### ISSUE TITLE
Unable to use Tap (possibly other touch actions) using pageobject's proxied element 

### ISSUE THREAD

**Issue by glorylo** [appium/appium-dotnet-driver#103]
If you were to use touch actions on elements such as the following:

           // double tapping on element
           new TouchAction(driver).
               Tap(element, x, y, 2)
               .Perform();    

where element is derived from using pageobjects.. this results in the exception:

Additional information: Field 'elementId' defined on type 'OpenQA.Selenium.Remote.RemoteWebElement' is not a field on the target object which is of type 'OpenQA.Selenium.Appium.Android.AndroidElement'.

Seems to be a bug but is there a new way to interact w/ touch actions + page objects?

**Comment by Astro03** [comment]
@TikhomirovSergey  might be able to help you.I do not know much about page objects.

**Comment by TikhomirovSergey** [comment]
Oopps! I'll fix it soon. Thanks for the report!

**Comment by glorylo** [comment]
@TikhomirovSergey  ok thanks for update.  i only noticed the new change w/ the generics driver and the use of new proxy element.  I had been using an older appium version for awhile.

**Comment by TikhomirovSergey** [comment]
Today I'll publish the new release. The root cause is that I didn't know that TouchActions tries to cast an element to RemoteWebElement. Actually the given element is the instance of a proxy-class provided by Castle.Core framework. Fortunately these proxies implement IWrapsElement. This point should be added to wiki.

**Comment by glorylo** [comment]
thanks!  yes, i realize you were using a proxy element.  I'll retest once you release it.

**Comment by TikhomirovSergey** [comment]
@glorylo 1.4.0.3 has been released. Now you can check the bug fix. If you are sure that the problem is resolved please close this ticket. I'm waiting for your response.

**Comment by glorylo** [comment]
i just checked it!  the fix works!  :+1: 

closing
