### ISSUE TITLE
How to use TouchActions in Selendroid Mode

### ISSUE THREAD

**Issue by EthanJiang** [appium/appium-dotnet-driver#113]
Hello

I am trying to do touchaction in selendroid mode, but as you know, we can't use the OpenQA.Selenium.Appium.MultiTouch.TouchAction directly.  So I thought, I can use the 
OpenQA.Selenium.Interactions.TouchActions to work with AndroidDriver<AndroidElement>. 

But it does not work.

So How to do TouchAction (eg. Press, Move ...) in selendroid mode?

Code:
                 AndroidDriver<AndroidElement>   fdriver = new AndroidDriver<AndroidElement>(
                        new Uri("http://127.0.0.1:4732/wd/hub"),
                        capabilities,
                        TimeSpan.FromSeconds(600));

            IWebElement element2 = fdriver.FindElement(By.Id("showcase_button"));
            TouchActions action = new TouchActions((IWebDriver)fdriver);
            action.Click(element2).Perform();

**Comment by TikhomirovSergey** [comment]
Hi @EthanJiang 
It is most likely the server side problem. Which server version do you use?

**Comment by EthanJiang** [comment]
Hi 

Thanks for replying. 

I use the latest AppiumForWindows_1_4_13_1.  

So No way to do touchaction in Selendroid mode?

Thanks

**Comment by EthanJiang** [comment]
Hi 

I have figure out how to fix the issue..
I need to write my on android driver like:

public class MYDriver : AndroidDriver, IHasTouchScreen where W : IWebElement
{
...
        public MYDriver(Uri remoteAddress, DesiredCapabilities desiredCapabilities, TimeSpan commandTimeout)
            : base(remoteAddress, desiredCapabilities, commandTimeout)
        {
            TouchScreen = new RemoteTouchScreen(this);
        }

        public ITouchScreen TouchScreen
        {
            get; private set;
        }
}

The purpose is to inherit from IHasTouchScreen.

So I close the this.

Maybe you can add this directly to AndroidDriver.

**Comment by TikhomirovSergey** [comment]
@EthanJiang 
It is the server-side problem. There are collisions between Selendroid API and Uatomator API. There are lots of reports about problems like yours here: https://github.com/appium/appium/issues

I think the best way to resolve these problems is to resolve these collisions on the server side.
