### ISSUE TITLE
Masroor

### ISSUE THREAD

**Issue by gaditek** [appium/appium-dotnet-driver#114]
Please resove this issue i have VS 2010 and appium server :1.4.13.1 and selinum web driver: 2.48.0
Im faceing this below issue:
When my app launch on device on first activity my test case fails.

using System;
using System.Text;
using System.Collections.Generic;
using System.Linq;
using OpenQA.Selenium;
using OpenQA.Selenium.Appium;
using OpenQA.Selenium.Appium.Android;
using OpenQA.Selenium.Remote;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace testappium2010
{
    [TestClass]
    public class UnitTest1
    {
        private AppiumDriver<AppiumWebElement> driver;
        
        [TestMethod]
        public void TestMethod1()
        {
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.SetCapability("deviceName", "Nexus 5");
            capabilities.SetCapability("platformName", "Android");
            capabilities.SetCapability(CapabilityType.Platform, "Windows");
            capabilities.SetCapability("app", @"C:\Users\Administrator\Downloads\app-debug.apk");
            capabilities.SetCapability("device ID", "uniquedeviceid");
            capabilities.SetCapability("platformVersion", "5.0.1");
            capabilities.SetCapability("appPackage", "org.cprados.wificellmanager");
            capabilities.SetCapability("appActivity", "org.cprados.wificellmanager.auth.AuthActivity");

            driver = new AndroidDriver<AppiumWebElement>(new Uri("http://127.0.0.1:8082/wd/hub"), capabilities, TimeSpan.FromSeconds(180));
            
        }
    }
}

Error message comes: Method not found: 'OpenQA.Selenium.Remote.CommandInfoRepository OpenQA.Selenium.Remote.CommandInfoRepository.get_Instance()'.

Appium server error:  info: [debug] Proxied response received with status 200: {"sessionId":"cb065201-a001-29e9-4061-bed77cc65155","status":0,"value":{"warnings":{},"desired":{"deviceName":"Nexus 5","platformName":"Android","platform":"Windows","app":"C:\\Users\\Administrator\\Downloads\\app-debug.apk","device ID":"uniquedeviceid","platformVersion":"5.0.1","appPackage":"org.cprados.wificellmanager","appActivity":"org.cprados.wificellmanager.auth.AuthActivity"},"deviceName":"Nexus 5","platformName":"android","platform":"android","app":"C:\\Users\\Administrator\\Downloads\\app-debug.apk","device ID":"uniquedeviceid","platformVersion":"21","appPackage":"org.cprados.wificellmanager","appActivity":"org.cprados.wificellmanager.auth.AuthActivity","takesScreenshot":true,"browserName":"selendroid","automationName":"selendroid","rotatable":true,"handlesAlerts":true,"javascriptEnabled":true,"networkConnectionEnabled":true,"version":"0.15.0","acceptSslCerts":true}}
> info: <-- GET /wd/hub/session/cb065201-a001-29e9-4061-bed77cc65155 200 61.709 ms - 888

**Comment by TikhomirovSergey** [comment]
@gaditek
Hi. This issue is already reported.
#112
I think that there is a dependency conflict. By default the last stable version uses Selenium.WebDriver and Selenium.Support 2.47.0. 

For now I advice to revert your Selenium.WebDriver dependency to 2.47.0.

**Comment by pshilpa1** [comment]
I am trying to use Appium to test Selenium webdriver C# scripts on real iPad device.
Getting error that 
Result StackTrace:	
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
   at UnitTestProject2.UnitTest1.TestMethod1() in C:\ED\TestAutomation\Ed.LMS\Main\UnitTestProject2\UnitTestProject2\UnitTest1.cs:line 29
Result Message:	
Test method UnitTestProject2.UnitTest1.TestMethod1 threw exception: 
System.InvalidOperationException: A new session could not be created. (Original error: ENOENT, stat '/Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip') (33)

Tried looking for this folder on mac and found it doesn't exist there. Came across this post and tried running ./reset.sh but unable to run ./reset.sh  on mac. I already have safarilauncher installed on ipad.
Appium is under Applications and I looked into its content using Show package contents but no clue how to get to this folder contents from Terminal and how to run that command to have a SafariLauncher folder in Appium.../build.

Please help.
I have a valid development profile, provisioning profile on apple developer and my device is registered there too.
Please help.

Thanks in advance

**Comment by Astro03** [comment]
@pshilpa1 - hey there, i don't see how your issue and the issue above relate (mind you, the issue above is also closed).  Please create a new issue and i'll be glad to chat there.

**Comment by pshilpa1** [comment]
Created new issue 143.

Thanks

**Comment by Anum-Zargar** [comment]
Hi All,

I am facing a issue.Have written a simple code to invoke appium server.But the error is thrown for setting URI.
Please help me someone,its urgent 👎 


using System;
using System.IO;
using System.Threading;

using OpenQA.Selenium;
using OpenQA.Selenium.Appium;
using OpenQA.Selenium.Appium.Android;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Appium.iOS;
using System.Diagnostics;
using OpenQA.Selenium.Appium.Service;
using NUnit.Framework;



namespace Test_Project
{
    public class Program
    {
        //Create insatnce for appium
        AppiumDriver<IWebElement> driver;


        AppiumLocalService service = null;
        public AppiumDriver<IWebElement> getDriver()
        {
            return driver;
        }
       
        [SetUp]
        public void Initdriver()
        {
           
     
            String apkPath;
            DesiredCapabilities cap = new DesiredCapabilities();
            cap.SetCapability("deviceName", "Anum");
            cap.SetCapability("platformName", "Android");
            cap.SetCapability("udid", "emulator-5554");
            // apkPath = AppDomain.CurrentDomain.BaseDirectory.Replace("\\bin\\Debug", "") + "Apk/";
            cap.SetCapability("platformVersion", "8.1");
            cap.SetCapability("app", "@C:\\Users\\azargar\\source\\repos\\Store_Simple\\Store_Simple_Project\\Store_Simple_Project\\Apk\\mobile-prod-release-signed.apk" + "mobile-prod-release-signed.apk");
            cap.SetCapability("appPackage", "com.cineplex.storefront");
            cap.SetCapability("appActivity", "com.cineplex.store.android.main.MainActivity");
            //cap.SetCapability("fullReSet", true);
            cap.SetCapability("newCommandTimeout", 120);
            //  System.Uri uri = new System.Uri("http://127.0.0.1:4723/wd/hub");
            //System.Uri uri = new System.Uri(appiumURL);
            driver = new AndroidDriver<AndroidElement>(new Uri("http://127.0.0.1:4723/wd/hub"), cap);

        }

        [TearDown]
        public void AfterTest()
        {
            driver.Quit();
        }
    }
}



Error is :-
![Error](https://user-images.githubusercontent.com/59899232/75117256-dd0f9080-563d-11ea-83ee-d2761561a068.PNG)
