### ISSUE TITLE
Defect: Failed to get the right AndroidDriver.PageSource in selendroid mode

### ISSUE THREAD

**Issue by EthanJiang** [appium/appium-dotnet-driver#117]
When invoke AndroidDriver.PageSource at first time, It works fines.  but when the call it on the next new UI, the page source still keep on the first value. 

maybe this is a server issue.

info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/window_handles","method":"GET"}
info: [debug] Available contexts: ["NATIVE_APP"]
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"97d48e9b-f365-1e1d-b745-daeab98a5ce6"}
info: <-- POST /wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/context 200 5053.716 ms - 76 {"status":0,"value":null,"sessionId":"97d48e9b-f365-1e1d-b745-daeab98a5ce6"}
info: --> GET /wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/source {}
info: [debug] Proxying command to localhost:8080
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/source","method":"GET"}
info: [debug] Proxied response received with status 200: {"value":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><views><DecorView name=\"\" label=\"\" value=\"\" ref=\"31938481-d205-2bd3-191b-94e127ed5bb2\" id=\"\" shown=\"true\"><rect x=\"0\" y=\"0\" height=\"1186\" width=\"720\"/><LinearLayout name=\"\" label=\"\" value=\"\" ref=\"cd437380-693f-f2be-fe47-21c1fd0df9b4\" id=\"\" shown=\"true\"><rect x=\"0\" y=\"0\" height=\"1186\" width=\"720\"/><ViewStub name=\"\" label=\"\" value=\"\" ref=\"5223ee70-f86a-3f66-3468-0154f55ffabf\" id=\"action_mode_bar_stub\" shown=\"false\"><rect x=\"0\" y=\"0\" height=\"0\" width=\"0\"/></ViewStub><FrameLayout name=\"\" label=\"\" value=\"\" ref=\"31903a5f-ae73-db24-37bb-acdb5ed1674d\" id=\"\" shown=\"true\"><rect x=\"0\" y=\"49\" height=\"1137\" width=\"720\"/><ActionBarOverlayLayout name=\"\" label=\"\" value=\"\" ref=\"61c7f402-a234-62fb-cd00-927bdc8f16f9\" id=\"decor_content_parent\" shown=\"true\"><rect x=\"0\" y=\"49\" height=\"1137\" width=\"720\"/><ContentFrameLayout name=\"\" label=\"\" value=\"\" ref=\"deebc092-7dd8-0db6-79fe-9bd431c27afb\" id=\"content\" shown=\"true\"><rect x=\"0\" y=\"158\" height=\"1028\" width=\"720\"/><DrawerLayout name=\"\" label=\"\" value=\"\" ref=\"24a77124-aece-8bc2-7dac-38fcaf745615\" id=\"drawer_layout\" shown=\"true\"><rect x=\"0\" y=\"158\" height=\"1028\" width=\"720\"/><FrameLayout name=\"\" label=\"\" value=\"\" ref=\"2f24d1f6-9e7c-0958-817b-24b605304809\" id=\"content_frame\" shown=\"true\"><rect x=\"0\" y=\"158\" height=\"1028\" width=\"720\"/><RelativeLayout name=\"\" label=\"\" value=\"\" ref=\"23190ff6-8b50-1b56-9aa3-33a9b87382e8\" id=\"\" shown=\"true\"><rect x=\"0\" y=\"158\" height=\"1028\" width=\"720\"/><GridView name=\"\" label=\"\" value=\"\" ref=\"f47560fe-d1e2-5a06-579d-c40480bf686e\" id=\"gridViewBottom\" shown=\"true\"><rect x=\"0\" y=\"158\" height=\"1028\" width=\"720\"/><GalleryCheckableRelativeLayout name=\"\" label=\"\" value=\"\" ref=\"7e020232-50f1-75da-6513-ee80075480b8\" id=\"\" shown=\"true\"><rect x=\"20\" y=\"400\" height=\"177\" width=\"680\"/><LinearLayout name=\"\" label=\"\" value=\"\" ref=\"50f6aabf-7ad1-49a7-83e8-17c988068d8e\" id=\"\" shown=\"true\"><rect x=\"22\" y=\"402\" height=\"173\" width=\"676\"/><LinearLayout name=\"\" label=\"\" value=\"\" ref=\"a2c0b012-3709-09c5-cf57-a714ac9f7388\" id=\"frameLayout1\" shown=\"true\"><rect x=\"22\" y=\"402\" height=\"117\" width=\"676\"/><LinearLayout name=\"\" label=\"\" value=\"\" ref=\"e5ce6303-b3ed-344d-45d3-c1e6f8f34707\" id=\"\" shown=\"true\"><rect x=\"22\" y=\"402\" height=\"117\" width=\"329\"/><AppCompatTextView name=\"\" label=\"\" value=\"No scanners available\" ref=\"049d749b-fc0e-dbd4-8654-52688408fb95\" id=\"device\" shown=\"false\"><rect x=\"22\" y=\"402\" height=\"0\" width=\"0\"/></AppCompatTextView><ImageView name=\"\" label=\"\" value=\"\" ref=\"93273b01-db84-f6cd-2eca-12e1038e13c9\" id=\"icon\" shown=\"true\"><rect x=\"22\" y=\"402\" height=\"117\" width=\"329\"/></ImageView><AppCompatTextView name=\"\" label=\"\" value=\"192.168.1.104\" ref=\"4b19f6a8-e9c2-340c-1ab2-fb51c34e14b8\" id=\"ip\" shown=\"false\"><rect x=\"22\" y=\"402\" height=\"0\" width=\"0\"/></AppCompatTextView></LinearLayout><ImageView name=\"\" label=\"\" value=\"\" ref=\"7e5991e3-2dfa-5dd1-cdcc-4841fc1ec7f0\" id=\"arrow\" shown=\"true\"><rect x=\"351\" y=\"402\" height=\"117\" width=\"19\"/></ImageView><LinearLayout name=\"\" label=\"\" value=\"\" ref=\"cec1c13a-8b41-b76f-d85d-53cfc6166878\" id=\"\" shown=\"true\"><rect x=\"370\" y=\"402\" height=\"117\" width=\"328\"/><ImageView name=\"\" label=\"\" value=\"\" ref=\"6e1273c7-c8a7-29c3-a4f4-0a783043c5bb\" id=\"dest\" shown=\"true\"><rect x=\"370\" y=\"402\" height=\"117\" width=\"328\"/></ImageView></LinearLayout></LinearLayout><LinearLayout name=\"\" label=\"\" value=\"\" ref=\"3f5ecb10-5025-e40a-4285-83c6b4b602e7\" id=\"\" shown=\"true\"><rect x=\"22\" y=\"519\" height=\"56\" width=\"676\"/><LinearLayout name=\"\" label=\"\" value=\"\" ref=\"3b47249c-3bb0-62a6-e3b6-b74a4ed3cb2d\" id=\"\" shown=\"true\"><rect x=\"22\" y=\"519\" height=\"56\" width=\"676\"/><AppCompatTextView name=\"\" label=\"\" value=\"Scan To Email\" ref=\"b4346262-ba35-5a87-edff-43f729df3081\" id=\"label\" shown=\"true\"><rect x=\"22\" y=\"519\" height=\"56\" width=\"590\"/></AppCompatTextView><ImageButton name=\"\" label=\"\" value=\"\" ref=\"beab8aa2-387e-350e-6f49-531ba4dc10fd\" id=\"popupButton\" shown=\"true\"><rect x=\"612\" y=\"519\" height=\"56\" width=\"86\"/></ImageButton></LinearLayout></LinearLayout></LinearLayout></GalleryCheckableRelativeLayout><GalleryCheckableRelativeLayout name=\"\" label=\"\" value=\"\" ref=\"aa7b2a04-cc0a-9b75-d106-2a20d3e1cf03\" id=\"\" shown=\"true\"><rect x=\"20\" y=\"635\" height=\"177\" width=\"680\"/><LinearLayout name=\"\" label=\"\" value=\"\" ref=\"28c8c999-9e18-3046-eed5-9aa86e2491b9\" id=\"\" shown=\"true\"><rect x=\"22\" y=\"637\" height=\"173\" width=\"676\"/><LinearLayout name=\"\" label=\"\" value=\"\" ref=\"a7ddda02-a7eb-df9a-c601-e4684d34942b\" id=\"frameLayout1\" shown=\"true\"><rect x=\"22\" y=\"637\" height=\"117\" width=\"676\"/><LinearLayout name=\"\" label=\"\" value=\"\" ref=\"4eb9c8ba-9cd8-2f6d-f0bc-6367cf0c0646\" id=\"\" shown=\"true\"><rect x=\"22\" y=\"637\" height=\"117\" width=\"329\"/><AppCompatTextView name=\"\" label=\"\" value=\"No scanners available\" ref=\"0645a3b6-abf2-7492-515c-032dcbfd2323\" id=\"device\" shown=\"false\"><rect x=\"22\" y=\"637\" height=\"0\" width=\"0\"/></AppCompatTextView><ImageView name=\"\" label=\"\" value=\"\" ref=\"c3bead04-573d-1856-ca4a-8398641a0d7c\" id=\"icon\" shown=\"true\"><rect x=\"22\" y=\"637\" height=\"117\" width=\"329\"/></ImageView><AppCompatTextView name=\"\" label=\"\" value=\"192.168.1.104\" ref=\"67638f58-9dd9-d497-5f57-3a7fbf454a8a\" id=\"ip\" shown=\"false\"><rect x=\"22\" y=\"637\" height=\"0\" width=\"0\"/></AppCompatTextView></LinearLayout><ImageView name=\"\" label=\"\" value=\"\" ref=\"4a239fa7-6b4b-4465-d968-b2ff0716eb9b\" id=\"arrow\" shown=\"true\"><rect x=\"351\" y=\"637\" height=\"117\" width=\"19\"/></ImageView><LinearLayout name=\"\" label=\"\" value=\"\" ref=\"93691223-115d-1721-c76c-c3d42639a68c\" id=\"\" shown=\"true\"><rect x=\"370\" y=\"637\" height=\"117\" width=\"328\"/><ImageView name=\"\" label=\"\" value=\"\" ref=\"16d4c04b-262d-9e26-7883-55437550f991\" id=\"dest\" shown=\"true\"><rect x=\"370\" y=\"637\" height=\"117\" width=\"328\"/></ImageView></LinearLayout></LinearLayout><LinearLayout name=\"\" label=\"\" value=\"\" ref=\"0ef131f5-b23b-3d18-cb45-4ecb08e8d5f1\" id=\"\" shown=\"true\"><rect x=\"22\" y=\"754\" height=\"56\" width=\"676\"/><LinearLayout name=\"\" label=\"\" value=\"\" ref=\"f7c8007e-7163-2f68-e9e6-56da01935721\" id=\"\" shown=\"true\"><rect x=\"22\" y=\"754\" height=\"56\" width=\"676\"/><AppCompatTextView name=\"\" label=\"\" value=\"Scan To Dropbox\" ref=\"cb5329e4-1065-1295-35a1-d94a52450ced\" id=\"label\" shown=\"true\"><rect x=\"22\" y=\"754\" height=\"56\" width=\"590\"/></AppCompatTextView><ImageButton name=\"\" label=\"\" value=\"\" ref=\"06854a7f-0239-a3ec-8728-08d19216ee6a\" id=\"popupButton\" shown=\"true\"><rect x=\"612\" y=\"754\" height=\"56\" width=\"86\"/></ImageButton></LinearLayout></LinearLayout></LinearLayout></GalleryCheckableRelativeLayout><GalleryCheckableRelativeLayout name=\"\" label=\"\" value=\"\" ref=\"faa5c4d8-ff12-552e-7704-84009f503db7\" id=\"\" shown=\"true\"><rect x=\"20\" y=\"870\" height=\"177\" width=\"680\"/><LinearLayout name=\"\" label=\"\" value=\"\" ref=\"baf21bb2-2c2f-356e-6e8f-f0d7812b0e3b\" id=\"\" shown=\"true\"><rect x=\"22\" y=\"872\" height=\"173\" width=\"676\"/><LinearLayout name=\"\" label=\"\" value=\"\" ref=\"08ff815c-c8c3-b19f-3df9-fed2177dc133\" id=\"frameLayout1\" shown=\"true\"><rect x=\"22\" y=\"872\" height=\"117\" width=\"676\"/><LinearLayout name=\"\" label=\"\" value=\"\" ref=\"0ceaaf98-984d-eba3-264f-a3a284ff8053\" id=\"\" shown=\"true\"><rect x=\"22\" y=\"872\" height=\"117\" width=\"329\"/><AppCompatTextView name=\"\" label=\"\" value=\"No scanners available\" ref=\"a8d3b2df-2bfb-3539-8d60-46cc120f45f0\" id=\"device\" shown=\"false\"><rect x=\"22\" y=\"872\" height=\"0\" width=\"0\"/></AppCompatTextView><ImageView name=\"\" label=\"\" value=\"\" ref=\"387f1b25-a6d8-2f15-3c72-fa221e72cdfd\" id=\"icon\" shown=\"true\"><rect x=\"22\" y=\"872\" height=\"117\" width=\"329\"/></ImageView><AppCompatTextView name=\"\" label=\"\" value=\"192.168.1.104\" ref=\"31e7db00-eba5-7606-39d6-8c99e7f5869e\" id=\"ip\" shown=\"false\"><rect x=\"22\" y=\"872\" height=\"0\" width=\"0\"/></AppCompatTextView></LinearLayout><ImageView name=\"\" label=\"\" value=\"\" ref=\"12b97c32-9651-0c48-4154-fd04cd6eea41\" id=\"arrow\" shown=\"true\"><rect x=\"351\" y=\"872\" height=\"117\" width=\"19\"/></ImageView><LinearLayout name=\"\" label=\"\" value=\"\" ref=\"75513555-7c6d-13c5-46b8-caff43257632\" id=\"\" shown=\"true\"><rect x=\"370\" y=\"872\" height=\"117\" width=\"328\"/><ImageView name=\"\" label=\"\" value=\"\" ref=\"66f65a5d-cb6f-027b-d5b0-851827f35be9\" id=\"dest\" shown=\"true\"><rect x=\"370\" y=\"872\" height=\"117\" width=\"328\"/></ImageView></LinearLayout></LinearLayout><LinearLayout name=\"\" label=\"\" value=\"\" ref=\"07e64407-0d32-2c91-74a4-f8b8170db853\" id=\"\" shown=\"true\"><rect x=\"22\" y=\"989\" height=\"56\" width=\"676\"/><LinearLayout name=\"\" label=\"\" value=\"\" ref=\"59f64f3f-f4b3-7a12-d6b4-04903bad9522\" id=\"\" shown=\"true\"><rect x=\"22\" y=\"989\" height=\"56\" width=\"676\"/><AppCompatTextView name=\"\" label=\"\" value=\"Scan To Box\" ref=\"1c0d4a3d-359b-8217-1c2a-d81f276853a5\" id=\"label\" shown=\"true\"><rect x=\"22\" y=\"989\" height=\"56\" width=\"590\"/></AppCompatTextView><ImageButton name=\"\" label=\"\" value=\"\" ref=\"7cc6a7b6-fa6e-5bc4-b7ee-714b68bf0693\" id=\"popupButton\" shown=\"true\"><rect x=\"612\" y=\"989\" height=\"56\" width=\"86\"/></ImageButton></LinearLayout></LinearLayout></LinearLayout></GalleryCheckableRelativeLayout><GalleryCheckableRelativeLayou
info: <-- GET /wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/source 200 282.491 ms - 25952
info: --> GET /wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/context {}
info: [debug] Responding to client with success: {"status":0,"value":"NATIVE_APP","sessionId":"97d48e9b-f365-1e1d-b745-daeab98a5ce6"}
info: <-- GET /wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/context 200 4.951 ms - 84 {"status":0,"value":"NATIVE_APP","sessionId":"97d48e9b-f365-1e1d-b745-daeab98a5ce6"}
info: --> POST /wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/context {"name":"NATIVE_APP"}
info: [debug] Getting a list of available webviews
info: [debug] executing cmd: D:\Android\android-sdk\platform-tools\adb.exe -s 169.254.191.177:5555 shell "cat /proc/net/unix"
info: [debug] Available contexts: NATIVE_APP
info: [debug] []
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/window_handles","method":"GET"}
info: [debug] Available contexts: ["NATIVE_APP"]
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"97d48e9b-f365-1e1d-b745-daeab98a5ce6"}
info: <-- POST /wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/context 200 5057.357 ms - 76 {"status":0,"value":null,"sessionId":"97d48e9b-f365-1e1d-b745-daeab98a5ce6"}
info: --> GET /wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/context {}
info: [debug] Responding to client with success: {"status":0,"value":"NATIVE_APP","sessionId":"97d48e9b-f365-1e1d-b745-daeab98a5ce6"}
info: <-- GET /wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/context 200 3.512 ms - 84 {"status":0,"value":"NATIVE_APP","sessionId":"97d48e9b-f365-1e1d-b745-daeab98a5ce6"}
info: --> POST /wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/context {"name":"NATIVE_APP"}
info: [debug] Getting a list of available webviews
info: [debug] executing cmd: D:\Android\android-sdk\platform-tools\adb.exe -s 169.254.191.177:5555 shell "cat /proc/net/unix"
info: [debug] Available contexts: NATIVE_APP
info: [debug] []
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/window_handles","method":"GET"}
info: [debug] Available contexts: ["NATIVE_APP"]
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"97d48e9b-f365-1e1d-b745-daeab98a5ce6"}
info: <-- POST /wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/context 200 5061.786 ms - 76 {"status":0,"value":null,"sessionId":"97d48e9b-f365-1e1d-b745-daeab98a5ce6"}
info: --> GET /wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/context {}
info: [debug] Responding to client with success: {"status":0,"value":"NATIVE_APP","sessionId":"97d48e9b-f365-1e1d-b745-daeab98a5ce6"}
info: <-- GET /wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/context 200 6.103 ms - 84 {"status":0,"value":"NATIVE_APP","sessionId":"97d48e9b-f365-1e1d-b745-daeab98a5ce6"}
info: --> POST /wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/context {"name":"NATIVE_APP"}
info: [debug] Getting a list of available webviews
info: [debug] executing cmd: D:\Android\android-sdk\platform-tools\adb.exe -s 169.254.191.177:5555 shell "cat /proc/net/unix"
info: [debug] Available contexts: NATIVE_APP
info: [debug] []
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/window_handles","method":"GET"}
info: [debug] Available contexts: ["NATIVE_APP"]
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"97d48e9b-f365-1e1d-b745-daeab98a5ce6"}
info: <-- POST /wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/context 200 5060.016 ms - 76 {"status":0,"value":null,"sessionId":"97d48e9b-f365-1e1d-b745-daeab98a5ce6"}
info: --> GET /wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/context {}
info: [debug] Responding to client with success: {"status":0,"value":"NATIVE_APP","sessionId":"97d48e9b-f365-1e1d-b745-daeab98a5ce6"}
info: <-- GET /wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/context 200 6.941 ms - 84 {"status":0,"value":"NATIVE_APP","sessionId":"97d48e9b-f365-1e1d-b745-daeab98a5ce6"}
info: --> POST /wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/context {"name":"NATIVE_APP"}
info: [debug] Getting a list of available webviews
info: [debug] executing cmd: D:\Android\android-sdk\platform-tools\adb.exe -s 169.254.191.177:5555 shell "cat /proc/net/unix"
info: [debug] Available contexts: NATIVE_APP
info: [debug] []
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/window_handles","method":"GET"}
info: [debug] Available contexts: ["NATIVE_APP"]
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"97d48e9b-f365-1e1d-b745-daeab98a5ce6"}
info: <-- POST /wd/hub/session/97d48e9b-f365-1e1d-b745-daeab98a5ce6/context 200 5079.448 ms - 76 {"status":0,"value":null,"sessionId":"97d48e9b-f365-1e1d-b745-daeab98a5ce6"}

**Comment by TikhomirovSergey** [comment]
Hi @EthanJiang 
It is probably server-side error and it is most likely this issue:
https://github.com/appium/appium/issues/2865

Also you can see how many issues about the getting of page sources have been reported:
https://github.com/appium/appium/search?utf8=%E2%9C%93&q=PageSource+&type=Issues

I'll keep this ticket opened to avoid the duplication.

**Comment by akinsolb** [comment]
Closing as not a .Net client issue.
