### ISSUE TITLE
How can i get a list of subclasses?

### ISSUE THREAD

**Issue by ManishKohli** [appium/appium-dotnet-driver#118]
Hi, I have a situation where im trying to automate a mobile app. 

Im trying to open the burger menu -> Get all the sub-classes under one main class and then iterate through them. 

![image](https://cloud.githubusercontent.com/assets/15723149/11025649/9b68897a-8702-11e5-8212-ef0abe3748c3.png)

ExpandableListView has a class. And i want to get all the sub-classes for RelativeLayout under it. 

Any help will be appreciated.

**Comment by TikhomirovSergey** [comment]
I can't understand...
Do you want to get all subelements using Appium and .NET client?

So you can try 

```c#
driver.FindElement(By.ClassName("android.widget.ExpandableListView")).FindElements(By.XPath(xpath))
```

How to build an XPath for Android please take a look at 
http://www.toolsqa.com/selenium-webdriver/choosing-effective-xpath/
http://stackoverflow.com/questions/16952514/selenium-webdriver-findelementby-xpath-not-working-for-me
http://stackoverflow.com/questions/26159603/need-to-identify-xpath-for-android-element-using-appium
and tons of stuff which you can find by Google.

**Comment by ManishKohli** [comment]
Thanks alot! Funny thing is, i tried the same about 5 minutes ago and it worked for me. Thanks though!
