### ISSUE TITLE
Continuos builds/deployment and PR workflow validation improvement

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/appium-dotnet-driver#124]
In 2014 .NET client was the very small library. Since that time it has growing to framework (I think). Number of contributors increases. There are lots of improvements.
- 1. We need to automate the building and deployment.
- 2. We need to enhance PR state workflow.

The first we could do with Jenkins CI or [Travis CI](https://travis-ci.org/) (like the Selenium project does).

The second should include:
- the PR checking with CI (it is connected to point 1)
- (optionally) the code style checking

**Comment by akinsolb** [comment]
Superseded by #260
