### ISSUE TITLE
SendKeys doesn't clear the existing text on Android

### ISSUE THREAD

**Issue by Frankwin** [appium/appium-dotnet-driver#146]
## Description

When using SendKeys, any existing text in a field on Android is not cleared and there's no option to specify it should be cleared.
## Environment
- .NET client build version: Latest
- Appium server version: 1.4.16.1
- Desktop OS/version used to run Appium: Windows 10
- Mobile platform/version under test: Android 6.0.1
- Real device or emulator/simulator: Real device
## Details

When sending the SendKeys command, the Appium server shows the following output:
`> info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"361e565c-0dde-4e23-9ba4-d0143a290120"}

> info: <-- POST /wd/hub/session/361e565c-0dde-4e23-9ba4-d0143a290120/timeouts 200 0.668 ms - 76 {"status":0,"value":null,"sessionId":"361e565c-0dde-4e23-9ba4-d0143a290120"}
> info: --> POST /wd/hub/session/361e565c-0dde-4e23-9ba4-d0143a290120/element/14/value {"value":["Turn them green"]}
> info: [debug] Pushing command to appium work queue: ["element:setText",{"elementId":"14","text":"Turn them green","replace":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"14","text":"Turn them green","replace":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: setText
> info: [debug] [BOOTSTRAP] [debug] Using element passed in.
> info: [debug] [BOOTSTRAP] [debug] Attempting to clear using UiObject.clearText().
> info: [debug] [BOOTSTRAP] [debug] Sending plain text to element: Turn them green
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"361e565c-0dde-4e23-9ba4-d0143a290120"}
> info: <-- POST /wd/hub/session/361e565c-0dde-4e23-9ba4-d0143a290120/element/14/value 200 6133.356 ms - 76 {"status":0,"value":true,"sessionId":"361e565c-0dde-4e23-9ba4-d0143a290120"}
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}`

As you can see the command that gets passed to the Appium Work Queue (element.setText) has "replace":false as the parameter. There's no way (that I have found) to make this true so the value gets replaced. 
## Code To Reproduce Issue [ Good To Have ]

element.SendKeys("Turn them green");

**Comment by TikhomirovSergey** [comment]
@Frankwin 
Sorry for the late responce.

Why should it clear the text field? 
Anyway you are able to use 

```c#
element.Clear();
element.SendKeys("Turn them green");
```

or 

```c#
element.Clear();
element.ReplaceValue("Turn them green");
```

**Comment by Frankwin** [comment]
Unfortunately element.Clear doesn't work either. It doesn't clear the element contents.
element.ReplaceValue is not an option in C#

**Comment by TikhomirovSergey** [comment]
@Frankwin 
Is clear issue reproduced on server v 1.5.x?

>element.ReplaceValue is not an option in C#

Can you clarify things which happen?
We have the test which passes: https://github.com/appium/appium-dotnet-driver/blob/master/integration_tests/Android/AndroidElementTest.cs#L82

Could you add a gist with server log if some exception is thrown?

**Comment by Frankwin** [comment]
@TikhomirovSergey 
So I'm using IMobileElement<AppiumWebElement> as the element class since I'm testing a Cordova Web App, not a native Android App. This doesn't seem to support ReplaceValue and this is also where the Clear issue can be reproduced with.

**Comment by TikhomirovSergey** [comment]
@Frankwin So, is it hybrid app and you are trying to do do something in WebView?

**Comment by Frankwin** [comment]
@TikhomirovSergey Yes that's correct

**Comment by TikhomirovSergey** [comment]
@Frankwin 
Ok. I think there some refactor or additional method is needed...

**Comment by Nisim761** [comment]
Hi,
I am suffering from the same problem. Using Java jars (4.0.0), Selenium jar (2.5.3), Java.
WebElement.Clear() method doesn't do anything.
Also trying to send Keys.Delete \ BackSpace don't work either - simply move the cursor to the beginning of the line.
