### ISSUE TITLE
error: Could not proxy command to remote server. Original error: 404 - unknown command: session/{sessionId}/appium/device/press_keycode

### ISSUE THREAD

**Issue by mgaticah** [appium/appium-dotnet-driver#148]
## Description

When i use 

AndroidDriver PressKeyCode(AndroidKeyCode.Home)

I'm getting this error message in appium log

> error: Could not proxy command to remote server. Original error: 404 - unknown command: session/2ea99589ce0bde3933932747b6a4f306/appium/device/press_keycode

## Environment

* .NET client Appium Webdriver 1.5.1.1
* Appium 1.4.13.1
* Windows 7
* Node.js 
{ npm: '2.15.1',
  ares: '1.10.1-DEV',
  http_parser: '2.5.2',
  icu: '56.1',
  modules: '46',
  node: '4.4.3',
  openssl: '1.0.2g',
  uv: '1.8.0',
  v8: '4.5.103.35',
  zlib: '1.2.8' }

* Mobile platform/version under test:
Android 4.4.2
Android 6.0

* Real device 

Code Sample

   [TestMethod]
        public void GoandroidHome()
        {
            DesiredCapabilities caps;
            caps = new DesiredCapabilities();
            caps.SetCapability("deviceName", "05dda3adca4faf70");
            caps.SetCapability("platformName", "Android");
            caps.SetCapability("platformVersion", "4.4.2");
            caps.SetCapability("browserName", "chrome");
            AndroidDriver<IWebElement> driver = null;
            try
            {
                driver = new AndroidDriver<IWebElement>(new Uri("http://10.51.2.124:3580/wd/hub"), caps,
                                                        TimeSpan.FromSeconds(600));
                driver.PressKeyCode(AndroidKeyCode.Home);
            }
            catch (Exception ex)
            {
            }
            if (driver != null)
                    driver.Dispose();
            }
    }

## Ecxeption stacktraces

[Link to stacktrace](https://gist.github.com/mgaticah/4b1556c1c963fdff165d8924bdb4b95e)

## Link to Appium logs

[Link to appium log](https://gist.github.com/mgaticah/02b3eee7f73308a5b8c2a9ac850f1908)

**Comment by mgaticah** [comment]
I made it work.
As i see, is required to be on NATIVE_APP context to use it.

**Comment by TikhomirovSergey** [comment]
@mgaticah 
Sorry for the late responce. There are tons of work for the [Java client](https://github.com/appium/java-client).

>I made it work.
>As i see, is required to be on NATIVE_APP context to use it.

Yes you are right. Because when you switch to webview then it uses the chromedriver which may doesnt know about some commands. Also I see that you use old server (<1.5.0). May be in new versions it had been fixed.

Anyway it is not the client problem.
