### ISSUE TITLE
Getting element screenshots fails

### ISSUE THREAD

**Issue by jbaeten** [appium/appium-dotnet-driver#150]
## Description

Getting a screenshot of an element doesn't work.
## Environment
- Appium WebDriver 1.5.1.1
- Appium server 1.5.2
- Node.js version 4.4.4
- Mobile platform/version under test: Android
- Real device or emulator/simulator: Real device
## Details

Calling `.GetScreenshot()` on an AppiumWebElement seems to cause an invalid request to the Appium server, resulting in an error message: "Unexpected error. The URL ... did not map to a valid resource"
## Code To Reproduce Issue [ Good To Have ]

```
//Using the Android UI demo app. After setting up the driver object
AppiumWebElement el = driver.FindElementByAccessibilityId("Graphics");
el.GetScreenshot();
```
## Link to Appium logs

[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'Graphics' using 'ACCESSIBILITY_ID' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[DESCRIPTION=Graphics, INSTANCE=0]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"value":{"ELEMENT":"1"},"status":0}
[debug] [AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"1"}
[HTTP] <-- POST /wd/hub/session/2c8d3423-e9ff-451d-8670-41250698ad05/element 200 29 ms - 87
[HTTP] --> GET /wd/hub/session/2c8d3423-e9ff-451d-8670-41250698ad05/screenshot/1 {}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- GET /wd/hub/session/2c8d3423-e9ff-451d-8670-41250698ad05/screenshot/1 404 3 ms - 107

**Comment by nuKs** [comment]
Same issue

**Comment by KazuCocoa** [comment]
It is appreciated if you could create an issue on Appium repo since this issue is too old.
