### ISSUE TITLE
Appium.WebDriver 2.0.1.1 is not compatible with UAP,Version=v10.0

### ISSUE THREAD

**Issue by tnesham** [appium/appium-dotnet-driver#160]
## Description
Ran Install-Package Appium.WebDriver in Nuget package manager console and received error.

## Environment
OS Name	Microsoft Windows 10 Pro
Version	10.0.14393 Build 14393
Visual Studio 2015 
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01586
## Ecxeption stacktraces
Install-Package : Appium.WebDriver 2.0.1.1 is not compatible with UAP,Version=v10.0.
At line:1 char:1
+ Install-Package Appium.WebDriver
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Castle.Core 3.3.3 is not compatible with UAP,Version=v10.0.
At line:1 char:1
+ Install-Package Appium.WebDriver
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Some packages are not compatible with UAP,Version=v10.0.
At line:1 char:1
+ Install-Package Appium.WebDriver
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Appium.WebDriver 2.0.1.1 is not compatible with UAP,Version=v10.0 (win10-arm).
At line:1 char:1

**Comment by TikhomirovSergey** [comment]
@tnesham Which nuget version do you use?

**Comment by TikhomirovSergey** [comment]
I have no Windows 10 machine now. 
Is it possible to add the dependency on Selenium Webdriver to you current UWP project? 
I suspect that it is impossible too...

**Comment by tnesham** [comment]
@TikhomirovSergey I was following [https://medium.com/@yostane/automated-ui-testing-of-a-uwp-app-using-appium-dc10d8df6631#.lvcsj03zr](url) which was selecting the wrong project. I created a new Test project, which can be seen in the link but lower down, then it works. This can be closed.

**Comment by TikhomirovSergey** [comment]
Ok

**Comment by Templum** [comment]
@tnesham The/a solution based on @yodurr answer to [my issue](https://github.com/appium/appium-dotnet-driver/issues/165#issuecomment-262509350)

> Here's the response from Visual Studio on how to add the optional "Unit Test Project" template. It's an optional install with VS 2017. I'll update the winappdriver readme.

> With VS 2017, there has been a revamp of how users choose and install components on the machine.
> The Unit Test Project template (that appears under Test node) comes with the “.NET desktop development” workload.
