### ISSUE TITLE
AppiumFieldDecorator equivalent in .NET driver?

### ISSUE THREAD

**Issue by kpanwar** [appium/appium-dotnet-driver#162]
## Description
I am trying to initialize by my page elements using Page Object Pattern but realized that AppiumFieldDecorator is missing in .NET driver. If there an equivalent class that I may be missing or is this class just missing? If missing, what are my options for maintaining a sane object model for automating an app built for iOS/android/UWP/Win32?

## Environment

* .NET client latest

## Details

Description should be enough

## Code To Reproduce Issue [ Good To Have ]

N/A

## Ecxeption stacktraces

N/A

## Link to Appium logs

N/A

**Comment by TikhomirovSergey** [comment]
@kpanwar 
Could you show your case? Please provide it as a [gist](https://gist.github.com/)

**Comment by kpanwar** [comment]
@TikhomirovSergey - Here is the gist https://gist.github.com/kpanwar/98ddc4b6e272b5b3ee4c44496d6dfcee

Not sure how this helps, but here is the java class that does not exist in c# driver https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/pagefactory/AppiumFieldDecorator.java

**Comment by kpanwar** [comment]
I see that you have AppiumPageObjectMemberDecorator. Is that the equivalent class?

**Comment by kpanwar** [comment]
@TikhomirovSergey - can you confirm if this is an actual bug in the driver?

**Comment by kpanwar** [comment]
I made progress but I am running into an issue that is unrelated.

**Comment by akinsolb** [comment]
@kpanwar What progress did you make and how was this resolved? Are you now able to use the AppiumPageObjectDecorator class to initialise page object {class) members (properties)?
