### ISSUE TITLE
Cant Install Appium Driver into an Component Test App

### ISSUE THREAD

**Issue by Templum** [appium/appium-dotnet-driver#165]
## Description

When I try to install the driver via nuget, into my Component Test App. I receive the following console Output:
```shell
Package Castle.Core 3.3.3 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86. Package Castle.Core 3.3.3 supports:
  - net35 (.NETFramework,Version=v3.5)
  - net40-client (.NETFramework,Version=v4.0,Profile=Client)
  - net45 (.NETFramework,Version=v4.5)
  - sl4 (Silverlight,Version=v4.0)
  - sl5 (Silverlight,Version=v5.0)
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86).
Package Appium.WebDriver 2.0.1.1 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86-aot. Package Appium.WebDriver 2.0.1.1 supports: net45 (.NETFramework,Version=v4.5)
Package Selenium.WebDriver 2.53.1 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86-aot. Package Selenium.WebDriver 2.53.1 supports:
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
Package Selenium.Support 2.53.1 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86-aot. Package Selenium.Support 2.53.1 supports:
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
Package Castle.Core 3.3.3 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86-aot. Package Castle.Core 3.3.3 supports:
  - net35 (.NETFramework,Version=v3.5)
  - net40-client (.NETFramework,Version=v4.0,Profile=Client)
  - net45 (.NETFramework,Version=v4.5)
  - sl4 (Silverlight,Version=v4.0)
  - sl5 (Silverlight,Version=v5.0)
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86-aot).
Fehler bei der Paketwiederherstellung. Es wird ein Rollback der Paketänderungen für "Test" ausgeführt.
```
The Windows Application Driver should now enable me to write test for the UWP Plattform. Which seems to be incompatible. Are there any solutions to this issue ?

## Environment

* Appium.WebDriver 2.0.1.1 
* Visual Studio 2017 RC

## Details
-

## Code To Reproduce Issue [ Good To Have ]
-

## Ecxeption stacktraces
-

## Link to Appium logs
-

**Comment by jlipps** [comment]
@yodurr any chance some folks from your team might be able to take a look at this compatibility issue? we don't have any .net experts on the appium team, unfortunately...

**Comment by yodurr** [comment]
yup taking a look

**Comment by yodurr** [comment]
@Templum I believe the issue is with the "Unit Test App Project" template not being compatible.  In VS 2015 the project template we used was called "Unit Test" and did not generate an app.  I'm asking the Visual Studio team for more information on how to create a new Unit Test project in VS 2017.  

In the meantime feel free to use one of the samples on https://github.com/microsoft/winappdriver as a starting point instead of creating a new project and you should be good to go in VS 2017 RC.

**Comment by Templum** [comment]
@yodurr Thank you much for your efforts. I will give it a shoot

**Comment by TikhomirovSergey** [comment]
@jlipps @yodurr @Templum 
This is the duplicated issue.
https://github.com/appium/appium-dotnet-driver/issues/160

But the reported did not share the way to resolve.

**Comment by yodurr** [comment]
Here's the response from Visual Studio on how to add the optional "Unit Test Project" template.  It's an optional install with VS 2017.  I'll update the winappdriver readme.

With VS 2017, there has been a revamp of how users choose and install components on the machine. 
The Unit Test Project template (that appears under Test node) comes with the “.NET desktop development” workload.

**Comment by Templum** [comment]
Thanks @yodurr so this can be closed
