### ISSUE TITLE
Support for XCUITest driver and Appium 1.6 for testing iOS 10 devices

### ISSUE THREAD

**Issue by smithdf3** [appium/appium-dotnet-driver#167]
## Description
I don't believe there is support for the new XCUITest driver that is necessary for testing IOS 10 devices using Appium 1.6.  Is there a plan to add this at some point?  Thanks.

**Comment by TikhomirovSergey** [comment]
@smithdf3 This is not the client issue. It depends on the server side

**Comment by christoff-1992** [comment]
Is this an issue? .. slowly working on fixing the framework that I use. I have noticed a couple of things such as the AppiumDriver.getPageSource not matching the /inspector endpoint. (FB_WDA)

Including a case where table cell's have the same properties, including text values and name when the inspector has the correct values.

Only just realised that the driver may have not been updated.

**Comment by akinsolb** [comment]
Please raise server issues [here](https://github.com/appium/appium/issues)
