### ISSUE TITLE
SetLocation method for appium dot net driver not defined

### ISSUE THREAD

**Issue by markrhamilton** [appium/appium-dotnet-driver#170]
I have developed an Appium C# Automated Test Framework to test real Android devices and emulators.  Everything is working well in testing on local devices and emulators.  However, we are transitioning our test cases to run on a Test Cloud Service,  interacting with real devices.  One issue that we need to resolve is to set the GPS coordinates that our AUT will utilize to perform the tests accurately.

I have queried the Test Cloud service and they indicated the usage of the "SetLocation" method.  I have tried to use this AppiumDriver/Android Driver method, but I still get the error that the method is not defined.

## Environment

* .NET client build version or git revision if you use some shapshot:
![image](https://cloud.githubusercontent.com/assets/24232354/22803085/5ed1f0bc-eec8-11e6-9c6b-7ede358eef96.png)

All NuGet Packages have been upgraded:

![image](https://cloud.githubusercontent.com/assets/24232354/22803110/7c39be50-eec8-11e6-912d-6b6269f0cec4.png)

* Appium server version:  1.4.16.1
* Desktop OS/version: Windows 10 Professional
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: Android OS 6.0
* Real device or emulator/simulator: Real Device

Code To Reproduce Issue [ Good To Have ]

![image](https://cloud.githubusercontent.com/assets/24232354/22803534/3fc66b6a-eeca-11e6-9c53-0487ca4a90a7.png)

**Comment by TikhomirovSergey** [comment]
@markrhamilton 
There is the [property](https://github.com/appium/appium-dotnet-driver/blob/9151d8dd9b3b20574bcfe465a8588fda1efb8c3d/appium-dotnet-driver/Appium/AppiumDriver.cs#L416). And it seems it has being there for long time.

**Comment by TikhomirovSergey** [comment]
@markrhamilton Please reopen this issue if there are additional details
