### ISSUE TITLE
How to Scroll or swipe windows 8.1 store app

### ISSUE THREAD

**Issue by seenals** [appium/appium-dotnet-driver#172]
I am working on automating a Windows 8.1 store app. I am unable to perform an action of swipe or scroll using this appium dotnet driver. 

All samples given are for andriod or iOS applications. Please describe how to achieve scroll of an element in Windows 8.1 app. How to locate and perform an action on an element not visible in the view port. If scrolling is possible, it should be possible to scroll and locate the element.

Please help!

## Environment

* .NET client build version or git revision if you use some shapshot: Appium.WebDriver 3.0.0.2
* Mobile platform/version under test: Windows 8.1 store app.
* Real device or emulator/simulator: Desktop.

Code I tried
            IOSElement gridView = EAMUISession.FindElementByAccessibilityId("GridView");
            Point location = gridView.Location;
            Size size = gridView.Size;
            driver.Swipe(location.X + size.Width / 2, location.Y + size.Height / 2, location.X - 1, location.Y + size.Height / 2, 3000);

## Ecxeption stacktraces

Test Name:	TestMethod1
Test FullName:	EAMAutomation.EAMStructureTests.TestMethod1
Test Source:	D:\BNSF_TFS\EAM\OffShore\AutomationPoCs\Version1\EAMAutomation\EAMAutomation\EAMStructureTests.cs : line 134
Test Outcome:	Failed
Test Duration:	0:00:25.4036544

Result StackTrace:	
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.PerformTouchAction(ITouchAction touchAction)
   at OpenQA.Selenium.Appium.AppiumDriver`1.DoSwipe(Int32 startx, Int32 starty, Int32 endx, Int32 endy, Int32 duration)
   at OpenQA.Selenium.Appium.iOS.IOSDriver`1.Swipe(Int32 startx, Int32 starty, Int32 endx, Int32 endy, Int32 duration)
   at EAMAutomation.UnitTest1.HorizontalScroll() in ...\EAMAutomation\EAMAutomation\UnitTest1.cs:line 193
   at EAMAutomation.UnitTest1.TestMethod1() in ...\EAMAutomation\EAMAutomation\UnitTest1.cs:line 177
Result Message:	
Test method EAMAutomation.UnitTest1.TestMethod1 threw exception: 
System.InvalidOperationException: Missing Command Parameter: element

**Comment by yodurr** [comment]
Hi @seenals it's true we've got some room for improvement on scroll support in WinAppDriver
https://github.com/Microsoft/WinAppDriver/issues/145

The current answer is you can initialize a TouchScreen instance on the WindowsDriver session as shown here.
https://github.com/Microsoft/WinAppDriver/blob/master/Tests/W3CWebDriver/TouchBase.cs

Then you can call .Scroll on the TouchScreen.
https://github.com/Microsoft/WinAppDriver/blob/master/Tests/W3CWebDriver/TouchScroll.cs

That said, it's not working perfectly depending on your particular scenario so if you are still encountering an issue it would be great if you opened it on the WinAppDriver issue board.

Also right now this currently only works on Windows PC.  Mobile support is something we're working on and do not yet have an ETA.

Thanks,
Yosef

**Comment by seenals** [comment]
Thanks Yosef for the prompt reply.
I'm running my application on a Windows 10 PC and the application under test is a windows store app written using XAML and C#. It runs on the PC as well as on Windows tablet. For the UI automation, I'm running this in local machine ie. in the Windows 10 PC.

Is this solution you gave applicable only for a browser application? Since the TouchBase class seems to handle HttpRequest and HttpWebResponse. My app is Windows native app. Will this solution apply for a native app?  I tried the below code snippet

 RemoteTouchScreen touchScreen = new RemoteTouchScreen(driver);
 touchScreen.Scroll(0, 100);

It compiles, but no scrolling happening. Will it scroll to the screen which is not visible on the viewport currently. I need to scroll horizontally on the screen, to make some elements visible and perform some action on them.

Please share your thoughts and guidance. Also let me know whether WinAppDriver has to handle this?. In that case I can raise the issue there.

Thanks & Regards,
Seena L.S.

**Comment by seenals** [comment]
Any updates on this issue? Still waiting and looking for options to get the scrolling working for Windows apps using this appium dotnet driver. Tried the TouchAction class as well.

In the below code snipper driver is WindowsDriver<WindowsElement> initialized with app capabilities. 
This has no effect on the screen. I just want to scroll horizontally to different sections in the grid view and assert or perform actions on the elements in the grid.

WindowsElement gridView = driver.FindElementByAccessibilityId("zoomedinGridView");
TouchAction act = new TouchAction(driver);
                act.Press(gridView, gridView.Location.X, topY)
                    .MoveTo(centerX + 4000, topY)
                    .Release().Perform();

Please let me know a work around to make this work.

**Comment by yodurr** [comment]
Hi @seenals We hope to have touch down, move, up released in the next few weeks.

**Comment by seenals** [comment]
That will be great. Please keep us posted.

**Comment by TikhomirovSergey** [comment]
@seenals @yodurr I am going to remove the swiping from the client side.

**Comment by akinsolb** [comment]
Closing as per https://github.com/microsoft/WinAppDriver/issues/169. Upgrade of appium server required
