### ISSUE TITLE
How to access ComboBox selected item and select any other item when automating windows app

### ISSUE THREAD

**Issue by seenals** [appium/appium-dotnet-driver#178]
## Description

I have a date picker in windows app. When I use Inspect.exe, the control type for date and time are ComboBoxes. I want to read the value set in hour combobox and set it another value depending on a calculation.

I tried the below code snippet.
var hourDropDown = driver.FindElementByAccessibilityId("HourPicker");
SelectElement hourpicker = new SelectElement(hourPickerDropDown);

But the SelectElement statement is throwing the below exception
OpenQA.Selenium.Support.UI.UnexpectedTagNameException: **Element should have been select but was ControlType.ComboBox**

For WindowsApp, is there any other way to get the dropdown options?

## Environment

.NET client build version or git revision if you use some shapshot: Appium.WebDriver 3.0.0.2
Mobile platform/version under test: Windows 8.1 store app.
Real device or emulator/simulator: Desktop OS Windows 10
Executing WinAppDriver

## Code To Reproduce Issue

In windows 8.1 app, use a datepicker and use the code snippet below to get the item selected in th Hour dropdown.
var hourDropDown = driver.FindElementByAccessibilityId("HourPicker");
SelectElement hourpicker = new SelectElement(hourPickerDropDown);

## Ecxeption stacktraces

Result StackTrace:	
at OpenQA.Selenium.Support.UI.SelectElement..ctor(IWebElement element)
   at AutomationProj.AppTests.DoExecute() in .....AppTests.cs:line 353
   at ....TestMethod1() in 
Result Message:	
Test method EAMAutomation.EAMStructureTests.TestMethod1 threw exception: 
OpenQA.Selenium.Support.UI.UnexpectedTagNameException: Element should have been select but was ControlType.ComboBox

**Comment by sureshbabukothapalli** [comment]
I am also facing same issue. can you please some one help

**Comment by seenals** [comment]
Any suggestions? What is the right approach to select an item from dropdown using appium dotnet driver?. Please help.

**Comment by lanzelot1989** [comment]
Does someone have the preferred way to do this?

I also tried to use the Java code from [here](http://stackoverflow.com/q/35412630) but could not get it to work properly.

**Comment by siggerzz** [comment]
I'm using NUnit and Page Object pattern. I've been able to do it by doing the following.

[FindsBy(How = How.Id, Using = "dropdown")]
public IWebElement Dropdown { get; set; }

var dropdownSelect = new SelectElement(Dropdown);

dropdownSelect.SelectByValue("test");

**Comment by seenals** [comment]
I have not explored the Page Object Pattern. But do intend to adopt the pattern for a mature automation suite.

I’m using the below code snippet.

//Get the element by id.
IWebElement selectTypes = WinDriver.FindElementByAccessibilityId("MyComboBox");
Debug.WriteLine("selectTypes: " + selectTypes.GetType());//this prints that it is a WindowsElement
var selectTypeComboBox = new SelectElement(selectTypes);//Exception and test fails.

StackTrace and Exception
at OpenQA.Selenium.Support.UI.SelectElement..ctor(IWebElement element)……
……….TestMethod1() in ……
Result Message:
TestMethod1 threw exception:
OpenQA.Selenium.Support.UI.UnexpectedTagNameException: Element should have been select but was ControlType.ComboBox

It does say the control is of type ComboBox. But SelectElement expects a select and not a ComboBox.
That is the issue. Do we need to do any casting to resolve this?

Since the app under test is a Windows store app, the UI is done using XAML. Will this cause any difference?

Please suggest how to write tests  with ComboBox element.

**Comment by Manvibha** [comment]
I too facing same issue OpenQA.Selenium.Support.UI.UnexpectedTagNameException: Element should have been select but was ControlType.ComboBox" 

Could not find any other workaround.
note: sendkeys will not work when there are common letters in dropdown list items. ex: New, end etx..

**Comment by SanjeevKumarmn** [comment]
I use Winium for my testing and it provides combo box selection feature. WinApp seems to be not having such options and not much of selenium native class are working. My suggestion is to use Winium until WinAPP guys mature enough to be used.

**Comment by roopaturlapati** [comment]
@SanjeevKumarmn  can you please provide the code that your using for combobox selection !

**Comment by swathiJaya** [comment]
Hi, I am facing the same issue..any updates?

**Comment by PraveenNalla23** [comment]
Hi, Any update on this defect?

**Comment by seenals** [comment]
No. I couldn’t proceed further.

**Comment by artmdv** [comment]
Hi, any chance this will be ever solved or answered with a workaround? :(

**Comment by davidporter** [comment]
I am also having this issue, any update?

**Comment by kishorS18** [comment]
I tried this one in c#, hope it will help someone who land on this page seeking answer.
` WindowsElement dropDownSupplier = (WindowsElement)window.FindElementByClassName("ComboBox");
            dropDownSupplier.Click();
            dropDownSupplier.SendKeys("item in dropdown");`

**Comment by karthikmsctcs** [comment]
I have tried a similar implementation
WindowsElement dropDownSupplier = (WindowsElement)window.FindElementByClassName("ComboBox"); 
ReadOnlyCollection<AppiumWebElement> li = dropDownSupplier.FindElementByClassName("ListBoxItem"); 
dropDownSupplier.Click();
li[0].Click(); //This will select the first item in the Combo Box List

**Comment by akinsolb** [comment]
Please either refer to [this](https://github.com/appium/appium-dotnet-driver/issues/178#issuecomment-535795878) comment or check out the [WinAppDriver supported APIs](https://github.com/microsoft/WinAppDriver/tree/master/Tests) and tests for example usage, in particular the [Combo box test](https://github.com/microsoft/WinAppDriver/blob/master/Tests/UWPControls/ComboBox.cs)
