### ISSUE TITLE
Unable to start appium server in the updated version

### ISSUE THREAD

**Issue by kiran-meda** [appium/appium-dotnet-driver#182]
## Description

Unable to start appium server programatically using C#

## Environment

* .NET client build version or git revision if you use some shapshot:
* Appium server version or git revision if you use some shapshot: v1.0.2-beta.2 
* Desktop OS/version used to run Appium if necessary: Windows10
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: 7.1.1
* Real device or emulator/simulator: Real device

## Details

Unable to start appium server programatically after update to the latest. Appium.js is missing in the latest version. I have used main.js.

## Code To Reproduce Issue [ Good To Have ]
AppiumLocalService service = new AppiumServiceBuilder().WithIPAddress("127.0.0.1").WithLogFile(new FileInfo(@"c:\temp\log.txt")).UsingPort(4723).WithAppiumJS(new FileInfo(@"C:\Users\Myuser\AppData\Local\Programs\appium-desktop\resources\app\main.js")).UsingDriverExecutable(new FileInfo(@"C:\Program Files\nodejs\node.exe")).Build();
service.Start();

## Ecxeption stacktraces

'OpenQA.Selenium.Appium.Service.Exceptions.AppiumServerHasNotBeenStartedLocallyException' occurred in appium-dotnet-driver.dll but was not handled in user code
The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: "C:\Users\Myuser\AppData\Local\Programs\appium-desktop\resources\app\main.js" --port 4723 --address 127.0.0.1 --log c:\temp\log.txt. 
Time 120000 ms for the service starting has been expired!

## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by Parahet** [comment]
I have the same issue, I used space character in LogFile (e.g. new FileInfo("D:\temp directory\log1.txt")), when I changed log file location to path without space character (e.g. "D:\temp\log1.txt") AppiumLocalService starts correctly.

**Comment by manivannan184** [comment]
i also have same issue. Any updates?

**Comment by akinsolb** [comment]
Linked #192
