### ISSUE TITLE
update Selenium to v3.8

### ISSUE THREAD

**Issue by obstar** [appium/appium-dotnet-driver#183]
As in title could you upgrade package on nuget to current selenium version 3.5?

**Comment by lanzelot1989** [comment]
Latest version for the C# language bindings seems to be [3.7.0](https://www.nuget.org/packages/Selenium.WebDriver/3.7.0) now.

**Comment by lanzelot1989** [comment]
Latest would be 3.8.0 now

**Comment by siggerzz** [comment]
Is this likely to happen?

I'm sharing a codebase between my Appium Hybrid app Tests / Selenium Desktop Tests.

Whilst this is fine for Chrome/Edge, Firefox's Gecko Driver relies on Selenium 3.5.0 or above, which causes my Appium tests to fail.

**Comment by Astro03** [comment]
I honestly don’t have time right now.  Maybe over Xmas break if I get a chance and I’m not working? 

If you make a PR for it, we can take a look and approve.  

Ciao,
ASTRO

**Comment by TikhomirovSergey** [comment]
#200 Merged here
