### ISSUE TITLE
VS2017 enters break mode during test execution

### ISSUE THREAD

**Issue by smoeller-liveid** [appium/appium-dotnet-driver#193]
When running my tests in debug mode, VS2017 suddenly enters break mode, although I did not set any break points. And because it obviously didn't break in my code, it does not show any source code. I can continue, and it typically works, but sometimes this break mode comes right in the middle of an selection or similar, which then fails the whole test.

I'm experiencing this with Appium version v1.7.1 (installed via node.js 6.11.5) on Windows 10 (1709).
My application under test is a Windows WPF / C# application. The Appium.WebDriver is version 3.0.0.2, MSTest.TestAdapter is 1.2.0, Selenium.WebDriver is 3.6.0

It looks to me as if this happens always after the same time, not depending on the test itself. On my PC, it happens after approx. 1 minute, regardless of what test is running. Even if I defer some execution in one test (i.e. Thread.Sleep(20000), it still happens after 1 minute, so it looks to me as if it would be independent from the actual test code.
I asked colleagues to test, and the basically support my findings, but with different times (colleague A around 2:20min, colleague B around 3:50).

Any idea is highly appreciated

**Comment by rajfidel** [comment]
@smoeller-liveid were you able to figure this? if not can you send what capabilities you set? a sample test which shows the problem? a screenshot for what you mean by 'break mode' and the appium logs for the test execution?

**Comment by smoeller-liveid** [comment]
The capabilities are as follows:
`appCapabilities.SetCapability("deviceName", "WindowsPC");`
`appCapabilities.SetCapability("app", applicationPath);`
So I think there's nothing special. 
Unfortunately, I could not find time till to create a sample yet, but this is definitively on my list.
In regards to the logs, is there a way to write them to file (I currently just see them flushing through the Powershell window)?
