### ISSUE TITLE
WindowsElement and PageObject

### ISSUE THREAD

**Issue by nms-plavoie** [appium/appium-dotnet-driver#196]
I can't get things working for using WindowsElement and PageObject. 

`
WindowsDriver<WindowsElement> driver = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), appCapabilities);
PageFactory.InitElements(View, this, new AppiumPageObjectMemberDecorator(new TimeOutDuration(TimeSpan.FromSeconds(60))));

[FindsBy(How = How.ClassName, Using = "TextBox")]
private WindowsElement UserName { get; set; }
`

How I am supposed to get working Page Object for WindowsElement and which attribute to search by accessibility id?

**Comment by vikrampvr** [comment]
I found a work around for this issue as below for identifying a control using AccessibilityId in pageobjects.

[FindsBy(How = How.XPath, Using = "//*[@AutomationId='id']")]
internal IWebElement ChkBxElement { get; set; }

**Comment by OmiCron07** [comment]
Thank you, I used this workaround too.
