### ISSUE TITLE
appium-dot-net-driver vs WinAppDriver

### ISSUE THREAD

**Issue by cosminstirbu** [appium/appium-dotnet-driver#199]
Hi,

I'm trying to wrap my head around [appium-dot-net-driver](https://github.com/appium/appium-dotnet-driver) (which looks more like the .NET client of Appium) and [WinAppDriver](https://github.com/Microsoft/WinAppDriver).

Can I simply just install appium using npm and then reference [appium-dot-net-driver](https://github.com/appium/appium-dotnet-driver) in my C# tests? Will it be enough to write UWP, Android and iOS cross platform tests?

Thank you,
Cosmin

**Comment by imurchie** [comment]
Yes. `appium-dot-net-driver` is the C# client for Appium. It provides the commands for communicating with the server. Installing the server and then using the `appium-dot-net-driver` is all you need.

**Comment by cosminstirbu** [comment]
Thank you!
