### ISSUE TITLE
Release new version on NuGet

### ISSUE THREAD

**Issue by siggerzz** [appium/appium-dotnet-driver#202]
## Description

Currently the latest version on NuGet is 3.0.0.2, however a new PR has been approved to update Appium dependencies to their latest versions(https://github.com/appium/appium-dotnet-driver/pull/200).

Is it possible to get this up on NuGet?

Cheers!

**Comment by TikhomirovSergey** [comment]
@siggerzz Hello. 
Yes. There is the plan to publish the new version in 2018 (February or March).
There is  a lot of work for enhancement.  All attention attention was focused on java client. Also there is lack of active contributors. So any help is appreciated.

**Comment by chiptus** [comment]
@TikhomirovSergey How can I help?

**Comment by TikhomirovSergey** [comment]
The first beta version since Feb'17 has been released. Please be in touch. Any contributions are welcome
