### ISSUE TITLE
When will be release new version of .net driver which will  supports the  new XCUITest driver, Selenium(3.8.0) and Appium 1.7.2 for testing iOS testing.

### ISSUE THREAD

**Issue by sanjaykumar5115** [appium/appium-dotnet-driver#203]
## Description
When will be release new version of .net driver which will supports the  new XCUITest driver, Selenium(3.8.0) and Appium 1.7.2 for testing iOS testing. we are facing the lot of issue while testing the same.

## Environment

* .NET client build version or git revision if you use some shapshot:
* Appium server version or git revision if you use some shapshot:1.7.1
* Desktop OS/version used to run Appium if necessary:1.2.7
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: IOS (11.2.1) mac-10.13.1
* Real device or emulator/simulator:Iphone 6-IOS (11.2.1)

## Details

When will be release new version of .net driver which will supports the  new XCUITest driver, Selenium(3.8.0) and Appium 1.7.2 for testing iOS testing. we are facing the lot of issue while testing the same.

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.
You can git clone https://github.com/appium/sample-code or https://github.com/appium/sample-code/tree/master/sample-code/apps and reproduce an issue using C# and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted C# code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by .NET.

## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by TikhomirovSergey** [comment]
4.0.0.1-bata is available now. But the work is not finished yet.

**Comment by sanjaykumar5115** [comment]
thank you update.

Can you share the beta version path.

**Comment by TikhomirovSergey** [comment]
@sanjaykumar5115 
https://www.nuget.org/packages/Appium.WebDriver/4.0.0.1-beta

**Comment by sanjaykumar5115** [comment]
thanks lots
