### ISSUE TITLE
Intermittent: KeepAliveFailure when running android test

### ISSUE THREAD

**Issue by renaldorini** [appium/appium-dotnet-driver#206]
## Description

While running an Android test on a Windows machine with Appium 1.72 command line we are now seeing an issue where the test will cut off due to KeepAliveFailure when attempting to get a response from Appium. 

## Environment

* .NET client build version or git revision if you use some shapshot:

* Appium server version or git revision if you use some shapshot:
1.72
* Desktop OS/version used to run Appium if necessary:
Windows 10
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
Node.js: 8.9.3
Appium CLI
* Mobile platform/version under test:
Android
* Real device or emulator/simulator:
Emulator

## Code To Reproduce Issue [ Good To Have ]

FindElement(string locator)
{
return FindElementById(locator);
}

// Basically we have a function that does a couple things like click around the screen and eventually gets to a portion where it will attempt to click a button twice and will not survive that.
FindElement(button).Click();
Thread.Sleep(TimeSpan.FromSeconds(10));
FindElement(button).Click();

## Exception stacktraces

https://gist.github.com/renaldorini/24de85e6820e180bdff35097bf610090

## Link to Appium logs

https://gist.github.com/renaldorini/b497423ebe2a014973df5fc619610622

**Comment by renaldorini** [comment]
Let me know how I can better help this since it is a pretty big issue that we just started seeing after switching to new 1.72.

**Comment by renaldorini** [comment]
Is anyone else seeing this or in the wrong place?

**Comment by Astro03** [comment]
Are you using the C# drivers to do this? if so, then this is the right
channel.

**Comment by renaldorini** [comment]
Yes this is using C#. I edited the test to avoid the issue, but still seeing it.

**Comment by sergmal** [comment]
Same happening to me. 

Using Appium.WebDriver 3.0.0.2, Real IOS device

I noticed this error comes up when between actions when something happening on the page.

**Comment by renaldorini** [comment]
Looks like this might be an issue with Selenium https://github.com/SeleniumHQ/selenium/issues/5758

**Comment by manivannan184** [comment]
I am also facing same issue

03-May-18 14:16:39 PM : method name : Error : Choose Home screen - Exception: A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://127.0.0.1:4723/wd/hub/session/2bf75e03-28e4-4c48-beab-6e8d96dec998/elements. The status of the exception was KeepAliveFailure, and the message was: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server. - Stack Trace:    at OpenQA.Selenium.Appium.Service.AppiumCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElements(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementsById(String id)
   at OpenQA.Selenium.Appium.AppiumDriver`1.FindElementsById(String id)
   at method.IsElementAvailable(device mDevice, String idNameOrtextName) in C:\Work\Sync\CAT-Development\CAT\CAT\CatUsage\MbuxApp.cs:line 781

**Comment by akinsolb** [comment]
Please use the [latest release](https://www.nuget.org/packages/Appium.WebDriver/)
