### ISSUE TITLE
Does appium-dotnet-driver support waiting for an element visible? 

### ISSUE THREAD

**Issue by higarry** [appium/appium-dotnet-driver#207]
Recently, I am using Appium+WinAppDriver to do UI testing for my UWP applications, but I encountered an issue:
I am not able to know when does some control elements of my APP has showed up , I failed to find some functions like WebDiverWait which is used on WebDriver. So there are some functions like WinDriverWait ? Or do some one has a good way to do this to wait for some element become visible?
Thanks

ref: http://www.seleniumhq.org/docs/04_webdriver_advanced.jsp#explicit-waits

**Comment by agriardyan** [comment]
I believe it's described very clear in the documentation : <br>

- https://github.com/appium/appium-dotnet-driver/wiki/Page-objects  and

- https://github.com/appium/appium-dotnet-driver/wiki/Page-objects#if-time-of-the-waiting-for-elements-differs-from-general

**Comment by shaktim121** [comment]
Hi @agriardyan 

I guess the question was for Appium+WinAppDriver and the documentation provided doesn't speak about the issue anywhere.
Please suggest if any explicit wait method available for windows element in WinAppDriver like:

IWebDriverWait wait = new IWebDriverWait(driver, TimeSpanFromSeconds(30));
