### ISSUE TITLE
Couldn't swipe and setContext in C#

### ISSUE THREAD

**Issue by jackingest** [appium/appium-dotnet-driver#212]
## The problem

C# codes, doesn't have setContext method. Also using Swipe or TouchAction, always got "Method has not yet been implemented" error. What's the problem? How can I solve these problems?

## Environment

* Appium version 1.7.2
* Desktop OS/version used to run Appium: 1.4.1
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real device Samsung S6
* Chrome 52, chromedriver 2.2.0

## Details

1. Couldn't set and switch contexts in C#, didn't find any useful method. How can I do that?
2. Couldn't scroll screen, TouchAction/Swipe doesn't work, report "Method has not yet been implemented" error. Any solution?

**Comment by GrzegorzSidwa** [comment]
Hi @xbotest , 
could you please provide detailed logs? I'm using appium 1.7.2 on both Android and iOS and I'm using swipes/setting context exposed by appium-dotnet-driver. I will try to help, but please provide full appium logs from execution. 
Br,
Greg

**Comment by rwilliamshgem** [comment]
Hi, 

I'm currently trying to get scroll/swipe to work in my automation using TouchAction but I get the following error. 
" cannot convert from ‘OpenQA.Selenium.Remote.RemoteWebDriver’ to ‘OpenQA.Selenium.Appium.Interfaces.IPerformsTouchActions’"

I’ve tried changing my driver to be AndroidDriver with still having the same error. If I cast the RemoteWebDriver to a IPerformsTouchActions it returns null.

I’m using appium 1.8.1 on windows
and appium.webdriver 3.0.0.2 in visual studio

Is there any other way to implement a scroll/swipe in c# or how can i get TouchActions to work?

Thanks in advance

**Comment by GrzegorzSidwa** [comment]
@rwilliamshgem  it look like you're using TouchActions in wrong place. Please refer to http://appium.io/docs/en/writing-running-appium/touch-actions/ for more details. In case of any issues please share your source code.

**Comment by johnstimbertintersys** [comment]
Hello, the following extension methods are throwing not implemented exceptions. I am trying to perform them against mobile chrome. Any guidance would be greatly appreciated.

appium-dotnet-driver 3.0.0.2
selenium webdriver 3.12.1

`
using OpenQA.Selenium;
using OpenQA.Selenium.Appium;
using OpenQA.Selenium.Appium.Android;
using OpenQA.Selenium.Appium.MultiTouch;
using OpenQA.Selenium.Support.UI;

public static void ScrollToElement(this AndroidDriver<IWebElement> driver, By locator)
        {
            var element = driver.FindElement(locator);
            TouchAction action = new TouchAction(driver);
            action.Press(0, 0);
            action.MoveTo(element.Location.X, element.Location.Y);
            action.Perform();
        }

        public enum SwipeDirection
        {
            Up,
            Down,
            Left,
            Right
        }

        public static void SwipeInDirection(this AndroidDriver<IWebElement> driver, SwipeDirection direction)
        {
            var Width = Convert.ToInt32(driver.ExecuteScript("return window.innerWidth", null));
            var Height = Convert.ToInt32(driver.ExecuteScript("return window.innerHeight", null));
            var action = new TouchAction(driver);
            switch (direction)
            {
                case SwipeDirection.Up:
                    action.Press(Width / 2, Height / 2);
                    action.MoveTo(Width / 2, -100);
                    //driver.Swipe(Width / 2, 1, Width / 2, Height - 100, 2000);
                    break;
                case SwipeDirection.Down:
                    driver.Swipe(Width / 2, Height - 1, Width / 2, 1, 2000);
                    break;
                case SwipeDirection.Left:
                    driver.Swipe(Width - 1, Height / 2, 1, Height / 2, 2000);
                    break;
                case SwipeDirection.Right:
                    driver.Swipe(1, Height / 2, Width - 1, Height / 2, 2000);
                    break;
            }

            driver.PerformTouchAction(action);
        }`

**Comment by alangithubtrader** [comment]
same here...

**Comment by alangithubtrader** [comment]
This works for me

https://www.guru99.com/scroll-up-down-selenium-webdriver.html

**Comment by lanzelot1989** [comment]
@jackingest: Changing contexts works as follows:
``` 
Driver.Context = Driver.Contexts[0];
```

**Comment by lanzelot1989** [comment]
@jackingest: Swiping can be done with
```
Driver.Swipe(...);
```
and I think the TouchActions above would need to be chained together:
```
new TouchAction(driver).Press(0, 0).MoveTo(element.Location.X, element.Location.Y).Release().Perform();
```

**Comment by VitaliiDolotov** [comment]
I have manage to do swipe using below code (Appium 4.0.0.5-beta). Hope this help:
```
            TouchAction actions = new TouchAction((IPerformsTouchActions)driver);
            actions.Press(startX, startY).Wait(300).MoveTo(endX, endY).Release().Perform();
```
