### ISSUE TITLE
Updating to latest Selenium and Selenium support NuGetPackages raises Casting issue

### ISSUE THREAD

**Issue by Gocoollnath** [appium/appium-dotnet-driver#226]
## Description

Updating to latest Selenium(v3.12.0) and selenium support (v3.12.0) NuGetPackages raises Casting issue
It was working fine till earlier version v3.11.2

## Environment

Appium version 1.8.0
Desktop OS/version used to run Appium: Windows 10 Pro
Node.js version (unless using Appium.app|exe): 8.10.0
Mobile platform/version under test: Android API 25 ,v7.1.1
Real device or emulator/simulator: Real Device Samsung Tab
Appium CLI or Appium.app|exe: both
IDE: VisualStudio 2017 Enterprise and C# as coding language
Selenium Driver and Selenium support driver : v3.12.0 (Issue creating version)

Selenium Driver and Selenium support driver v3.11.2 worked fine without any casting issues

## Code To Reproduce Issue [ Good To Have ]

 public static AndroidElement UserName_Field()

        {
            AndroidElement UserName = driver.FindElement(By.Id("*:id/LoginView_txtUsername"));
            return UserName;
        }

## Ecxeption stacktraces
Test Name:	TestMethod1
Test FullName:	UnitTestProject1.UnitTest1.TestMethod1
Test Source:	C:\Users\gokulnath.kumar\source\repos\UnitTestProject1\UnitTestProject1\UnitTest1.cs : line 25
Test Outcome:	Failed
Test Duration:	0:00:53.4154213

Result StackTrace:	

at OpenQA.Selenium.Appium.AppiumDriver`1.FindElement(By by)
   at *_Mobile.Page_Objects.Login_Objects.UserName_Field() in C:\Users\gokulnath.kumar\source\repos\UnitTestProject1\UnitTestProject1\Page_Objects\Login_Objects.cs:line 21
   at *_Mobile.Log_in_module.Login_module.Login(String Uname, String Pwd) in C:\Users\gokulnath.kumar\source\repos\UnitTestProject1\UnitTestProject1\App_Modules\Login_module.cs:line 18
   at UnitTestProject1.UnitTest1.TestMethod1() in C:\Users\gokulnath.kumar\source\repos\UnitTestProject1\UnitTestProject1\UnitTest1.cs:line 27
Result Message:	
Test method UnitTestProject1.UnitTest1.TestMethod1 threw exception: 
System.InvalidCastException: Unable to cast object of type 'OpenQA.Selenium.Remote.RemoteWebElement' to type 'OpenQA.Selenium.Appium.Android.AndroidElement'.

## Link to Appium logs

https://gist.github.com/Gocoollnath/c6b4be5ababf838a0acf0adb72552a20

**Comment by pbmzbr** [comment]
For some reason, when you have the last version of the Selenium WebDriver and Selenium Support installed with Appium in your NuGet Packages your project will crash.

So, my suggestion is: uninstall the Selenium leaving only the Appium.
Or: downgrade the Selenium version (if you need to use Selenium anyway).

**Comment by Gocoollnath** [comment]
https://github.com/SeleniumHQ/selenium/issues/6045 . It's confirmed that how RemoteWebDriver works have been changed based on request in latest Selenium driver versions. Can the update be also made to Appium? @jlipps @TikhomirovSergey @mykola-mokhnach .Please, can you provide an update when this change be incorporated in Appium too?

**Comment by ronjonesjr** [comment]
#230 I've been running into these invalid casts for a while too!

**Comment by KthProg** [comment]
Okay wontfix... so what's the workaround?

**Comment by akinsolb** [comment]
Apologies all, [install the latest beta version](https://www.nuget.org/packages/Appium.WebDriver/4.0.0.4-beta)

**Comment by KthProg** [comment]
Thanks. Selenium changed some method signatures and switched DesiredCapabilities to some new interface. Is there documentation on how the beta version handles these changes?

**Comment by akinsolb** [comment]
Not yet but AppiumOptions.cs is the replacement class for now.

**Comment by KthProg** [comment]
Cool thank you very much!

**Comment by nikolay-advolodkin** [comment]
Did anyone figure out the new usage of the AppiumOptions will look? Does anyone have a code sample? Thanks

**Comment by akinsolb** [comment]
@nikolay-advolodkin I believe this is only available from the nuget package beta3?

**Comment by nikolay-advolodkin** [comment]
@akinsolb which pare is only Nuget?
I did: Install-Package Appium.WebDriver -Version 4.0.0.4-beta
https://screencast.com/t/RCw4nx8qMT

**Comment by akinsolb** [comment]
@nikolay-advolodkin That is correct. With this package version, you should not be receiving 'Unable to cast object of type'. If you are, can you upload a [gist](https://gist.github.com) of your stacktrace

**Comment by nikolay-advolodkin** [comment]
Here's the stacktrace @akinsolb  - https://gist.github.com/nikolay-advolodkin/f0cc583d44cfbd95078431c384d65354

**Comment by akinsolb** [comment]
@nikolay-advolodkin The latest and beta release supports up to Selenium v3.14. Your screenshot shows you have 3.14.1. Please raise a new issue using the issue template.

**Comment by nikolay-advolodkin** [comment]
> @nikolay-advolodkin The latest and beta release supports up to Selenium v3.14. Your screenshot shows you have 3.14.1. Please raise a new issue using the issue template.

You're right, that was the problem

**Comment by srinivas15j1988** [comment]
Hi,

In appiumoptions.additionalcapability how do u set the current working directory?
