### ISSUE TITLE
appium-dotnet-driver don't support .net core 2.0

### ISSUE THREAD

**Issue by ParisHuang** [appium/appium-dotnet-driver#227]
Description
1. create .net core project.
2. install Appium.Webdriver package by Nuget.
3. there are warning information: "Package 'Appium.WebDriver 3.0.0.2' was restored using '.NETFramework, Version=v4.6.1' instead of the project target framework '.NETCoreApp, Version=v2.0', This package may not be fully compatible with your project."

Problem: appium-dotnet-driver don't support .net core 2.0 project.

**Comment by nadvolod** [comment]
Having same issue. Any updates on this?

**The problem**
Appium doesn't work on .NET Core 2.0

**Environment**
Appium version (or git revision) that exhibits the issue: 3.0.0.2
Desktop OS/version used to run Appium: Windows 10 and Mac OS High Sierra
Real device or emulator/simulator: Real device
Details
I'm attempting to run a simple Appium test that works for me with .NET Framework, but doesn't work for me using .NET Core.

**Code To Reproduce Issue [ Good To Have ]**
Please supply your own Sauce user name and access key.

public void TestNativeAndroidApp(string testName)
        {
            var capabilities = new DesiredCapabilities();
            capabilities.SetCapability("platformName", "Android");
            capabilities.SetCapability("platformVersion", "7.1.1");
            //TODO first you must upload an app to Test Object so that you get your app key
            capabilities.SetCapability("testobject_api_key", "0D6C044F19D0442BA1E11C3FF087F6A6");
            capabilities.SetCapability("deviceName", "Google Pixel");
            capabilities.SetCapability("deviceOrientation", "portrait");
            capabilities.SetCapability("name", testName);
            var rdcUrl = "https://us1.appium.testobject.com/wd/hub";
            //TODO should be interchangeable to run on Windows/Mac
            var sauceUser = Environment.GetEnvironmentVariable("SAUCE_USERNAME", EnvironmentVariableTarget.User);
            var sauceKey = Environment.GetEnvironmentVariable("SAUCE_ACCESS_KEY", EnvironmentVariableTarget.User);
            var sauceUlr =
                $"https://{sauceUser}:{sauceKey}@ondemand.saucelabs.com:443/wd/hub";
            var driver = new AndroidDriver<IWebElement>(new Uri(rdcUrl), capabilities);
            driver.Quit();
        }

**Comment by LGFox** [comment]
I managed to run it on MacOS but I compiled it for .net core manually.
You can create new netcore project, move Appium folder and Resources.resx to the new project, fix path in Resource.resx and just a couple of small compilation issues.

As for me, I think this project pretty ready to be moved to .net core but I didn't run integration tests against my build.

**Comment by theAshenfire** [comment]
Hello,
going over the files i've noticed that .NET standard was added to 4.0.0.2 beta. any idea when this will be available via NuGet package?

**Comment by akinsolb** [comment]
As of date, the project is yet to fully support netCore v.*. In order to do this, the following needs to happen, a drop of support for SeleniumExtras APIs, such as PageFactory, WaitUntil, ExpectedConditons etc,  and/or an implementation of useful APIs to users, i.e PageFactory for using similar locators for multiple platform/drivers which does support netCore.
