### ISSUE TITLE
W3C capabilities are incorrect

### ISSUE THREAD

**Issue by dpgraham** [appium/appium-dotnet-driver#229]
## Description

* I just looked at the logs posted by a user of the client and it was creating sessions with these capabilities:

```json
{
  "desiredCapabilities": {
        "app": xxx,
        "deviceName": xxx,
        "fullReset": true,
        "newCommandTimeout": 1800,
        "platformName": "ios",
        "platformVersion": "11.3.1",
        "startIWDP": true,
        "udid": xxx,
        "updatedWDABundleId": "io.appium.WebDriverAgentRunner",
        "xcodeOrgId": xxx,
        "xcodeSigningId": "iPhone Developer"
    },
    "firstMatch": [{
        "platformName": "ios"
    }
}
```

The format should be like this (see https://github.com/jlipps/simple-wd-spec#processing-capabilities for reference):

```json
{
  "alwaysMatch": {
        "app": xxx,
        "deviceName": xxx,
        "fullReset": true,
        "newCommandTimeout": 1800,
        "platformName": "ios",
        "platformVersion": "11.3.1",
        "startIWDP": true,
        "udid": xxx,
        "updatedWDABundleId": "io.appium.WebDriverAgentRunner",
        "xcodeOrgId": xxx,
        "xcodeSigningId": "iPhone Developer"
    },
    "firstMatch": [{
        "platformName": "ios"
    }
}
```

`desiredCapabilities` should be `alwaysMatch`

We had the same issue in the Java client

(refer to https://github.com/appium/appium/issues/10668#issuecomment-389232455)

**Comment by justintoth** [comment]
Any update on this? We're completely blocked on running our Appium test cases until this is resolved...

**Comment by akinsolb** [comment]
@justintoth does upgrading your selenium.Webdriver dll/ package resolve your issue? the code pertaining to this issue is in that Webdriver.dll. If this issue exists in the latest version of Selemium.Webdriver then the issue should be raised in that repo and not this one.

**Comment by dpgraham** [comment]
@akinsolb It's an Appium issue.

According to @justintoth's logs, the desired capabilities are being sent in this format:

```
{
    "desiredCapabilities": {
        "device": "Android",
        "deviceName": "FA6CE0302473",
        "platformName": "Android",
        "platformVersion": "8.1",
        "appPackage": "com.rpr.mobile",
        "appActivity": "com.rpr.mobile.droid.SplashActivity",
        "automationName": "uiautomator2",
        "forceMjsonwp": "true",
        "newCommandTimeout": 120,
        "testobject_test_name": "CanLookupPropertyDetail"
    },
    "capabilities": {
        "firstMatch": [{
            "platformName": "Android"
        }]
    }
}
```

which is missing the `alwaysMatch` capability.

We had the same problem in the Java client, it was sending `capabilities.desiredCapabilities` instead of `capabilities.alwaysMatch`
