### ISSUE TITLE
GetClipboard

### ISSUE THREAD

**Issue by prirolim** [appium/appium-dotnet-driver#234]
## Description

I need to use `getClipboard` using Appium with C#. I looked at the appium [documentation](https://appium.readthedocs.io/en/latest/en/commands/device/clipboard/get-clipboard/) and it doesn't show the C# code. I didn't found the implementation in the source code. Are there any plans to add it?

Thanks!

## Environment

* Visual Studio 2017 Community
* Appium.WebDriver 3.0.0.2

**Comment by mykola-mokhnach** [comment]
Linked https://github.com/appium/appium-dotnet-driver/issues/252

**Comment by PraveenNalla23** [comment]
@akinsolb, can you please provide update on 4.0.1.0-beta release date.
