### ISSUE TITLE
Is Pagefactory going to be deprecated in near future?

### ISSUE THREAD

**Issue by Gocoollnath** [appium/appium-dotnet-driver#235]
appium/appium#10906

**Comment by jimevans** [comment]
`PageFactory` is deprecated in the main Selenium repository. It is still a going concern in the [DotNetSeleniumExtras repository](https://github.com/DotNetSeleniumTools/DotNetSeleniumExtras), though the repo is looking for a new owner.

**Comment by akinsolb** [comment]
PageFactory still exists and is only available for .NetFramework.
