### ISSUE TITLE
Add support for FindsByWindowsAutomationAttribute

### ISSUE THREAD

**Issue by cosminstirbu** [appium/appium-dotnet-driver#237]
## Description

We have a suite of tests that need to run on both iOS and UWP.

We're using the `AppiumPageObjectMemberDecorator` to decorate our elements, but unfortunately there's no attribute for Windows.

Currently the `AppiumPageObjectMemberDecorator` and `ByFactory` classes only support iOS and Android.

It would be useful to support Windows as well - maybe by introducing a `FindsByWindowsAutomationAttribute`.

Until this is done - is there maybe a workaround that we could use to decorate our elements for both iOS and UWP?

Thanks,
Cosmin

**Comment by cosminstirbu** [comment]
I've forked the repo and made the changes as a patch against 3.0.0.2 (since this is the version we're currently using)

You can find the changes here: https://github.com/cosminstirbu/appium-dotnet-driver/commit/5fbd7279b281efaddca0a3932037cdb40e404c01

If you're happy with them, I can make the same changes against `master` as well and open a PR.

Thanks,
Cosmin

**Comment by cosminstirbu** [comment]
After adding this feature, I've ran into this issue https://github.com/Microsoft/WinAppDriver/issues/454

Any help would be appreciated.

**Comment by akinsolb** [comment]
@cosminstirbu make a pull request

**Comment by cosminstirbu** [comment]
I'll do a rebase sometime by the end of this week and I'll create the pull request this weekend hopefully.

**Comment by akinsolb** [comment]
Closed by #276
