### ISSUE TITLE
[Question] FindsBy - iOS - uiaccessibilityidentification

### ISSUE THREAD

**Issue by dazinator** [appium/appium-dotnet-driver#241]
## Description

One of the locator strategies mentioned here: https://saucelabs.com/blog/advanced-locator-strategies
is accessbility_id.

> For iOS this is the accessibility identifier laid out by Apple [here](https://developer.apple.com/documentation/uikit/uiaccessibilityidentification).
For Android the accessibility id maps to the content-description for the element, as described here.

From reading the [wiki](https://github.com/appium/appium-dotnet-driver/wiki/Page-objects) I couldn't establish which FindsBy attribute to use to locate elements with this strategy - is there one?

Thanks

**Comment by akinsolb** [comment]
As of version 4 and below, you will have to use the 'FindsByIOSUIAutomation' attribute, which contains an 'Accessibility' property.
