### ISSUE TITLE
publish new version Nuget

### ISSUE THREAD

**Issue by flyofsky** [appium/appium-dotnet-driver#242]
## Description

The current version of NuGet is 3.0.0.2 and  4.0.0.1-beta.
Recently, Tizen-related PR was merged.
When can we get a new version of NuGet with Tizen?
Do you have a plan to publish a new version NuGet?

**Comment by akinsolb** [comment]
While it would be great to see a release of a new version of this client. There should be a few refactoring tasks completed before publishing a nuget. A lot of the unit tests fail due to changes on the upstream selenium project and evolutionary changes.

**Comment by akinsolb** [comment]
Forgotten to add details regarding Tizen on Nuget, but I will update therelease notes.
