### ISSUE TITLE
Add linter verification to CI 

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium-dotnet-driver#248]
It would be nice to perform basic source verification using tools like FxCop on our CI server for each incoming PR.

**Comment by akinsolb** [comment]
@mykola-mokhnach If we add a tool such as FxCop, the minimum recommend rules won't fail a build. Instead it will append a vast amount of warning messages to the build logs. 
I think we should do 1 of the following: 

1. Add a linter applying minimum recommended rule sets, allowing the default build action of throwing warning messages (in build logs) for the current violated rules.
2. Add a linter applying minimum recommended rule sets, suppressing build warning messages for all current violated rules.
3. Add a linter, applying minimum recommended rule sets, set the build action to fail for all active rule sets. This will cause the build to fail until all violations are addressed. 

I'm happy to add this to both src and test projects, but there might be some violation exceptions for the two projects and some classes, like having an underscore within an identifier, (for example, `AndroidKeycode.KeycodeButton_Mode`)

I'm more than happy to go through option 3 or other alternatives.

**Comment by mykola-mokhnach** [comment]
I would also prefer to have a minimum set of rules so then we can extend it step by step as soon as current violations are getting addressed
