### ISSUE TITLE
Add support for IMAGE locator type

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium-dotnet-driver#250]
https://github.com/appium/java-client/pull/990

**Comment by MummanaSubramanya** [comment]
any idea when this can be implemented? Im eagerly waiting.

**Comment by akinsolb** [comment]
I plan to do this on the weekend. You're more than welcome to contribute if you think you have the capacity to do it before then

**Comment by MummanaSubramanya** [comment]
@akinsolb : Can i expect this to be in next release?

**Comment by MummanaSubramanya** [comment]
@akinsolb : any update on this? can we expect a new version of c# bindings soon?
