### ISSUE TITLE
DesiredCapabilities has been deprecated in a favor of browser-specific options classes appium

### ISSUE THREAD

**Issue by burakavcioglu** [appium/appium-dotnet-driver#259]
Hi,

I am getting the error below in the code.

**Error Image:** https://i.hizliresim.com/3znz4O.png

        **[TestInitialize]
        public void SamsungGalaxyA8()
        {
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;
            var capabilities = new DesiredCapabilities();
            capabilities.SetCapability("app", ZiraatApp);
            capabilities.SetCapability(MobileCapabilityType.Udid, A8ID);
            capabilities.SetCapability("Platform", "Windows");
            capabilities.SetCapability("deviceName", A8);
            capabilities.SetCapability(CapabilityType.Platform, "Android");
            capabilities.SetCapability(CapabilityType.PlatformName, "Android");
            capabilities.SetCapability("platformVersion", A8Version);
            capabilities.SetCapability("noReset", true);
            capabilities.SetCapability("fullReset", "False");
            capabilities.SetCapability("useNewWDA", true);
            capabilities.SetCapability("showXcodeLog", true);
            capabilities.SetCapability("autoGrantPermissions", true);
            var Mobile = new AndroidDriver<AppiumWebElement>(new Uri("http://127.0.0.1:4723/wd/hub"), capabilities);
            Mobile.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(180);

            Console.WriteLine("Device Connected");
        }**

**Comment by akinsolb** [comment]
FYI @burakavcioglu your link returns a '403 Forbidden' page.
linked #258
