### ISSUE TITLE
Appium Server log in VS2017 Console Window

### ISSUE THREAD

**Issue by cosminstirbu** [appium/appium-dotnet-driver#261]
Hello,

Is there a way to see the server log in the VS2017 Console Window when started with  AppiumServiceBuilder.Build()?

When running it on VS 4 Mac, it logs everything in the Application Output window. However, on Windows, I can't see the logs anywhere.

I know the Java client logs the server logs in the console output as well, when running the tests with Intellij. I'm looking for something similar.

Thank you,
Cosmin

**Comment by akinsolb** [comment]
No, it would be best to use the Appium API to retrieve logs
