### ISSUE TITLE
FindElementBy<X> tries to use CSS selector on 4.0.0.2-beta

### ISSUE THREAD

**Issue by lanzelot1989** [appium/appium-dotnet-driver#265]
## Description

When starting Appium and trying to use 
* FindElementByClassName 
* FindElementByName
* FindElementById
* FindElementByTagName

the commands get translated to a CSS selector which does not work.

## Environment

* Appium server version or git revision if you use some shapshot: 1.9.1
* Desktop OS/version used to run Appium if necessary: Win 10
* Node.js version: 10.10.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator, API 26 (8.0)

## Details
Used package versions:
```
Appium.WebDriver: 4.0.0.2-beta
Castle.Core: 4.3.1
Newtonsoft.Json: 11.0.2
Selenium.WebDriver: 3.14.0
Selenium.Support: 3.14.0
```

## Code To Reproduce Issue
```
var driver = new AndroidDriver<IWebElement>(new Uri("http://localhost:4444/wd/hub"), options, TimeSpan.FromSeconds(60));
var element = driver.FindElementByClassName("android.widget.Button");
```

## Exception stacktraces
```
'driver.FindElementByClassName("android.widget.Button")' threw an exception of type 'OpenQA.Selenium.InvalidSelectorException'
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233088
    HelpLink: null
    InnerException: null
    Message: "Locator Strategy 'css selector' is not supported for this session"
    Source: "WebDriver"
    StackTrace: "   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)\r\n   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)\r\n   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)\r\n   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)\r\n   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByClassName(String className)\r\n   at OpenQA.Selenium.Appium.AppiumDriver`1.FindElementByClassName(String className)"
    TargetSite: {Void UnpackAndThrowOnError(OpenQA.Selenium.Remote.Response)}
```

## Link to Appium logs

```
[debug] [W3C] Calling AppiumDriver.findElement() with args: ["css selector",".android\\.widget\\.Button","456ec581-2527-4968-af70-3aa639e0d8f5"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [W3C] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session
[debug] [W3C]     at AndroidUiautomator2Driver.validateLocatorStrategy (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:349:13)
[debug] [W3C]     at AndroidUiautomator2Driver.callee$0$0$ (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\commands\find.js:26:8)
[debug] [W3C]     at tryCatch (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[debug] [W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[debug] [W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[debug] [W3C]     at invoke (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[debug] [W3C]     at enqueueResult (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
[debug] [W3C]     at new Promise (<anonymous>)
[debug] [W3C]     at new F (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
[debug] [W3C]     at AsyncIterator.enqueue (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
[debug] [W3C]     at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[debug] [W3C]     at Object.runtime.async (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
[debug] [W3C]     at AndroidUiautomator2Driver.callee$0$0 [as findElOrElsWithProcessing] (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\build\lib\basedriver\commands\find.js:47:30)
[debug] [W3C]     at AndroidUiautomator2Driver.callee$0$0$ (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\commands\find.js:46:21)
[debug] [W3C]     at tryCatch (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[debug] [W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[debug] [W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[debug] [W3C]     at invoke (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[debug] [W3C]     at enqueueResult (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
[debug] [W3C]     at new Promise (<anonymous>)
[debug] [W3C]     at new F (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
[debug] [W3C]     at AsyncIterator.enqueue (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
[debug] [W3C]     at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[debug] [W3C]     at Object.runtime.async (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
[debug] [W3C]     at AndroidUiautomator2Driver.callee$0$0 [as findElement] (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\build\lib\basedriver\commands\find.js:88:30)
[debug] [W3C]     at C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:296:26
[debug] [W3C]     at tryCatcher (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\util.js:26:23)
[debug] [W3C]     at Promise._settlePromiseFromHandler (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:510:31)
[debug] [W3C]     at Promise._settlePromiseAt (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:584:18)
[debug] [W3C]     at Promise._settlePromiseAtPostResolution (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:248:10)
[debug] [W3C]     at Async._drainQueue (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:128:12)
[debug] [W3C]     at Async._drainQueues (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:133:10)
[debug] [W3C]     at Immediate.Async.drainQueues (C:\Users\myUser\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:15:14)
[debug] [W3C]     at runCallback (timers.js:694:18)
[debug] [W3C]     at tryOnImmediate (timers.js:665:5)
[debug] [W3C]     at processImmediate (timers.js:647:5)
[HTTP] <-- POST /wd/hub/session/456ec581-2527-4968-af70-3aa639e0d8f5/element 400 44 ms - 5676
[HTTP]
```

**Comment by MummanaSubramanya** [comment]
@mykola-mokhnach : any update about this issue ?

Even Im facing same issue

failure logs:
`[debug] [W3C] Calling AppiumDriver.findElement() with args: ["css selector","#permission_allow_button","d76fc3da-df27-446a-926a-5cb7fad62789"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [W3C] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session
[debug] [W3C]     at AndroidUiautomator2Driver.validateLocatorStrategy (C:\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driv`

I tried with both ID :  "com.android.packageinstaller:id/permission_allow_button"
and "permission_allow_button"

both failed because of above error.

**Comment by MummanaSubramanya** [comment]
@akinsolb: any update about this issue?

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/10874#issuecomment-427578539
I read selenium codebase a bit before.
Below probably can be a workaround.

```
FindElement("id", "some ids")
FindElement("name", "some names")
FindElement("class name", "some class names")
```

Appium client should override them `FindElementBy*`

**Comment by KazuCocoa** [comment]
You can try https://github.com/appium/appium-dotnet-driver/pull/268

**Comment by MummanaSubramanya** [comment]
@akinsolb  @KazuCocoa  test still fails after updating to 4.0.0.4-beta. it still check for css selector after switching to native context.

Setup: android O, real device : Samausng galaxy 8, appium version 1.9.1, appium client: 4.0.0.4-beta

Below are my logs:

`[HTTP] {"name":"NATIVE_APP"} [debug] [W3C] Calling AppiumDriver.setContext() with args: ["NATIVE_APP","fee6cd95-0501-4416-9953-b444ee531624"] [debug] [AndroidDriver] Getting a list of available webviews [debug] [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s ce0718276bf16a2901 shell cat /proc/net/unix' [debug] [AndroidDriver] WEBVIEW_30478 mapped to pid 30478 [debug] [AndroidDriver] Getting process name for webview [debug] [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s ce0718276bf16a2901 shell ps' [debug] [AndroidDriver] Parsed pid: '30478' pkg: 'com.essent.flix' from [debug] [AndroidDriver] USER PID PPID VSZ RSS WCHAN ADDR S NAME [debug] [AndroidDriver] u0_a207 30478 3401 3717200 453392 0 0 R com.essent.flix [debug] [AndroidDriver] Returning process name: 'com.essent.flix' [debug] [AndroidDriver] Found webviews: ["WEBVIEW_chrome","WEBVIEW_com.essent.flix"] [debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_chrome","WEBVIEW_com.essent.flix"] [debug] [W3C] Responding to client with driver.setContext() result: null [HTTP] <-- POST /wd/hub/session/fee6cd95-0501-4416-9953-b444ee531624/context 200 394 ms - 14 [HTTP] [HTTP] --> POST /wd/hub/session/fee6cd95-0501-4416-9953-b444ee531624/element [HTTP] {"using":"css selector","value":"#com\\.android\\.packageinstaller\\:id\\/permission_allow_button"} [debug] [W3C] Calling AppiumDriver.findElement() with args: ["css selector","#com\\.android\\.packageinstaller\\:id\\/permission_allow_button","fee6cd95-0501-4416-9953-b444ee531624"] [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator [debug] [W3C] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session [debug] [W3C] at AndroidUiautomator2Driver.validateLocatorStrategy (C:\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:349:13) [debug] [W3C] at AndroidUiautomator2Driver.callee$0$0$ (C:\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\commands\find.js:26:8) [debug] [W3C] at tryCatch (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40) [debug] [W3C] at GeneratorFunctionPrototype.invoke [as _invoke] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22) [debug] [W3C] at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21) [debug] [W3C] at invoke (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37) [debug] [W3C] at enqueueResult (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17) [debug] [W3C] at new Promise (<anonymous>) [debug] [W3C] at new F (C:\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36) [debug] [W3C] at AsyncIterator.enqueue (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12) [debug] [W3C] at AsyncIterator.prototype.(anonymous function) [as next] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21) [debug] [W3C] at Object.runtime.async (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12) [debug] [W3C] at AndroidUiautomator2Driver.callee$0$0 [as findElOrElsWithProcessing] (C:\node_modules\appium\node_modules\appium-base-driver\build\lib\basedriver\commands\find.js:47:30) [debug] [W3C] at AndroidUiautomator2Driver.callee$0$0$ (C:\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\commands\find.js:46:21) [debug] [W3C] at tryCatch (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40) [debug] [W3C] at GeneratorFunctionPrototype.invoke [as _invoke] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22) [debug] [W3C] at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21) [debug] [W3C] at invoke (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37) [debug] [W3C] at enqueueResult (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17) [debug] [W3C] at new Promise (<anonymous>) [debug] [W3C] at new F (C:\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36) [debug] [W3C] at AsyncIterator.enqueue (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12) [debug] [W3C] at AsyncIterator.prototype.(anonymous function) [as next] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21) [debug] [W3C] at Object.runtime.async (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12) [debug] [W3C] at AndroidUiautomator2Driver.callee$0$0 [as findElement] (C:\node_modules\appium\node_modules\appium-base-driver\build\lib\basedriver\commands\find.js:88:30) [debug] [W3C] at C:\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:296:26 [debug] [W3C] at tryCatcher (C:\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\util.js:26:23) [debug] [W3C] at Promise._settlePromiseFromHandler (C:\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:510:31) [debug] [W3C] at Promise._settlePromiseAt (C:\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:584:18) [debug] [W3C] at Promise._settlePromiseAtPostResolution (C:\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:248:10) [debug] [W3C] at Async._drainQueue (C:\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:128:12) [debug] [W3C] at Async._drainQueues (C:\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:133:10) [debug] [W3C] at Immediate.Async.drainQueues [as _onImmediate] (C:\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:15:14) [debug] [W3C] at runCallback (timers.js:794:20) [debug] [W3C] at tryOnImmediate (timers.js:752:5) [debug] [W3C] at processImmediate [as _immediateCallback] (timers.js:729:5) [HTTP] <-- POST /wd/hub/session/fee6cd95-0501-4416-9953-b444ee531624/element 400 66 ms - 4602 [HTTP] [HTTP] --> GET /wd/hub/session/fee6cd95-0501-4416-9953-b444ee531624/screenshot [HTTP] {}`

**Comment by MummanaSubramanya** [comment]
@akinsolb : Yep Next time I will create gist. I'm trying to find element 
"com.android.packageinstaller:id/permission_allow_button" using By.ID

**Comment by akinsolb** [comment]
@MummanaSubramanya OK. Please provide gists of your code and stracktrace. Replace any sensitive parameters with 'x' if necessary. If the bug still exists I'll reopen this issue.

**Comment by cosminstirbu** [comment]
Hello,

This still reproduces if you use the Page Object pattern.

```
[FindsByIOSUIAutomation(ID = "AddNewUserButton")]
private IMobileElement<AppiumWebElement> _addNewUserButton;
```

I think the issue is that the `AppiumDriver` methods marked as `new` are not invoked, instead, the `RemoteWebDriver` are. At least this is what I was able to tell from by debugging.

**Comment by cosminstirbu** [comment]
I've ended up "overriding" the `IFindsById` methods in `AppiumDriver` as it can be seen here:

https://github.com/cosminstirbu/appium-dotnet-driver/commit/92d3a00fd7b5e4e4e7f76222569725076318fd32

I can open a PR with this if you guys think it looks good.

**Comment by cosminstirbu** [comment]
Done, please see https://github.com/appium/appium-dotnet-driver/pull/302
