### ISSUE TITLE
Select method doesn't work 

### ISSUE THREAD

**Issue by MummanaSubramanya** [appium/appium-dotnet-driver#267]
## Description
Unable to select dropdown for value in Hybrid app

## Environment

* .NET client build version or git revision if you use some shapshot:4.0.0.3(beta)
* Appium server version or git revision if you use some shapshot:1.9.1
* Desktop OS/version used to run Appium if necessary:
* Mobile platform/version under test: 8.0
* Real device or emulator/simulator: Samsung s8
* App type: Hybrid
* Chrome version: 69
* Automation Name: Appium
* Selenium: 3.14

## Code To Reproduce Issue [ Good To Have ]

'var selectElement = new SelectElement(AppElement);
selectElement.SelectByText(value);'

## Ecxeption stacktraces

`[HTTP] {"using":"xpath","value":"//div[normalize-space(.)='Country']/following-sibling::select"}
[W3C] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Matched '/wd/hub/session/077d2dbd-898a-473d-99a6-ce61567b2d0b/element' to command name 'findElement'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/077d2dbd-898a-473d-99a6-ce61567b2d0b/element] to [POST http://127.0.0.1:8000/wd/hub/session/fcbdb15a19d9069fec77b08464288532/element] with body: {"using":"xpath","value":"//div[normalize-space(.)='Country']/following-sibling::select"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"fcbdb15a19d9069fec77b08464288532","status":0,"value":{"ELEMENT":"0.7739416607289735-8"}}
[JSONWP Proxy] Replacing sessionId fcbdb15a19d9069fec77b08464288532 with 077d2dbd-898a-473d-99a6-ce61567b2d0b
[HTTP] <-- POST /wd/hub/session/077d2dbd-898a-473d-99a6-ce61567b2d0b/element 200 137 ms - 106
[HTTP]
[HTTP] --> GET /wd/hub/session/077d2dbd-898a-473d-99a6-ce61567b2d0b/element/0.7739416607289735-8/name
[HTTP] {}
[W3C] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Matched '/wd/hub/session/077d2dbd-898a-473d-99a6-ce61567b2d0b/element/0.7739416607289735-8/name' to command name 'getName'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/077d2dbd-898a-473d-99a6-ce61567b2d0b/element/0.7739416607289735-8/name] to [GET http://127.0.0.1:8000/wd/hub/session/fcbdb15a19d9069fec77b08464288532/element/0.7739416607289735-8/name] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"fcbdb15a19d9069fec77b08464288532\",\"status\":0,\"value\":\"select\"}"
[JSONWP Proxy] Replacing sessionId fcbdb15a19d9069fec77b08464288532 with 077d2dbd-898a-473d-99a6-ce61567b2d0b
[HTTP] <-- GET /wd/hub/session/077d2dbd-898a-473d-99a6-ce61567b2d0b/element/0.7739416607289735-8/name 200 51 ms - 80
[HTTP]
[HTTP] --> GET /wd/hub/session/077d2dbd-898a-473d-99a6-ce61567b2d0b/element/0.7739416607289735-8/name
[HTTP] {}
[W3C] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Matched '/wd/hub/session/077d2dbd-898a-473d-99a6-ce61567b2d0b/element/0.7739416607289735-8/name' to command name 'getName'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/077d2dbd-898a-473d-99a6-ce61567b2d0b/element/0.7739416607289735-8/name] to [GET http://127.0.0.1:8000/wd/hub/session/fcbdb15a19d9069fec77b08464288532/element/0.7739416607289735-8/name] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"fcbdb15a19d9069fec77b08464288532\",\"status\":0,\"value\":\"select\"}"
[JSONWP Proxy] Replacing sessionId fcbdb15a19d9069fec77b08464288532 with 077d2dbd-898a-473d-99a6-ce61567b2d0b
[HTTP] <-- GET /wd/hub/session/077d2dbd-898a-473d-99a6-ce61567b2d0b/element/0.7739416607289735-8/name 200 47 ms - 80
[HTTP]
[HTTP] --> POST /wd/hub/session/077d2dbd-898a-473d-99a6-ce61567b2d0b/execute/sync
[HTTP] {"script":"return (function(){return function(){var d=this;function f(a){return\"string\"==typeof a};function h(a,b){this.code=a;this.a=l[a]||m;this.message=b||\"\";a=this.a.replace(/((?:^|\\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\\s\\xa0]+/g,\"\")});b=a.length-5;if(0>b||a.indexOf(\"Error\",b)!=b)a+=\"Error\";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||\"\"}\n(function(){var a=Error;function b(){}b.prototype=a.prototype;h.b=a.prototype;h.prototype=new b;h.prototype.constructor=h;h.a=function(b,c,g){for(var e=Array(arguments.length-2),k=2;k<arguments.length;k++)e[k-2]=arguments[k];return a.prototype[c].apply(b,e)}})();var m=\"unknown error\",l={15:\"element not selectable\",11:\"element not visible\"};l[31]=m;l[30]=m;l[24]=\"invalid cookie domain\";l[29]=\"invalid element coordinates\";l[12]=\"invalid element state\";l[32]=\"invalid selector\";l[51]=\"invalid selector\";\nl[52]=\"invalid selector\";l[17]=\"javascript error\";l[405]=\"unsuppo
[W3C] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Matched '/wd/hub/session/077d2dbd-898a-473d-99a6-ce61567b2d0b/execute/sync' to command name 'execute'
[Protocol Converter] Rewrote the original URL '/wd/hub/session/077d2dbd-898a-473d-99a6-ce61567b2d0b/execute/sync' to '/wd/hub/session/077d2dbd-898a-473d-99a6-ce61567b2d0b/execute' for MJSONWP protocol
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/077d2dbd-898a-473d-99a6-ce61567b2d0b/execute] to [POST http://127.0.0.1:8000/wd/hub/session/fcbdb15a19d9069fec77b08464288532/execute] with body: {"script":"return (function(){return function(){var d=this;function f(a){return\"string\"==typeof a};function h(a,b){this.code=a;this.a=l[a]||m;this.message=b||\"\";a=this.a.replace(/((?:^|\\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\\s\\xa0]+/g,\"\")});b=a.length-5;if(0>b||a.indexOf(\"Error\",b)!=b)a+=\"Error\";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||\"\"}\n(function(){var a=Error;function b(){}b.prototype=a.prototype;h.b=a.prototype;h.prototype=new b;h.prototype.constructor=h;h.a=function(b,c,g){for(var e=Array(arguments.length-2),k=2;k<arguments.length;k++)e[k-2]=arguments[k];return a.prototype[c].apply(b,e)}})();var m=\"unknown error\",l={15:\"element not selectable\",11:\"element not visible\"};l[31]=m;l[30]=m;l[24]=\"invalid cookie domain\";l[29]=\"invalid element coordinates\";l[12]=\"invalid element state\";l[32]=\"invalid selector\";l[51]=\"invalid selector\";\nl[52]=\"invalid selector\";l[17]=\"javascript error\";l[405]=\"unsupported operation\";l[34...
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"fcbdb15a19d9069fec77b08464288532","status":13,"value":{"message":"unknown error: a.getAttributeNode is not a function\n  (Session info: chrome=69.0.3497.100)\n  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.17134 x86_64)"}}
[debug] [W3C] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: The request to /wd/hub/session/077d2dbd-898a-473d-99a6-ce61567b2d0b/execute has failed
[debug] [W3C]     at JWProxy.proxy$ (C:\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:182:13)
[debug] [W3C]     at tryCatch (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[debug] [W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[debug] [W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[debug] [W3C]     at GeneratorFunctionPrototype.invoke (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[debug] [W3C]     at <anonymous>
[debug] [MJSONWP] Matched JSONWP error code 13 to UnknownError
[HTTP] <-- POST /wd/hub/session/077d2dbd-898a-473d-99a6-ce61567b2d0b/execute/sync 500 195 ms - 1620
[HTTP]
[HTTP] --> GET /wd/hub/session/077d2dbd-898a-473d-99a6-ce61567b2d0b/screenshot
[HTTP] {}`

**Comment by akinsolb** [comment]
@MummanaSubramanya Please try [v4.0.0.0.4-beta](https://www.nuget.org/packages/Appium.WebDriver/4.0.0.4-beta)

**Comment by MummanaSubramanya** [comment]
@akinsolb : Awesome. Was eagerly waiting for this fix. Thanks much!!

**Comment by MummanaSubramanya** [comment]
@akinsolb @KazuCocoa test still fails after updating to 4.0.0.4-beta.
Setup: android O, real device : Samausng galaxy 8, appium version 1.9.1, appium client: 4.0.0.4-beta

Below are my logs:

`[HTTP] {"name":"NATIVE_APP"}
[debug] [W3C] Calling AppiumDriver.setContext() with args: ["NATIVE_APP","fee6cd95-0501-4416-9953-b444ee531624"]
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s ce0718276bf16a2901 shell cat /proc/net/unix'
[debug] [AndroidDriver] WEBVIEW_30478 mapped to pid 30478
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s ce0718276bf16a2901 shell ps'
[debug] [AndroidDriver] Parsed pid: '30478' pkg: 'com.essent.flix' from
[debug] [AndroidDriver]     USER           PID  PPID     VSZ    RSS WCHAN            ADDR S NAME
[debug] [AndroidDriver]     u0_a207      30478  3401 3717200 453392 0                   0 R com.essent.flix
[debug] [AndroidDriver] Returning process name: 'com.essent.flix'
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_chrome","WEBVIEW_com.essent.flix"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_chrome","WEBVIEW_com.essent.flix"]
[debug] [W3C] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/fee6cd95-0501-4416-9953-b444ee531624/context 200 394 ms - 14
[HTTP]
[HTTP] --> POST /wd/hub/session/fee6cd95-0501-4416-9953-b444ee531624/element
[HTTP] {"using":"css selector","value":"#com\\.android\\.packageinstaller\\:id\\/permission_allow_button"}
[debug] [W3C] Calling AppiumDriver.findElement() with args: ["css selector","#com\\.android\\.packageinstaller\\:id\\/permission_allow_button","fee6cd95-0501-4416-9953-b444ee531624"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [W3C] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session
[debug] [W3C]     at AndroidUiautomator2Driver.validateLocatorStrategy (C:\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:349:13)
[debug] [W3C]     at AndroidUiautomator2Driver.callee$0$0$ (C:\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\commands\find.js:26:8)
[debug] [W3C]     at tryCatch (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[debug] [W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[debug] [W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[debug] [W3C]     at invoke (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[debug] [W3C]     at enqueueResult (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
[debug] [W3C]     at new Promise (<anonymous>)
[debug] [W3C]     at new F (C:\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
[debug] [W3C]     at AsyncIterator.enqueue (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
[debug] [W3C]     at AsyncIterator.prototype.(anonymous function) [as next] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[debug] [W3C]     at Object.runtime.async (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
[debug] [W3C]     at AndroidUiautomator2Driver.callee$0$0 [as findElOrElsWithProcessing] (C:\node_modules\appium\node_modules\appium-base-driver\build\lib\basedriver\commands\find.js:47:30)
[debug] [W3C]     at AndroidUiautomator2Driver.callee$0$0$ (C:\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\commands\find.js:46:21)
[debug] [W3C]     at tryCatch (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[debug] [W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[debug] [W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[debug] [W3C]     at invoke (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[debug] [W3C]     at enqueueResult (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
[debug] [W3C]     at new Promise (<anonymous>)
[debug] [W3C]     at new F (C:\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
[debug] [W3C]     at AsyncIterator.enqueue (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
[debug] [W3C]     at AsyncIterator.prototype.(anonymous function) [as next] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[debug] [W3C]     at Object.runtime.async (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
[debug] [W3C]     at AndroidUiautomator2Driver.callee$0$0 [as findElement] (C:\node_modules\appium\node_modules\appium-base-driver\build\lib\basedriver\commands\find.js:88:30)
[debug] [W3C]     at C:\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:296:26
[debug] [W3C]     at tryCatcher (C:\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\util.js:26:23)
[debug] [W3C]     at Promise._settlePromiseFromHandler (C:\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:510:31)
[debug] [W3C]     at Promise._settlePromiseAt (C:\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:584:18)
[debug] [W3C]     at Promise._settlePromiseAtPostResolution (C:\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:248:10)
[debug] [W3C]     at Async._drainQueue (C:\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:128:12)
[debug] [W3C]     at Async._drainQueues (C:\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:133:10)
[debug] [W3C]     at Immediate.Async.drainQueues [as _onImmediate] (C:\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:15:14)
[debug] [W3C]     at runCallback (timers.js:794:20)
[debug] [W3C]     at tryOnImmediate (timers.js:752:5)
[debug] [W3C]     at processImmediate [as _immediateCallback] (timers.js:729:5)
[HTTP] <-- POST /wd/hub/session/fee6cd95-0501-4416-9953-b444ee531624/element 400 66 ms - 4602
[HTTP]
[HTTP] --> GET /wd/hub/session/fee6cd95-0501-4416-9953-b444ee531624/screenshot
[HTTP] {}`

**Comment by MummanaSubramanya** [comment]
@akinsolb: Thanks I confirm this Issue fixed but there is another error which is still not fixed. 
https://github.com/appium/appium-dotnet-driver/issues/265
