### ISSUE TITLE
Member to perform a swipe

### ISSUE THREAD

**Issue by ytonthat** [appium/appium-dotnet-driver#27]
The driver should expose a member to allow a client to perform swipes

**Comment by imsardine** [comment]
@ytonthat To open the navigation drawer, what coordinates did you pass to the `Swipe` method? `Press(0, 100)` doesn't work for me, and `Press(-1, 100)` results in an error message "An unknown server-side error occurred while processing the command."

**Comment by ytonthat** [comment]
I use x = 1 as a starting point for opening drawers

**Comment by imsardine** [comment]
@ytonthat thanks for the information. Interestingly, I found x-coordinate of the starting point could be any small numbers other than zero.
