### ISSUE TITLE
Test Freezes on Samsung S8

### ISSUE THREAD

**Issue by MummanaSubramanya** [appium/appium-dotnet-driver#273]
## Description
Test Freezes on Appium 1.9.1 with C# client 4.0.0.4 -beta.

## Environment

* .NET client build version or git revision if you use some shapshot:  4.0.0.4 -beta.
* Appium server version or git revision if you use some shapshot: 1.9.1
* Desktop OS/version used to run Appium if necessary: Windows
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: CLI
* Mobile platform/version under test: Samsung S8
* Real device or emulator/simulator: Real

## Details
Automation name: UIAUTOMATOR2
App: Hybrid app
Version: Android O

## Code To Reproduce Issue [ Good To Have ]
MobileDriver.FindElementByXPath(element).Click();

## Exception stacktraces
https://gist.github.com/MummanaSubramanya/01e2bb906d1064b8c2f476d1a63cb618

## Link to Appium logs
https://gist.github.com/MummanaSubramanya/8b35a4388667a44e6aa20aac0d9b89d5

**Comment by mykola-mokhnach** [comment]
> [debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//*[@text='Devices config.']/../android.widget.Button","context":"","multiple":false}}

This log is NOT from uiautomator2

**Comment by MummanaSubramanya** [comment]
Sorry My bad "UIAutomator2" was getting overridden by "Appium". Issue got resolved
