### ISSUE TITLE
get Size not working in Linux appium 1.9.1 

### ISSUE THREAD

**Issue by MummanaSubramanya** [appium/appium-dotnet-driver#285]
## The problem
I have hybrid app and Im trying the below method 
`MobileDriver.FindElement(LocateElement(type, object)).Size` which works fine when running in windows machine with appium server 1.9.1 here is the [windows gist](https://gist.github.com/MummanaSubramanya/ef966924f9cd13abd760366645a5e4fb) When I try to run the same code in Linux machine with appium server 1.9.1 it fails with error "Unknown command". Here is the gist for linux appium server [linux gist](https://gist.github.com/MummanaSubramanya/1c7f34b7d99e7cee0b9465dc96b3688a) 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: Linux and Windows 10
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android o
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: CLI for linux and Exe for windows

## Details

`<add key="AppiumServer" value="127.0.0.1" />
      <add key="AppiumServerPort" value="4723" />
      <add key="PlatformName" value="Android" />
      <add key="AutomationName" value="uia" />
      <add key="PlatformVersion" value="8.0" />
      <add key="DeviceName" value="xxxxxxx" />
      <add key="AppPackage" value="com.xxx.xxx" />
      <add key="AppActivity" value=".MainActivity" />
      <add key="AutoWebview" value="true" />`

**Comment by MummanaSubramanya** [comment]
please refer issue https://github.com/appium/appium/issues/11619 for more details

**Comment by KazuCocoa** [comment]
This should fix by https://github.com/appium/appium-uiautomator2-driver/pull/240
