### ISSUE TITLE
Specified cast is not valid on OSX

### ISSUE THREAD

**Issue by ervin-chan-bcs** [appium/appium-dotnet-driver#288]
## Description

getting a "Specified cast is not valid" at 
openQA.Selenium.Appium.Properties.Resources.get_npm_script_unix () while running in OSX.

## Environment

* .NET client build version or git revision if you use some shapshot: 4.0.0.4-beta
* Appium server version or git revision if you use some shapshot: 1.9.1
* Desktop OS/version used to run Appium if necessary: Mac OS High Sierra 10.13.6
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: Node v10.5.0
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Real Device

## Details

When trying to start appium programatically on IOS, it fails with error "Specified cast is not valid".

## Code To Reproduce Issue [ Good To Have ]

On IOS using NUnit, create a simple test that automatically starts appium with the following codes.

OptionCollector argCollector = new OptionCollector().AddArguments(GeneralOptionList.LogLevel("error"));
            var serviceBuilder = new AppiumServiceBuilder()
                                        .UsingPort(portNumber)
                                        .WithArguments(argCollector);
            service = serviceBuilder.Build();
            service.Start();

Once ran, it fails on serviceBuilder.Build() line.

## Exception stacktraces

I'm unable to generate the line number for the stacktrace, but it fails below:

Specified cast is not valid.
15:26:08   at OpenQA.Selenium.Appium.Properties.Resources.get_npm_script_unix () [0x00014] in <8b741f283b73461291f20d7b158f79d7>:0 
15:26:08   at OpenQA.Selenium.Appium.Service.AppiumServiceBuilder.get_InstalledNodeInCurrentFileSystem () [0x00014] in <8b741f283b73461291f20d7b158f79d7>:0 
15:26:08   at OpenQA.Selenium.Appium.Service.AppiumServiceBuilder.CheckAppiumJS () [0x0003c] in <8b741f283b73461291f20d7b158f79d7>:0 
15:26:08   at OpenQA.Selenium.Appium.Service.AppiumServiceBuilder.get_Args () [0x00006] in <8b741f283b73461291f20d7b158f79d7>:0 
15:26:08   at OpenQA.Selenium.Appium.Service.AppiumServiceBuilder.Build () [0x00014] in <8b741f283b73461291f20d7b158f79d7>:0

**Comment by akinsolb** [comment]
Resolved by #357
