### ISSUE TITLE
Get Appium Server Log Using Client

### ISSUE THREAD

**Issue by MummanaSubramanya** [appium/appium-dotnet-driver#289]
## Description

I want to get the appium server log using the c# code. I know I can store the log using the appium& > log.txt but I need for a purpose something line Driver.GetAppiumServerLog();

## Environment

* .NET client build version or git revision if you use some shapshot: 4.0.0.4 beta
* Appium server version or git revision if you use some shapshot: 1.9.2@beta
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: 8.0
* Real device or emulator/simulator: Real

**Comment by lanzelot1989** [comment]
I read up on this and this blog post describes how this should be possible after this ticket has been implemented:
https://appiumpro.com/editions/88 

Currently this
```
        private string GetAppiumServerLog()
        {
            var entries = CurrentDriver.Manage().Logs.GetLog("server");
            var log = new StringBuilder("======== APPIUM SERVER LOGS ========");
            foreach (var entry in entries)
            {
                log.Append($"{entry.Timestamp} {entry.Message}\r\n");
            }
                    
            log.Append("================");
            return log.ToString();
        }
```
fails with a NullReferenceException on GetLog("server") call.

As per the blog post the option 
```
--allow-insecure=get_system_logs
```
needs to be added to allow the retrieval of the Appium server logs.

Please let me know if you (@MummanaSubramanya) meant something else with this ticket.
