### ISSUE TITLE
Exception: A new session could not be created. W3C capabilities: 'deviceName' can't be blank

### ISSUE THREAD

**Issue by EricAtHaufe** [appium/appium-dotnet-driver#293]
Hi I'm updating classic window app test case by replacing DesiredCapabilities with AppiumOptions and AppiumCapablilities, but I currently have a problem I cannot resolve.

This is error in log file:
   [Appium] Could not parse W3C capabilities: 'deviceName' can't be blank
 

This is the updated test script:

AppiumOptions appiumOptions = new AppiumOptions();
appiumOptions.AddAdditionalCapability("app", @ExecutablePath);
appiumOptions.AddAdditionalCapability("platformName", "Windows");
appiumOptions.AddAdditionalCapability("deviceName", "WindowsPC");

session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appiumOptions, TimeSpan.FromSeconds(1.5));

At this point, exception is throw,  test case aborts but the application is launched.

Visiual Studio 2017 reports:
Message: Die Methode "Appium.InstallationTest.ClassInitialize" für die Klasseninitialisierung hat eine Ausnahme ausgelöst. 
OpenQA.Selenium.WebDriverException: OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for 
URL http://127.0.0.1:4723/wd/hub/session timed out after 1.5 seconds. ---> System.Net.WebException: Timeout für Vorgang überschritten.

Appium Log file:
Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"C:\\Program Files (x86)\\XXX\\XXX\\XXX\\XXX.exe","platformName":"Windows","deviceName":"WindowsPC"},"capabilities":{"firstMatch":[{"platformName":"Windows"}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"app":"C:\\Program Files (x86)\\XXX\\XXX\\XXX\\XXX.exe","platformName":"Windows","deviceName":"WindowsPC"},null,{"firstMatch":[{"platformName":"Windows"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1542627435238 (12:37:15 GMT+0100 (GMT+01:00))
[Appium] Could not parse W3C capabilities: 'deviceName' can't be blank
[Appium] Trying to fix W3C capabilities by merging them with JSONWP caps
[BaseDriver] The capabilities ["app","deviceName"] are not standard capabilities and should have an extension prefix
[Appium] Creating new WindowsDriver (v1.4.0) session
[Appium] Capabilities:
[Appium]   app: C:\Program Files (x86)\XXX\XXX\XXX\XXX.exe
[Appium]   deviceName: WindowsPC
[Appium]   platformName: Windows
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"C:\\Program Files (...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: app.
[BaseDriver] Session created with session id: e05f0406-e54c-4c5f-b239-a94d1244b66d
[WinAppDriver] You must use WinAppDriver version 1.1
[WinAppDriver] Verifying WinAppDriver version 1.1 is installed via comparing the checksum.
[debug] [WinAppDriver] WinAppDriver changed state to 'starting'
[WinAppDriver] Killing any old WinAppDrivers on same port, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"4724 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I winappdriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
[WinAppDriver] No old WinAppDrivers seemed to exist
[WinAppDriver] Spawning winappdriver with: 4724/wd/hub
[WinAppDriver] [STDOUT] Windows Application Driver listening for requests at: http://127.0.0.1:4724/wd/hub
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[WinAppDriver] [STDOUT] Press ENTER to exit.
[WinAppDriver] [STDOUT] 

Any idea on the source of the problem?

Appium.WebDriver version: 4.0.0.4-beta
Selenium.WebDriver version: 3.14
Selenium.Support version: 3.14
Newtonsoft.Json  version=11.0.2

**Comment by KazuCocoa** [comment]
It is because of dotnet driver has no fix for W3C adaption, I assume.
e.g.: https://github.com/appium/python-client/blob/b6795db715d8b86b5ca5da980d597f42b31343d5/appium/webdriver/webdriver.py#L62

Then, Appium fallback to previous spec.

**Comment by afgaiel** [comment]
did you find any solution for this problem?

**Comment by akinsolb** [comment]
@afgaiel do you still get this exception with the latest server and driver?

**Comment by afgaiel** [comment]
@akinsolg: thanks very much. the problem is solved.  I think the device name had a space and I corrected it.
