### ISSUE TITLE
Clipboard.SetText() is not working in Appium + Android + C#

### ISSUE THREAD

**Issue by PraveenNalla23** [appium/appium-dotnet-driver#295]
Description:
I was trying to paste a string inside a textbox using clipboard but was not working in android appium c# version whereas in Desktop chrome browser version its working properly.
Clipboard.GetText() is returning empty string.

- Environment

Appium server version or git revision if you use some shapshot: Appium Desktop v1.9.1
Desktop OS/version used to run Appium if necessary: Windows 10 Enterprise
Mobile platform/version under test: Android 8.0
Real device or emulator/simulator: Real Device Samsung Galaxy S3
IDE: VisualStudio 2017 Enterprise and C#
Appium WebDriver 4.0.0.4-beta
Selenium.WebDriver 3.14.0 same observation with 3.141.0 as well

- Code To Reproduce Issue:

Thread thread = new Thread(() => Clipboard.SetText("SampleText", TextDataFormat.Text));
                thread.SetApartmentState(ApartmentState.STA); //Set the thread to STA
                thread.Start();
                thread.Join();
                DefaultsTextBox.SendKeys(OpenQA.Selenium.Keys.Control + System.Windows.Forms.Keys.V);

Nothing is entered is text box.

- Link to Appium logs
[HTTP] --> POST /wd/hub/session/54345edd-dd95-4838-aa82-8837480b8057/element
[HTTP] {"using":"css selector","value":"[test-id='defaults']"}
[W3C] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Matched '/wd/hub/session/54345edd-dd95-4838-aa82-8837480b8057/element' to command name 'findElement'
[JSONWP Proxy] Proxying [POST /wd/hub/session/54345edd-dd95-4838-aa82-8837480b8057/element] to [POST http://127.0.0.1:8000/wd/hub/session/ed637d415c0d30960dab0447178138e8/element] with body: {"using":"css selector","value":"[test-id='defaults']"}
[JSONWP Proxy] Got response with status 200: {"sessionId":"ed637d415c0d30960dab0447178138e8","status":0,"value":{"ELEMENT":"0.9114265502182417-1"}}
[JSONWP Proxy] Replacing sessionId ed637d415c0d30960dab0447178138e8 with 54345edd-dd95-4838-aa82-8837480b8057
[HTTP] <-- POST /wd/hub/session/54345edd-dd95-4838-aa82-8837480b8057/element 200 79 ms - 106
[HTTP] 
[HTTP] --> POST /wd/hub/session/54345edd-dd95-4838-aa82-8837480b8057/element/0.9114265502182417-1/value
[HTTP] {"text":"V","value":["","V"]}
[W3C] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Matched '/wd/hub/session/54345edd-dd95-4838-aa82-8837480b8057/element/0.9114265502182417-1/value' to command name 'setValue'
[JSONWP Proxy] Proxying [POST /wd/hub/session/54345edd-dd95-4838-aa82-8837480b8057/element/0.9114265502182417-1/value] to [POST http://127.0.0.1:8000/wd/hub/session/ed637d415c0d30960dab0447178138e8/element/0.9114265502182417-1/value] with body: {"text":"V","value":["","V"]}
[JSONWP Proxy] Got response with status 200: {"sessionId":"ed637d415c0d30960dab0447178138e8","status":0,"value":null}
[JSONWP Proxy] Replacing sessionId ed637d415c0d30960dab0447178138e8 with 54345edd-dd95-4838-aa82-8837480b8057
[HTTP] <-- POST /wd/hub/session/54345edd-dd95-4838-aa82-8837480b8057/element/0.9114265502182417-1/value 200 342 ms - 76

Please look into the issue

**Comment by akinsolb** [comment]
@PraveenNalla23 Which namespace is Clipboard.SetText from?
