### ISSUE TITLE
startIWDP Error in ios appium

### ISSUE THREAD

**Issue by csharsha** [appium/appium-dotnet-driver#296]
## Description

Please describe the issue. It may be a bug description. So then please briefly descride steps which you were trying to perform and what happened instead.
If there is the feature you want to see added to Appium .NET client so please describe necessity of this feature and the way that it should work.

## Environment

* .NET client build version or git revision if you use some shapshot:
* Appium server version or git revision if you use some shapshot:
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test:
* Real device or emulator/simulator:

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.
You can git clone https://github.com/appium/sample-code or https://github.com/appium/sample-code/tree/master/sample-code/apps and reproduce an issue using C# and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted C# code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Exception stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by .NET.

## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by csharsha** [comment]
When I try to launch ios-webkit-debug-proxy to access webview contexts in **ios device using ios capabilities in appium desktop,** I am getting error like "**Error: Timed out waiting for ios_webkit_debug_proxy to open" and "Could not connect to lockdownd, error code -21. Exiting.,Unable to attach 92818ac7d66960e2b5bd76dcbf5355953f536555 inspector"**

I eventually tried to update

brew update
brew reinstall libimobiledevice
brew reinstall ios-webkit-debug-proxy 

but nothing worked. Please help.

**Comment by imurchie** [comment]
Sometimes it is necessary to get the latest `libimobiledevice` and `ios-webkit-debug-proxy`
```
brew uninstall ios-webkit-debug-proxy
brew uninstall libimobiledevice

brew install libimobiledevice --HEAD
brew install ios-webkit-debug-proxy --HEAD
```

**Comment by csharsha** [comment]
I did both but no luck!

**Comment by akinsolb** [comment]
Closing as this isn't a .Net client issue.
