### ISSUE TITLE
calculator example not working

### ISSUE THREAD

**Issue by markusNirpaw** [appium/appium-dotnet-driver#305]
I'm trying to just run the calculator test C# example as provided inside visual studio 2017. When I download and build the example, it shows several lines as deprecated;
```
                DesiredCapabilities appCapabilities = new DesiredCapabilities();
                appCapabilities.SetCapability("app", CalculatorAppId);
                appCapabilities.SetCapability("deviceName", "WindowsPC");
```
 and one as an error that needs to be changed;
`
CalculatorSession.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(1.5));`
to
` session.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(1.5);`

.
I get errors such as this for each test (Addition, division, Multipluication, Substraction, Templatized) when I try and run them: 

> 
> Test Name:	Addition
> Test FullName:	CalculatorTest.ScenarioStandard.Addition
> Test Source:	C:\Users\[user]\Downloads\WinAppDriver-master\Samples\C#\CalculatorTest\ScenarioStandard.cs : line 32
> Test Outcome:	Failed
> Test Duration:	0:00:00
> 
> Result StackTrace:	
> at OpenQA.Selenium.Appium.AppiumDriver`1..ctor(Uri remoteAddress, ICapabilities desiredCapabilities, TimeSpan commandTimeout)
>    at OpenQA.Selenium.Appium.AppiumDriver`1..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
>    at OpenQA.Selenium.Appium.Windows.WindowsDriver`1..ctor(Uri remoteAddress, DesiredCapabilities desiredCapabilities)
>    at CalculatorTest.CalculatorSession.Setup(TestContext context) in C:\Users\[user]\Downloads\WinAppDriver-master\Samples\C#\CalculatorTest\CalculatorSession.cs:line 42
>    at CalculatorTest.ScenarioStandard.ClassInitialize(TestContext context) in C:\Users\[user]\Downloads\WinAppDriver-master\Samples\C#\CalculatorTest\ScenarioStandard.cs:line 101
> Result Message:	Class Initialization method CalculatorTest.ScenarioStandard.ClassInitialize threw exception. System.TypeLoadException: System.TypeLoadException: Method 'Dispose' in type 'OpenQA.Selenium.Appium.Service.AppiumCommandExecutor' from assembly 'appium-dotnet-driver, Version=3.0.0.2, Culture=neutral, PublicKeyToken=null' does not have an implementation..
> 

I'm a c# app developer, and really don't have a clue what I'm doing with Appium/WinAppDriver (Ive just been told to figure it out), and after looking at this for a bit am at a loss as how to troubleshoot whats going on here. I don't know if this is an Appium issue, a WinAppDriver issue, or something else, and help would be appreciated.

**Comment by KazuCocoa** [comment]
That is MJSONWP (not W3C) protocol's wait method, according to selenium webdriver.
https://github.com/SeleniumHQ/selenium/blob/07a18746ff756e90fd79ef253a328bd7dfa9e6dc/dotnet/src/webdriver/Remote/WebDriverWireProtocolCommandInfoRepository.cs#L113

I assume previously the example worked as MJSONWP. But recently it works in W3C.
The example should update to the latest (W3C) format.
(It is because differences between MJSONWP and W3C protocol in .NET client side)

**Comment by mshamshaddin** [comment]
For me, it was an issue with the Selenium Driver.  Check the version of your Selenium.WebDriver.  3.0.1 is compatible with Appium,

**Comment by anilr945** [comment]
Me too facing the issue with Calculator application. Not able to automate the clicks. 
Getting exception like:
{"using":"accessibility id","value":"TogglePaneButton"}
HTTP/1.1 404 Not Found
Content-Length: 139
Content-Type: application/json

{"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}
              
 DesiredCapabilities appCapabilities = new DesiredCapabilities();
                appCapabilities.SetCapability("app", _calApp);
                appCapabilities.SetCapability("deviceName", "WindowsPC");
                appCapabilities.SetCapability("platformName", "Windows");

                session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities);
                session.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(5));

                session.FindElementByAccessibilityId("TogglePaneButton").Click();
                session.FindElementByAccessibilityId("num6Button").Click();
                session.FindElementByAccessibilityId("plusButton").Click();
                session.FindElementByAccessibilityId("num6Button").Click();
                session.FindElementByName("Equals").Click();

Trying for so long, not able figure out the problem. Any help would be appreciated.

**Comment by akinsolb** [comment]
The calculator example code isn't in appium repository. Please raise the issue in the repo the code belongs in. 
FYI for an example of working calculator tests, see the [tests](https://github.com/appium/appium-dotnet-driver/blob/master/test/integration/Windows/ClickElementTest.cs) in this repository. They cannot be a part of a test run in azure pipelines, so they may not exist in this repo for long.
