### ISSUE TITLE
{"There is already an option for the platformName capability. Appium.Net 4.0.0.5

### ISSUE THREAD

**Issue by pavkr** [appium/appium-dotnet-driver#311]
## Description

Exception being thrown on extentiating Appium Chrome Driver

## Environment

* Node.js version 10.13.0 | Appium 1.10.1
* Real device 

## Details
  <package id="Appium.Net" version="4.0.0.5" targetFramework="net461" />
  <package id="Selenium.Support" version="3.141.0" targetFramework="net461" />
  <package id="Selenium.WebDriver" version="3.141.0" targetFramework="net461" />
## Code To Reproduce Issue [ Good To Have ]

`
           ChromeOptions options = new ChromeOptions();
           options.PlatformName = "Android";
            options.AddAdditionalCapability( MobileCapabilityType.DeviceName, deviceObject.Name );
            options.AddAdditionalCapability( MobileCapabilityType.AutomationName, AutomationName.AndroidUIAutomator2 );
            options.AddAdditionalCapability( MobileCapabilityType.Udid, deviceObject.Udid );
`
            `Uri server = new Uri( Localhost );
            driver = new AndroidDriver<RemoteWebElement>( server, options, new TimeSpan(0, 1, 30));`

## Exception stacktraces

[<script](https://gist.github.com/pavkr/c012cff805d36d1609ddc2fb039cf992.js) src="https://gist.github.com/pavkr/c012cff805d36d1609ddc2fb039cf992.js"></script>

**Comment by MummanaSubramanya** [comment]
you need to use AppiumOptions options = new AppiumOptions(); instead of ChromeOptions options = new ChromeOptions(); and options.AddAdditionalCapability(MobileCapabilityType.BrowserName, "chrome"]);

**Comment by pavkr** [comment]
Works just fine, thank you!

**Comment by pavkr** [comment]
Note: to pass the capabilities
`
AppiumOptions options = new AppiumOptions();
options.AddAdditionalCapability(MobileCapabilityType.BrowserName, "chrome"]);

ChromeOptions chromeOptions = new ChromeOptions();
chromeOptions.AddArgument( "enable-precise-memory-info" );
chromeOptions.AddArgument( "disable-infobars" );

options.AddAdditionalCapability(ChromeOptions.Capability, chromeOptions);
`

**Comment by Djkmichaela** [comment]
hi can anyone assist me i keep getting the same exception

 System.ArgumentException : There is already an option for the platformName capability. Please use the  instead.
    Parameter name: capabilityName

My code below:

  public void OpenAppium()
        {
            AppiumOptions options = new AppiumOptions();
            options.AddAdditionalCapability(MobileCapabilityType.BrowserName, "chrome");
            ChromeOptions chromeoption = new ChromeOptions();
            chromeoption.AddAdditionalCapability(MobileCapabilityType.DeviceName, "emulator-5554");
            chromeoption.AddAdditionalCapability(MobileCapabilityType.PlatformName, "Android");
            chromeoption.AddAdditionalCapability(MobileCapabilityType.App, @"C: \Users\user\source\tabscorAn\platforms\android\app\build\outputs\apk\debug\app-debug.apk");
            chromeoption.AddAdditionalCapability("chromedriverExecutable", @"C:\Users\user\source\repos\chromedriver");

            options.AddAdditionalCapability(ChromeOptions.Capability, chromeoption);
            AndroidDriver<AndroidElement> androidDriver = new AndroidDriver<AndroidElement>(options);

            var driv = androidDriver.Contexts.First(x => x.Contains("WEBVIEW_"));
            androidDriver.Context = driv;
        }
