### ISSUE TITLE
How to access the WPF custom control's elements?

### ISSUE THREAD

**Issue by NeelakandanKannan** [appium/appium-dotnet-driver#312]
## The problem
Our custom control is designed in drawing architecture. i.e. every elements in a control are drawn using DeviceContext's Draw methods. We are not arranging elements as UI elements. To provide the accessibility support, we have provided the **AutomationPeer** support for control (not inner elements). 

Can you please let us know how we can provide the testing support for inner elements to read using Appium?

We have tried the followings,

`
AutomationElement datagrid = desktop.FindFirst(TreeScope.Descendants, new PropertyCondition(AutomationElement.AutomationIdProperty, "gridControl"));

if (datagrid == null)
    Assert.Fail("GridControl is null");
else
{
     var pattern = datagrid1.GetCurrentPattern(GridPatternIdentifiers.Pattern) as GridPattern;
     var item = pattern.GetItem(1, 1);
     if (item != null)
     {
        object value = null;
        item.TryGetCurrentPattern(ValuePattern.Pattern, out value);
        var valueProvider = value as ValuePattern;
        var currentValue = valueProvider.Current.Value;
    }
}
`
_[AutomationElement](https://docs.microsoft.com/en-us/dotnet/api/system.windows.automation.automationelement?view=netframework-4.7.2)_ class provides support to access the inner elements. 

As like the above methods, can we get any solution to read the inner elements?

## Environment

* WPF platform

**Comment by akinsolb** [comment]
Closing as this addressed by WinAppDriver team: https://github.com/microsoft/WinAppDriver/issues/600
