### ISSUE TITLE
WindowsDriver - Alternative for DesiredCapabilities

### ISSUE THREAD

**Issue by jamiel44** [appium/appium-dotnet-driver#316]
Now that DesiredCapabilities are deprecated, what is the best alternative to use with a WindowsDriver?

I appreciate that although using DesiredCapabilities will still work, but I would prefer to future proof my tests.

I'm coding in C# with Visual Studio.

Thanks

E.G.
DesiredCapabilities appCapabilities = new DesiredCapabilities();
appCapabilities.SetCapability("app", @"C:\Windows\System32\notepad.exe");
NotepadSession = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), appCapabilities);

**Comment by akinsolb** [comment]
@jamiel44 for the time being its AppiumOptions, which is available in the beta versions. Future releases may proceed with this or provide an alternative.

**Comment by TroyWalshProf** [comment]
@akinsolb  - Should this still be open?

AppiumOptions has been released and just works

Example 1:
```
AppiumOptions options = new AppiumOptions();

options.AddAdditionalCapability("app", @"C:\Windows\System32\notepad.exe");
return new WindowsDriver<IWebElement>(new Uri("http://127.0.0.1:4723"), options);
```


Example 2:
```
AppiumOptions options = new AppiumOptions();

options.AddAdditionalCapability("app", "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App");
return new WindowsDriver<IWebElement>(new Uri("http://127.0.0.1:4723"), options);
```

**Comment by akinsolb** [comment]
@TroyWalshProf No, There should be another task to develop `AppiumOptions` further, but this should be closed.
