### ISSUE TITLE
Add support for Espresso DataMatcher locator

### ISSUE THREAD

**Issue by akinsolb** [appium/appium-dotnet-driver#318]
related to [#12372](https://github.com/appium/appium/issues/12372) & [#895](https://github.com/appium/appium-desktop/pull/895)

**Comment by LyubomirStoimchev** [comment]
@akinsolb Done in https://github.com/appium/appium-dotnet-driver/pull/408

**Comment by akinsolb** [comment]
Thanks @LyubomirStoimchev
