### ISSUE TITLE
fingerprint endpoint is not implemented

### ISSUE THREAD

**Issue by LasseHall** [appium/appium-dotnet-driver#322]
## Description

The fingerprint endpoint is not implemented (http://appium.io/docs/en/commands/device/authentication/finger-print/). This endpoint is needed for functional tests on emulators to verify app behaviour around the biometrics authentication feature passing or failing.

**Comment by dpgraham** [comment]
@akinsolb are you able to take this, or do you want me to?

**Comment by akinsolb** [comment]
@dpgraham  I'm sure you had a PR with this a while back. Please do, I'm looking at a set of other bugs

**Comment by akinsolb** [comment]
resolved by #324
