### ISSUE TITLE
Appium Service Builder takes more than 3 minutes

### ISSUE THREAD

**Issue by manivannan184** [appium/appium-dotnet-driver#323]
## The problem

I am trying to start a Appium Android Service with AppiumServiceBuilder() but it takes more than 3 minutes to build

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0-beta.0 (issue is happening with recent previous appium versions as well)
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): 10.15.3
* Npm or Yarn package manager: npm 6.4.1
* Mobile platform/version under test: Android Oreo
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.Webdriver library 4.0.0.5-beta for C#

## Details

I am starting Appium service for android device using below statement:

`_service = new AppiumServiceBuilder().UsingPort(4723).WithLogFile(fileInfo).WithArguments(args).Build();`

First time when Appium is installed, the service starts within 15 seconds.

However if i restart the Desktop or later, it takes more than 3 minutes to start the session.
(Whether the device already has Appium.settings app or not - the behavior is same)

## Link to Appium logs

No appium session is created during the error time, so no logs can be provided.

## Code To Reproduce Issue 

```
var args = new OptionCollector().AddArguments(GeneralOptionList.LocalTimezone()).AddArguments(GeneralOptionList.OverrideSession());

            var fileInfo = new FileInfo(Path.Combine(CatUtilityInterface.Instance.Automationpath + @"\Appium_DEV-" +
                                                DateTime.Now.ToString("yyyy-MMM-dd_HH-mm-ss") + ".txt"));

            _service = new AppiumServiceBuilder().UsingPort(4723).WithLogFile(fileInfo).WithArguments(args).Build();

            _service?.Start();
```

**Comment by manivannan184** [comment]
delay happens at this statement

`this.AppiumJS = this.InstalledNodeInCurrentFileSystem;`

Class: AppiumServiceBuilder
Namespace: OpenQA.Selenium.Appium.Service

I found the recovery by adding below environmental variable:
_APPIUM_BINARY_PATH
C:\Users\<user>\AppData\Roaming\npm\node_modules\appium\build\lib\main.js_

**Comment by broetchenrackete36** [comment]
I did a little bit of digging and its (probably) because update-notifier doesn't have a network-connection (maybe you are behind a proxy, update-notifier doesn't honor proxy-settings). See discussion on npm-community: https://npm.community/t/npm-version-takes-3-minutes-to-complete-when-run-in-child-process-and-behind-corporate-proxy/1658/11 and pull-request https://github.com/npm/cli/pull/61 .

Workarounds are to either set `APPIUM_BINARY_PATH` or `NO_UPDATE_NOTIFIER="true"`.
