### ISSUE TITLE
What is the difference between the Applium.WebDriver and the Gravity.Drivers.WebDriver nuget packages? 

### ISSUE THREAD

**Issue by hooligan495** [appium/appium-dotnet-driver#326]
I'm starting to use appium for testing a UWP app. 
When I follow the instructions on the main page and it says to install the nuget package I see 2 that looks similar but one is potentially newer...  What's the difference between the 2 packages?  They both ref this github repo.

**Comment by akinsolb** [comment]
Hi @hooligan495 I'm not sure which documentation you're referring to, but I don't think the Gravity.* NuGet package is not released by the appium organisation
