### ISSUE TITLE
. Method 'Dispose' in type 'OpenQA.Selenium.Appium.Service.AppiumCommandExecutor' from assembly 'appium-dotnet-driver, Version=3.0.0.2, Culture=neutral, PublicKeyToken=null' does not have an implementation.

### ISSUE THREAD

**Issue by rameshrc** [appium/appium-dotnet-driver#327]
I get an error when I launch Appium windows driver for WinForm app
. Method 'Dispose' in type 'OpenQA.Selenium.Appium.Service.AppiumCommandExecutor' from assembly 'appium-dotnet-driver, Version=3.0.0.2, Culture=neutral, PublicKeyToken=null' does not have an implementation.

                DesiredCapabilities appCapabilities = new DesiredCapabilities();
                appCapabilities.SetCapability("app", @"C:\Program Files (x86)\Simulator\Simulator.exe");
                appCapabilities.SetCapability("appArguments", @"Startup.config");
                appCapabilities.SetCapability("appWorkingDir", @"C:\Program Files (x86)\Simulator");
                WindowsDriver<WindowsElement> windowsDriver = new WindowsDriver<WindowsElement>(appCapabilities);

  <package id="Appium.WebDriver" version="3.0.0.2" targetFramework="net472" />
  <package id="Castle.Core" version="3.3.3" targetFramework="net472" />
  <package id="MSTest.TestAdapter" version="1.4.0" targetFramework="net472" />
  <package id="MSTest.TestFramework" version="1.4.0" targetFramework="net472" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net472" />
  <package id="Selenium.Support" version="3.141.0" targetFramework="net472" />
  <package id="Selenium.WebDriver" version="3.141.0" targetFramework="net472" />
  <package id="Selenium.WebDriver.ChromeDriver" version="72.0.3626.69" targetFramework="net472" />

**Comment by akinsolb** [comment]
HI @rameshrc, can you try running this test with the latest [beta version](https://www.nuget.org/packages/Appium.WebDriver/4.0.0.6-beta)
