### ISSUE TITLE
How can we get android element from mouse cursor location in google emulator?

### ISSUE THREAD

**Issue by rajendarm** [appium/appium-dotnet-driver#334]
Hi Everyone,

We have very good experience team with Coded UI. We would like to use the same team to test our mobile application. Now I have started writing tests using appium-dotnet-driver. We don't find some APIs listed below
>> We would like to get the android element from the cursor location.
>> We are not able to get any attribute or properties on AndroidElement. We have used GetAttribute or GetProperty but no luck
>> Is there any way to get XPath, class name and etc on AndroidELement.
>> We are able to get page source on the driver.  Is there any way to get page source on AndroidElement?
>> We don't find synchronization functions. Is there any API
>> Is there any C# api to inspect android app (apk) ?
Can anyone help to find or improve above functionalities?

Regards,
Raj

**Comment by mykola-mokhnach** [comment]
I'd rather use Appium forum to ask questions. This is the place for bugs

**Comment by rajendarm** [comment]
Thank you for the response. Appium has Inspect tool to get control information. But here I want to get control information in c# code. I don't want to install Appium because everything is available in appium-dotnet-driver only. I need only single control information at least page source Android element in c#.

**Comment by akinsolb** [comment]
AFAIK you cannot get an element based on the location of a mouse cursor.

There no such thing as a page source for an element, but I presume you mean the value of element attribute(s).

AndroidElement.GetAttribute(string attributeName) is how you obtain the specified attribute for an element & works in [v4.1.1](https://www.nuget.org/packages/Appium.WebDriver/4.1.1)
