### ISSUE TITLE
Java Client vs .NET Client

### ISSUE THREAD

**Issue by cosminstirbu** [appium/appium-dotnet-driver#335]
Hello,

Over the last year we've noticed that the feature gap between the Java Client and the .NET Client got larger and larger.

Obviously we understand that this is an open source project so the availability for maintenance and feature development is limited.

Since Microsoft are already developing a [Windows Driver ](https://github.com/microsoft/WinAppDriver) that is integrated by Appium Server, I was thinking that maybe the Appium organisation could reach out to Microsoft asking them to become active contributors and help addressing the feature gap.

Hopefully I won't receive any backlash for this as I'm fully aware of what it takes to maintain and develop an open source project.

Thank you,
Cosmin

**Comment by KazuCocoa** [comment]
Hi @yodurr 
I hope you are doing well. I mention you since you thankfully take care of appium-windows-driver repo.
Do you think your team (or someone?) can help maintain this client?

**Comment by yodurr** [comment]
We've participated before but currently don't have capacity to contribute a great deal to this project.  I will ask around.

**Comment by KazuCocoa** [comment]
Thanks very much

**Comment by akinsolb** [comment]
Closing as this thread has not had recent activity
