### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by BrijeshKaria** [appium/appium-dotnet-driver#337]
Do you have plan to release new version? Current version on budget is 3.0.2.
I was looking for support to updated selenium version- this was updated in 4.0.0.1 beta

**Comment by KazuCocoa** [comment]
@akinsolb 
Hi, do you have any idea about this?

**Comment by akinsolb** [comment]
@BrijeshKaria @KazuCocoa Yeah, I'll try do this within the next fortnight but it won't support Selenium v4, instead it will support the last version of Selenium v3 (3.141.0)

**Comment by KazuCocoa** [comment]
Thanks.
Yes, it's good to me > v4
(Other clients also have not been updated to the v4-alpha)

**Comment by BrijeshKaria** [comment]
Thanks.
3.141.0 is good for me.

**Comment by LucasLibis** [comment]
Hello,
Any news on the support of the latest version of Selenium?

**Comment by BrijeshKaria** [comment]
@akinsolb any luck?

**Comment by akinsolb** [comment]
@BrijeshKaria @LucasLibis  A major release can be found [here](https://www.nuget.org/packages/Appium.WebDriver/4.0.0)

**Comment by LucasLibis** [comment]
@akinsolb Great job! Thank you
