### ISSUE TITLE
Unknown server side issue

### ISSUE THREAD

**Issue by charan517333** [appium/appium-dotnet-driver#342]
## Description

I'm trying to run two different ports of appium with different model android devices.

S10: port:1237

S9: port: 1298

Observed behavior: Everytime when I run in multiple real devices. I was able to see unknow service side issue and gets terminated and also all the remaining test cases are skipped.

## Environment

* Appium server version 1.13
* Desktop OS/version used to run Appium if necessary:
* Mobile platform/version under test: 9(pie)
* Real device or emulator/simulator: Real device

## Details

Please provide more details, if necessary.
[Capabilities.txt](https://github.com/appium/appium-dotnet-driver/files/3541340/Capabilities.txt)
[Appium failure.txt](https://github.com/appium/appium-dotnet-driver/files/3541341/Appium.failure.txt)

**Comment by akinsolb** [comment]
Try using the dotnet client or raising your issue [here](https://github.com/appium/java-client) in the java client repo
