### ISSUE TITLE
Please release/deploy 4.0.0.6 to Nuget

### ISSUE THREAD

**Issue by lanzelot1989** [appium/appium-dotnet-driver#350]
## Description

Please pack and release the version 4.0.0.6 to nuget. Thanks in advance.

**Comment by akinsolb** [comment]
There have been some changes since 4.0.0.6-beta. The ordering of release may reflect differently in NuGet because the semantics of versioning changed. The major release is [here](https://www.nuget.org/packages/Appium.WebDriver/4.0.0)

**Comment by lanzelot1989** [comment]
Thanks a lot, we had a successful update; maybe some pointers for others on the migration from 3.0.0.2
* Breaking changes include the usage of AppiumOptions instead of DesiredCapabilities for driver initialization
* Page Objects support was moved to https://github.com/DotNetSeleniumTools/DotNetSeleniumExtras: make sure to update the usings
* For us the usage of "FindsBy(How=How.ID, Using=..." also worked for iOS, but we now had to change it towards "[FindsByIOSUIAutomation(ID =..." in our page objects
* Driver.Swipe is gone, use TouchAction like so
```
var movementTimeMs = 1500;
new TouchAction(Driver)
        .Press(from.X, from.Y)
        .Wait(movementTimeMs)
        .MoveTo(to.X, to.Y)
        .Release()
        .Perform();
```
* update your hubs standalone server to 3.141.59
* nodeconfigs needed to be adapted. We define "maxInstances", "appPackage", "platformName", "automationName" now which seems to work for the capability matching.
