### ISSUE TITLE
Does appium-dotnet-driver support Automate Mac app ?

### ISSUE THREAD

**Issue by QITIE** [appium/appium-dotnet-driver#352]
## Description

Just wounder if my c# code base on the appium-dotnet-driver can talk to Appium-for-mac driver on Mac on ?

## Environment
windows pc
Macbook pro

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

static void Main(string[] args)
        {
            AppiumOptions appCapabilities = new AppiumOptions();

            appCapabilities.AddAdditionalCapability("app", "/Applications/Microsoft Outlook.app");
            appCapabilities.AddAdditionalCapability("udid", "5C946EED-D63E-5658-B99E-F7EC65B4D49F");
            appCapabilities.AddAdditionalCapability("deviceName", "Mac");
            appCapabilities.AddAdditionalCapability("platformName", "Mac");
            appCapabilities.AddAdditionalCapability("automationName", "XCUITest");
            IOSDriver<IWebElement> driver = new IOSDriver<IWebElement>(new Uri("http://xx.xx.xx.129:4723/wd/hub"), appCapabilities);

            signInOutlookTestMac(driver);
        }

**Comment by jlipps** [comment]
any appium client should be able to do this. did you try it? if you think you've encountered a bug, post an issue at the appium/appium issue tracker.
