### ISSUE TITLE
ICommandError

### ISSUE THREAD

**Issue by mehmetbeyHZ** [appium/appium-dotnet-driver#353]
![Screenshot_6](https://user-images.githubusercontent.com/12996462/65000397-207a0c00-d8f4-11e9-8751-4a7ca4b20bde.png)
What is the problem?
version 4.0

**Comment by akinsolb** [comment]
@mehmetbeyHZ a constructor does not exist with parameters of the given types (Uri, DesiredCapabilities).

Use the following AndroidDriver constructor AndroidDriver(URI, AppiunOptions)

Replace DesiredCapabilities object with AppiumOptions.cs and use the setAdditionalCapabilities() method of that object to specify capabilities.
