### ISSUE TITLE
System.InvalidCastException : Unable to cast object of type 'System.String' to type 'System.Byte[]'.

### ISSUE THREAD

**Issue by cosminstirbu** [appium/appium-dotnet-driver#356]
Hello,

When referencing https://www.nuget.org/packages/Appium.WebDriver/4.0.0 in a .NET Core project (2.0 or 3.0) and instantiate Appium Service like

`new AppiumServiceBuilder()
                    .UsingAnyFreePort()
                    .WithArguments(new OpenQA.Selenium.Appium.Service.Options.OptionCollector().AddArguments(new System.Collections.Generic.KeyValuePair<string, string>("--log-no-colors", string.Empty)))
                    .Build();`

we receive the following exception:

`System.InvalidCastException : Unable to cast object of type 'System.String' to type 'System.Byte[]'.`

The exception is thrown by this line of code `bytes = Properties.Resources.npm_script_unix;` from `AppiumServiceBuilder`

It seems that it might be related to https://github.com/microsoft/msbuild/issues/2221

Interestingly enough, if I clone the repo and add the project as a reference to my .NET Core project, everything works as expected - so it seems that there might be something wrong with the .nuget package itself.

Also, if I build and generate the standalone .dll, and reference just the .dll - everything works as expected.

I'm not too familiar with the targeting / nuget packaging techniques, so any help with this would be appreciated.

P.S. - this reproduces on macOS

Thanks,
Cosmin

**Comment by reply2sagar** [comment]
Is there any solution for this issue? I am facing same issue on Mac when trying to instantiate AndroidDriver. It works in Windows. Must be to do with NPM and node versions

**Comment by akinsolb** [comment]
@cosminstirbu is it possible that you're using .net45 target or msbuild is using that version of the DLL?

**Comment by cosminstirbu** [comment]
@akinsolb thanks for looking into this.

I would be happy to test if you push a prerelease .nuget package.

**Comment by akinsolb** [comment]
@cosminstirbu Yeah sure no probs. I'll get that out soon

**Comment by clintnetwork** [comment]
Hi,

You need to set the node and appium paths like specific here: https://github.com/appium/appium-dotnet-driver/wiki/How-to-start-an-AppiumDriver-locally#if-there-is-no-specific-parameters-then

Like this:

```csharp
using OpenQA.Selenium.Appium.Service;
using System;
...

Environment.SetEnvironmentVariable(AppiumServiceConstants.NodeBinaryPath, "the full path to node.js executable file");
Environment.SetEnvironmentVariable(AppiumServiceConstants.AppiumBinaryPath, "the full path to appium.js or main.js");
AppiumLocalService service = AppiumLocalService.BuildDefaultService();
service.Start();
 ...
service.Dispose();
```

**Comment by cosminstirbu** [comment]
@akinsolb - any plans of releasing a beta package with this fix?

**Comment by akinsolb** [comment]
Sorry @cosminstirbu tried to fit in more things. Today
