### ISSUE TITLE
C# appium test internet connection on android real device

### ISSUE THREAD

**Issue by rutin31** [appium/appium-dotnet-driver#358]
## Description

How to Check Internet Connection on Android  Real Device
I tried several options:

1. - AndroidDriver.ExecuteScript("mobile: shell",  "ping -c1 www.google.com").ToString();
2. -  AndroidDriver.ExecuteScript("mobile: shell", "{'command': 'ping', 'args': ['-c1', 'www.google.com']}").ToString();
3. -  AndroidDriver.ExecuteScript("mobile: shell", new object[] { "ping",  "www.google.com" }).ToString();

Everyone gets an error message:
error: command' argument is mandatory

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/android-shell.md should help

**Comment by rutin31** [comment]
The link does not help. It does not work. Is there  another way to check internet connection

**Comment by KazuCocoa** [comment]
ah, I thought you were asking the command's format.

https://discuss.appium.io/ is a good place to ask such general questions.
Launching a browser, adding network connection check in the app under test as debug feature (or prepare a helper app) or via `adb shell dumpsys` are common way, I guess.

**Comment by mykola-mokhnach** [comment]
uia2 driver also provides `mobile: deviceInfo` command, which returns extended details about networks available to the device. See https://github.com/appium/appium/issues/12502
