### ISSUE TITLE
Add Activate App endpoint

### ISSUE THREAD

**Issue by manoj9788** [appium/appium-dotnet-driver#360]
This issue is raised to track and maintain the dot-net-client on par with other language clients on API's. Hope to solve issues like
https://github.com/appium/appium-dotnet-driver/issues/335

Here are some of API's missing, feel free to pick and work on

- [ ] GET_PERFORMANCE_DATA
- [x] ACTIVATE_APP
- [ ] GET_DISPLAY_DENSITY
- [ ] GET_SYSTEM_BARS
- [ ] IS_KEYBOARD_SHOWN
- [ ] SEND_SMS
- [ ] GSM_CALL
- [ ] GSM_SIGNAL
- [ ] GSM_VOICE
- [ ] GET_ALLSESSION

Please feel free to suggest, if I've missed out any of the API's and will be glad to add it to this list.

**Comment by akinsolb** [comment]
Breaking this into multiple issues for each endpoint. Changing the scope of this issue to address the ACTIVATE_APP endpoint
