### ISSUE TITLE
ActivateApp is not calling activate_app but remove_app instead

### ISSUE THREAD

**Issue by broetchenrackete36** [appium/appium-dotnet-driver#372]
## Description

Using Activate App is not activating the App but removing it because of a wrong API-call (wrong endpoint).

## Environment

* .NET client build version or git revision if you use some shapshot: 4.1.0
* Appium server version or git revision if you use some shapshot:
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: android
* Real device or emulator/simulator:

## Details

Should be a simple fix.

**Comment by sunthrc19** [comment]
ACTIVATE_APP
