### ISSUE TITLE
SendKeys sends "ß" instead of "-"

### ISSUE THREAD

**Issue by ApolloCreek** [appium/appium-dotnet-driver#380]
## Description

While trying to send ",.-öä#ü+ß" SendKeys transmits ",.ßöä#ü+ß". Obviously the dash is replaced by a (German) "ß". I first got aware of the issue when I tried to send a regular Guid to the text box where all "-" were replaced by "ß". 
If the OS keyboard layout is switched to ENG, the "-" remains and the example works just fine. Btw: on a German keyboard "ß" is at the place where "-" is on an English one.

## Environment

- simple WPF application, .Net FW 4.6.1
- testing class library, xUnit, .Net FW 4.6.1
- Win10Pro (1909), German (OS language, keyboard layout)
- WinAppDriver 1.2.1910.2002
- Appium.WebDriver 4.1.1

![image](https://user-images.githubusercontent.com/6825692/70736346-6f2b1c80-1d10-11ea-9512-89dbf0bba1c3.png)

**Comment by akinsolb** [comment]
Can you provide server logs via gist?

**Comment by ApolloCreek** [comment]
Thank you Laolu for the quick response and sorry for bothering. 
It seems like this is rather a case for the [WinAppDriver guys](https://github.com/microsoft/WinAppDriver/issues/507#issue-368112811), who missed the point, that outside US most people do _not_ use an US keyboard layout. :-/
Unfortunately, that decreases this toolsets usabilty alot.

**Comment by akinsolb** [comment]
That's a shame
