### ISSUE TITLE
Location property under AppiumDriver should be exposed by an interface

### ISSUE THREAD

**Issue by gravity-api** [appium/appium-dotnet-driver#386]
The Location property under AppiumDriver class is currently part of the class and is not exposed by an interface. In order to use it I have to use AppiumDriver and in turn to use RemoteWebDriver and I cannot create my own implementation for this property.

Why is that a problem?

We are currently implementing a framework which is based on Selenium and Appium. We have a mock driver which we use to run our sanity tests.

Because some of the properties are not implemented by an interface, we must perform a check based on AppiumDriver class which means I cannot use my mock driver for some important mobile based actions.

Currently I am bypassing it by using different validation methods and some workarounds including reflection, to base my validation on property name and type - but this is a very "dirty" solution.

Exposing properties with interfaces will allow us to implement these interfaces on our mock framework and make a "clean" validation against the interface.

If possible we would be happy to join as contributors and do these kind of implementations for the community sake

**Comment by mykola-mokhnach** [comment]
@gravity-api Thanks for the suggestion

We are always happy to welcome new contributors. Simply create a PR and it will be merged as soon as we review it.

**Comment by mykola-mokhnach** [comment]
I could also send you an invite to our dev slack channel if you could provide your email address

**Comment by gravity-api** [comment]
gravity.api@outlook.com :)

**Comment by gravity-api** [comment]
will be updated on next version

**Comment by akinsolb** [comment]
@gravity-api will publish this on 31st January '20
