### ISSUE TITLE
Appium - webElement.Displayed return exception ("Method not implemented")

### ISSUE THREAD

**Issue by parwalrahul** [appium/appium-dotnet-driver#388]
## Description

 webElement.Displayed return exception ("Method not implemented")

## Environment

Nuget Package Version 3.0.0.2

## Details

![image](https://user-images.githubusercontent.com/12759282/72784597-2e97ba80-3c4f-11ea-8861-26dd5277d6c5.png)

**Comment by KazuCocoa** [comment]
What about 4.x?
https://github.com/appium/appium-dotnet-driver/blob/4928f79210b61c04b34d562b79955341bcb1dfe9/CHANGELOG.MD#4003-beta

**Comment by Dor-bl** [comment]
@akinsolb maybe something we should add to the docs?
