### ISSUE TITLE
Desktop Automated Test using ...WinAppDriver... Window 10

### ISSUE THREAD

**Issue by johnsajj** [appium/appium-dotnet-driver#394]
## The problem

I am using Windows 10 for running Appium Desktop Automated Test. I am trying to do the Calculator example the following code is give a null value as a public token:

this.Session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appCap);

How do I get the Token for appium-dotnet driver? Am I missing other dependencies to run Appium Driver?

## Environment

Windows 10
Microsoft.WinAppDriver...
Visual Studio 2019

## Details
the following error
Method 'Dispose' in type 'OpenQA.Selenium.Appium.Service.AppiumCommandExecutor' from assembly 'appium-dotnet-driver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

## Code To Reproduce Issue [ Good To Have ]

using OpenQA.Selenium.Appium.Windows;
using OpenQA.Selenium.Remote;

private const string WindowsApplicationDriverUrl = "http://127.0.0.1:4723";
private const string CalId = "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App";
public WindowsElement NotepadMainEditBox { get; private set; }
DesiredCapabilities appCap = new DesiredCapabilities();

[TestMethod]
[Obsolete]
public void LoginScreen_Example_Login()
{
	appCap.SetCapability("app", CalId);
	appCap.SetCapability("deviceName", "WindowsPC");

	try
	{
		this.Session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appCap);

		Assert.IsNotNull(Session);
				
	}
	catch (SystemException ex)
	{
	   var t = ex.Message;
	}

}

I am getting the following error:
Method 'Dispose' in type 'OpenQA.Selenium.Appium.Service.AppiumCommandExecutor' from assembly 'appium-dotnet-driver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by akinsolb** [comment]
@johnsajj Use the latest appium-dotnet-driver dll package from nuget?

**Comment by johnsajj** [comment]
Laolu Benson


Thank you for the quick response. I have downloaded Appium.WebDriver from nugget and revised the Test Method to the following:


[TestMethod]
  [Obsolete]
  public void LoginScreen_Example_Login()
  {
       AppiumOptions opt = new AppiumOptions();
       opt.AddAdditionalCapability("app", CalId);
       opt.AddAdditionalCapability("deviceName", "WindowsPC");
   try
   {

        Session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), opt);
        Assert.IsNotNull(Session);
   }
   catch (SystemException ex)
   {
       var t = ex.Message;
   }
  }


Issue is now it is getting hung up then stopping at this point:

                           Session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), opt);


Thank you for your assistance in  this matter


Amina Johnson, AR

Inserso Corporation


________________________________

**Comment by johnsajj** [comment]
Laolu Benson


Thank you for the quick response. I have downloaded Appium.WebDriver from nugget and revised the Test Method to the following:


[TestMethod]
  [Obsolete]
  public void LoginScreen_Example_Login()
  {
       AppiumOptions opt = new AppiumOptions();
       opt.AddAdditionalCapability("app", CalId);
       opt.AddAdditionalCapability("deviceName", "WindowsPC");
   try
   {

        Session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), opt);
        Assert.IsNotNull(Session);
   }
   catch (SystemException ex)
   {
       var t = ex.Message;
   }
  }


Issue is now it is getting hung up then stopping at this point:

                           Session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), opt);


Thank you for your assistance in  this matter


Amina Johnson, AR

Inserso Corporation

**Comment by akinsolb** [comment]
@johnsajj Can you provide the server logs in a [gist](https://gist.github.com)

**Comment by johnsajj** [comment]
Please see the following step down to try to resolve the issue:
1. Manual hit Appium via cmd  (Welcome to Appium)
2. Manual went to url "http://127.0.0.1:4723/wd/hub" (Edge) and couldn't reach
3. Download port listener and ran netstat -ano | findstr 4723
4. Port is Listening

Error Message when running the Test Method (Debug)
 Test method Public_ART.System.Dev._7_0_0.PosTests.LoginScreen_Example_Login threw exception: 
    OpenQA.Selenium.WebDriverException: Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:4723
       at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
       at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
       --- End of inner exception stack trace ---
       at OpenQA.Selenium.Appium.Service.AppiumCommandExecutor.Execute(Command commandToExecute)
       at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
  Stack Trace: 
    RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
    RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
    AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
    RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
    RemoteWebDriver.ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
    AppiumDriver`1.ctor(Uri remoteAddress, ICapabilities appiumOptions)
    WindowsDriver`1.ctor(Uri remoteAddress, AppiumOptions AppiumOptions)
    PosTests.LoginScreen_Example_Login() line 141

Const:
private const string WindowsApplicationDriverUrl = "http://127.0.0.1:4723/wd/hub";
private const string CalId = "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App";

Thank you for all your assistance with this issue

**Comment by akinsolb** [comment]
@johnsajj The above is of the stack trace & not the appium server log. How are you instantiating your appium server, & can you post the log from it?

**Comment by johnsajj** [comment]
Good Morning Laolu,


Thank you for the quick reply,


My apologies for not asking the right question. Is Appium Configuration similar to Selenium?


There is a High probability that the root cause is our configuration. Our Configuration is the Same as Selenium (below is the Process and a snippet of the Code Logic).


Selenium Process :

  1.  Download all Selenium Drivers from nugget via Visual Studio 2019
  2.  Reference the driver's needed to run the Automated Test (ex. using ...Selenium.Chrome)
  3.  In the Class call IWebdriver to spin up Selenium.Remote (ex. IWebdriver driver.Navigate(...))
  4.  Selenium spins up a Virtual server
  5.  The Automated Tests run Successfully


References:

using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;

Instantiation:

IWebDriver driver);

driver = new ChromeDriver();


Automated Test:

[TestMethod]
  public void LandingPage_Entry_HTTP()
  {
      baseUrl = "http://ar.dev.afcec-cloud.af.mil/";
      sendKeys.Add("_verifyEnTry");
      value = "url";
      layout.expected = "https://ar.dev.afcec-cloud.af.mil/";

     layout.lstElements.Add("url");

    actual = layout.Verify_LandingPageInfo(baseUrl, value, driver, sendKeys);

  }




Appium Process:


   Initialization

  private const string WindowsApplicationDriverUrl = "http://127.0.0.1:4723/wd/hub";
  private const string CalId = "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App";

   Session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), opt);


   Instantiation:


   AppiumOptions opt = new AppiumOptions();
   opt.AddAdditionalCapability("app", CalId);
   opt.AddAdditionalCapability("deviceName", "WindowsPC");


    References:



   using OpenQA.Selenium.Appium.Windows;
   using OpenQA.Selenium.Appium;
   using OpenQA.Selenium.Remote;


(Example from GitHub)

[TestMethod]
  [Obsolete]
  public void LoginScreen_Example_Login()
  {
      AppiumOptions opt = new AppiumOptions();
      opt.AddAdditionalCapability("app", CalId);
      opt.AddAdditionalCapability("deviceName", "WindowsPC");
   try
   {

        Session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), opt);
        Assert.IsNotNull(Session);
   }
   catch (SystemException ex)
   {
       var t = ex.Message;
   }
  }


There is no server logs, the Automated Tests are running from a Laptop using Selenium Drivers.



Please let me know if I am misunderstanding you question.


Amina Johnson, AR

.Net Developer

Contractor, AFCEC/FMO

Inserso Corporation


________________________________

**Comment by akinsolb** [comment]
Hi @johnsajj I believe confusion lies within 'step 4.  Selenium spins up a Virtual server.' Selenium does not do this for Appium. You can do so by either using the ```AppiumLocalService``` class like so in your setup method:
```
var appiumServer = new AppiumServiceBuilder().Build();
appiumServer.Start();
```

and disposing it with ```appiumServer.Dispose()```

Alternatively, you can spin up an appium server manually on your test host machine by following the 'Installing Appium' & 'Starting Appium' section described [here](http://appium.io/docs/en/about-appium/getting-started/?lang=en)

I have created a [gist](https://gist.github.com/akinsolb/838b8402ee7db6abc32871d3849fae84) of an example extacting the [windows click element test](https://github.com/appium/appium-dotnet-driver/blob/master/test/integration/Windows/ClickElementTest.cs)

**Comment by johnsajj** [comment]
Good Morning,


Thank you for the quick response and confirming the root cause. The Resolution will be relayed to the Manager' of the Project  for the next steps.


I will log on and Close the Ticket.


Thank you for all your assistance in this matter,


Amina Johnson, AR

.Net Developer

Contractor, AFCEC/FMO

Inserso Corporation


________________________________
