### ISSUE TITLE
System.TypeLoadException : Access is denied: 'OpenQA.Selenium.Remote.DesiredCapabilities'.

### ISSUE THREAD

**Issue by nadvolod** [appium/appium-dotnet-driver#402]
## The problem

I am trying to run Appium tests using AppiumOptions() and I keep getting the following error `System.TypeLoadException : Access is denied: 'OpenQA.Selenium.Remote.DesiredCapabilities'.` in my C# tests.
[You can try this test as an example
](https://github.com/saucelabs-training/demo-csharp/blob/master/SauceExamples/DotnetFramework/Appium/Appium4.NUnit.Scripts/RealDevices/NativeApp/AndroidGetStarted.cs)
## Environment

* Appium version (or git revision) that exhibits the issue: 4.1.1
* Desktop OS/version used to run Appium: Windows 10

## Details

Stack trace from Visual Studio
```
Stack Trace: 
    AppiumOptions.ctor()
    AndroidGetStarted.ShouldOpenApp() line 29
```

## Code To Reproduce Issue [ Good To Have ]

[You can try this test as an example
](https://github.com/saucelabs-training/demo-csharp/blob/master/SauceExamples/DotnetFramework/Appium/Appium4.NUnit.Scripts/RealDevices/NativeApp/AndroidGetStarted.cs)

**Comment by imurchie** [comment]
See https://github.com/appium/appium-dotnet-driver/issues/333

**Comment by nadvolod** [comment]
Switching to Selenium version 3.141.0 worked, thanks @imurchie 👍

**Comment by MPNistal** [comment]
Hello everyone, I also still get the same error even when Selenium Webdriver and Support Packages are in version 3.141.0
![image](https://user-images.githubusercontent.com/52284489/123371235-eacb8200-d5b3-11eb-99ca-9c1a4d69886f.png)

Debug Error + Code Snippet:
![image](https://user-images.githubusercontent.com/52284489/123371265-0040ac00-d5b4-11eb-8ab0-3df1d83924af.png)

Hope someone could take a look and shed light. Thanks!

**Comment by ManikandanMani** [comment]
Hi everyone, I get this same error  in appium options when I use selenium version 4.1.0 , could you let us know how to resolve this error when selenium version 4.1.0 is used ?

**Comment by albert-asin** [comment]
Hi
Here the same problem with Appium.WebDriver 4.3.1

**Comment by prashelke** [comment]
I am also facing same issue

**Comment by alexlazarciuc** [comment]
Same issue when updating to Selenium 4.1.0

**Comment by Honey250690** [comment]
Hi everyone, I get this same error in appium options when I use selenium version 4.1.0 , could you let us know how to resolve this error when selenium version 4.1.0 is used along with appium.dotnet driver package 4.3.1, is there any way to resolve this ?

**Comment by TimothyKhouri** [comment]
yup, same issue as everyone else. I'm guessing that this is years of being ignored that it'll continue to be ignored.

**Comment by mykola-mokhnach** [comment]
> yup, same issue as everyone else. I'm guessing that this is years of being ignored that it'll continue to be ignored.

Sorry we made you feel that way @TimothyKhouri
The Appium team has been experiencing lack of resources to maintain this particular client for quite long period of time. We are happy to welcome new volunteers.

**Comment by timothyjwhite** [comment]
I thought the goal of Selenium was any language? Clearly this issue was entered into the code over 4 years ago, why hasn't someone fixed it.? I guess that is also why the appium inspector does not have the option to generate code in C#. This is a blocking issue for me. My company has C# developers and we need to get testing going with this as we are trying to see if we can get better speed and scalability with this option then we have with our current tool. Being blocked by this could end this effort altogether.

**Comment by mykola-mokhnach** [comment]
> I thought the goal of Selenium was any language? Clearly this issue was entered into the code over 4 years ago, why hasn't someone fixed it.? I guess that is also why the appium inspector does not have the option to generate code in C#. This is a blocking issue for me. My company has C# developers and we need to get testing going with this as we are trying to see if we can get better speed and scalability with this option then we have with our current tool. Being blocked by this could end this effort altogether.

Sorry to hear that. Opensource simply does not work like that. If nobody fixes the issue then, most likely, people don't need this fix as much. Unfortunately we don't have anyone who is constantly maintaining this client. If anyone from your team wants to improve C# bindings then just let us know.

**Comment by timothyjwhite** [comment]
The issue isn't one about finding a control or interacting with one, this problem prevents connecting to the device to be tested. This is the main point of automated testing. you can do nothing if you can't connect to the device. , 

Second while we have c# developers we don't have selenium experts, so we have no one who could delve into this problem to correct it.

**Comment by alexlazarciuc** [comment]
Hi @timothyjwhite - after updating the appium to the beta (you can chose in your nuget pre-release option) https://github.com/appium/appium-dotnet-driver/tree/release/5.0.0 and selenium to latest version everything works fine on my end. Are you running against the cloud or locally?

**Comment by timothyjwhite** [comment]
Disregard last comment, it was the AutoWebview option that caused the problem. i have been able to connect to my device, and interact with it thank you for the help. Much Appreciated.

**Comment by alexlazarciuc** [comment]
@timothyjwhite I use mine in this way:
var opt = new AppiumOptions()
   opt.DeviceName = deviceName;
   opt.PlatformName = platformName;
    opt.PlatformVersion = platformVersion;
    opt.AcceptInsecureCertificates = true;

For the cloud:  options.AddAdditionalOption("bstack:options", browserstackOptions);
in browserstackOptions building the options the cloud provider expects

**Comment by alexlazarciuc** [comment]
@timothyjwhite  - Yes checking the code history I see I had to remove that one as well. Glad you are sorted.

**Comment by timothyjwhite** [comment]
One additional question:

Appium inspector shows an id for the control that I want to click. When I try to find the element By.Id it can't find it, but using the xPath option works. Is there something special I need to do:

AppiumElement el1 = driver.FindElement(By.Id("main_menu-button-open"));

The id value was copied from Appium inspector directly.

**Comment by jlipps** [comment]
You could try including your fully specified package id before the id, like `packageid:id`

**Comment by timothyjwhite** [comment]
I tried this (the commented line works the top one yields  the error message below:

AppiumElement el1 = driver.FindElement(By.Id("InstrumentDemoSystemMonitor-debug:id/login-button-open_img"));
            //AppiumElement el1 = driver.FindElement(By.XPath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.ViewSwitcher/android.widget.FrameLayout/android.webkit.WebView/android.webkit.WebView/android.view.View[2]/android.view.View/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[3]"));


Error message:
OpenQA.Selenium.NoSuchElementException: An element could not be located on the page using the given search parameters.

**Comment by PeterExtrapreneur** [comment]
> @timothyjwhite I use mine in this way: var opt = new AppiumOptions() opt.DeviceName = deviceName; opt.PlatformName = platformName; opt.PlatformVersion = platformVersion; opt.AcceptInsecureCertificates = true;
> 
> For the cloud: options.AddAdditionalOption("bstack:options", browserstackOptions); in browserstackOptions building the options the cloud provider expects

How did you manage to make it work? Are you testing Windows-Apps? Selenium 4+ is not working for me? Using remotewebdriver. 

Example:
            AppiumOptions appiumOptions = new AppiumOptions();
            appiumOptions.AddAdditionalCapability("app", AppIdentifier);
            appiumOptions.AddAdditionalCapability("deviceName", "WindowsPC");
            appiumOptions.AddAdditionalCapability("ms:waitForAppLaunch", 1);
            
            Driver = new WindowsDriver<RemoteWebElement>(new Uri("http://127.0.0.1:4723"), appiumOptions);

**Comment by Dor-bl** [comment]
@PeterExtrapreneur, Please refrain from responding to old closed issues. 
If you have an issue, please open a new one.
