### ISSUE TITLE
AppiumServiceBuilder .AddCapabilities() causes timeout

### ISSUE THREAD

**Issue by mcopjan** [appium/appium-dotnet-driver#405]
Appium Webdriver 4.1.1

I am trying to start Appium service with **default capability** 'derivedDataPath'. When I take AppiumServiceBuilder arguments before calling Start() and run the same from terminal, appium starts without any problems, but if I start the service via service.Start(), it will timeout. The same code snippet works fine without .AddCapabilities(driverOptions))

The documentation on this topic also seems to be very outdated https://github.com/appium/appium-dotnet-driver/wiki/How-to-start-an-AppiumDriver-locally

```
AppiumServiceBuilder appiumService = new AppiumServiceBuilder();
var logPath = Path.Combine(Path.Combine(home, $"{simulator.Udid}.log"));
var nodeConfigJsonPath = Path.Combine(home, $"{simulator.Udid}.json");
var guid = Guid.NewGuid();
var derivedDataPath = Path.Combine(home, $"Library/Developer/Xcode/DerivedData/WebDriverAgent-{guid}");
var driverOptions = new AppiumOptions();
driverOptions.AddAdditionalCapability("derivedDataPath", derivedDataPath);

var service = appiumService
                            .UsingAnyFreePort()
                            .WithIPAddress(hostIP)
                            .WithArguments(new OptionCollector()
                            .AddArguments(new KeyValuePair<string, string>("-U", $"{simulator.Udid}"))
                            .AddArguments(new KeyValuePair<string, string>("--webdriveragent-port", $"{webdriveragentPort}"))
                            .AddArguments(new KeyValuePair<string, string>("--nodeconfig", $"{nodeConfigJsonPath}"))
                            .AddArguments(new KeyValuePair<string, string>("--log-level", $"error:{logLevel}"))
                            .AddCapabilities(driverOptions))
                            .WithLogFile(new FileInfo(logPath))
                            .Build();
                service.Start();
```

OpenQA.Selenium.Appium.Service.Exceptions.AppiumServerHasNotBeenStartedLocallyException: "The local appium server has not been started. The given Node.js executable: /usr/local/bin/node Arguments: \"/usr/local/lib/node_modules/appium/build/lib/main.js\" --port \"60011\" --address \"**********\" --log \"/Users/*******/8EC7CD44-BE9F-44DE-AB85-64CC6B12C12D.log\" -U 8EC7CD44-BE9F-44DE-AB85-64CC6B12C12D --webdriveragent-port 8100 --nodeconfig /Users/martinco/8EC7CD44-BE9F-44DE-AB85-64CC6B12C12D.json --log-level error:debug **--default-capabilities '{\"derivedDataPath\": \"/Users/********/Library/Developer/Xcode/DerivedData/WebDriverAgent-e4a6a726-6aa1-4335-9655-46228dd56668\"}'**. \nTime 120000 ms for the service starting has been expired!"
  at OpenQA.Selenium.Appium.Service.AppiumLocalService.Start()\n 

The above command executed from Terminal causes no problems
```
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   derivedDataPath: /Users/martinco/Library/Developer/Xcode/DerivedData/WebDriverAgent-e4a6a726-6aa1-4335-9655-46228dd56668
[Appium]   udid: 8EC7CD44-BE9F-44DE-AB85-64CC6B12C12D
```

Please advise.

**Comment by mcopjan** [comment]
Workaround is to use AddArguments() and the following escape sequence 
```
var derivedDataPath = {your path}

builder.AddArguments(new KeyValuePair<string, string>("--default-capabilities", $"\"{{\\\"derivedDataPath\\\": \\\"{derivedDataPath}\\\"}}\"")))
```

**Comment by Dor-bl** [comment]
@mcopjan did you tried the above on the latest version?
