### ISSUE TITLE
Using Driver.Location() throws System.InvalidCastException: 

### ISSUE THREAD

**Issue by derekgrant12** [appium/appium-dotnet-driver#412]
## Description
When running a test on a real samsung S9 Device, and executing Driver.Location(); the code throws an exception. but in the appium logs i can see the location is returned without issue
## Environment

* .NET client build version or git revision if you use some shapshot:.netcoreapp3.1
* Appium server version or git revision if you use some shapshot:1.17.1
* Desktop OS/version used to run Appium if necessary:Mac
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test:Android 9.0 
* Real device or emulator/simulator:Real device Samsung S9
* Ussing Appium webdriver 4.1.1
## Details

Running test to get Location from phone.  i can see appium log returning correct value.
i think this issue was shown and fixed before as parsing issue.

## Exception stacktraces

https://gist.github.com/derekgrant12/b1a3684df2b02dcf27dc5410d8c3bd60

## Link to Appium logs
https://gist.github.com/derekgrant12/81b8f4f16ccff603eae6797fc5cc95b9

**Comment by akinsolb** [comment]
Interesting. I actually have an S9 Test device. I’ll check it out tonight if someone doesn’t get there before me

**Comment by derekgrant12** [comment]
yeh would be great if you checked to confirm you're having same issue

**Comment by akinsolb** [comment]
I couldn’t reproduce this, and I have the same versions of appointments and Android on my device. Interestingly, I couldn’t find where a dictionary would be cast to a string.

Can you supply your code statements for reproduction?

**Comment by akinsolb** [comment]
resolved by #306
