### ISSUE TITLE
Driver is really slow when used with .netcore instead of .netframework

### ISSUE THREAD

**Issue by broetchenrackete36** [appium/appium-dotnet-driver#414]
## Description

While I was refactoring my mobile test suite, I wanted to give .NET Core a go. Everything worked fine, until I noticed, that my Tests were running much longer than usual. So I created a quick comparison-project and noticed, that the Appium.WebDriver is really slow when used with .NET Core 3.1. The commands on the appium-server are just as quick as normally, but the time between commands is way higher.

## Environment

* .NET client build version or git revision if you use some shapshot: 4.1.1
* Appium server version or git revision if you use some shapshot: 1.16.0
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 13.0.1
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Emulator

## Details
To reproduce the issue I created a little Project with the same Test-Run (as a console-app, so no dependencies except appium) that measures getting the height of all Elements of the Android Settings app.

With .NET Core it takes around a second longer than with .NET Framework for each element. See the two outputs and the project below

## Code To Reproduce Issue [ Good To Have ]

[Speed Measurement with .NET Core 3.1](https://gist.github.com/broetchenrackete36/a22f448c232df2e760be80cf730c0046)
[Speed Measurement with .NET Framework 4.7.2](https://gist.github.com/broetchenrackete36/06502a2b78ada8ffeb0d6ab57dd76b42)
[Speed-comparison project](https://github.com/broetchenrackete36/appium-dotnet-speed-comparison)

## Additional Information
I also tried to compile the Appium.WebDriver as a .NETCore package but it didn't improve the speed. I have the feeling it could be related to selenium itself.

**Comment by TroyWalshProf** [comment]
@broetchenrackete36  - Would you happen to be using localhost?
If so this maybe the issue: https://github.com/dotnet/runtime/issues/23581#issuecomment-354391321

**Comment by broetchenrackete36** [comment]
Interesting, will test with ip address in the morning, I am indeed using localhost in my comparison-test.
I first noticed the issue on my jenkins where I'm connecting to a selenium grid... Which runs on the same jenkins as the dotnet tests...
So yes, this could very well be the problem I'm experiencing, I'll confirm it tomorrow and will close the issue if it is. Nice find.

**Comment by broetchenrackete36** [comment]
Sorry for the delay.

Yes, the issue lies within dotnet itself.
