### ISSUE TITLE
Its displaying Object ref not found when i used the below code, can any one help me on this appium c# code

### ISSUE THREAD

**Issue by vishnuprakash9845** [appium/appium-dotnet-driver#439]
## Description

I a have a native application supported in both android and IOS platform. I am trying to build a common code to automate the on both the IOS and Android platform. When tried to debug the code getting the **Object ref not set to the instance of variable** for UserNameField. 

Weather the following code works for identifying both the IOS and android with single property or not or am i missing anything, can anyone please help me out. Here's the code

public class TestApplication
    {
        private AppiumDriver<AppiumWebElement> _appiumDriver;

        public TestApplication(AppiumDriver<AppiumWebElement> driver)
        {
            _appiumDriver = driver;
            PageFactory.InitElements(_appiumDriver, this);
        }
        
        [FindsByIOSUIAutomation(Accessibility = "userName")]
        [FindsByAndroidUIAutomator(Accessibility = "un")]
        **_public AppiumWebElement UserNameField { get; set; }_**

        [FindsByIOSUIAutomation(Accessibility = "password")]
        [FindsByAndroidUIAutomator(Accessibility = "pw")]
        public AppiumWebElement PasswordField{ get; set; }       
    }

**Can anyone help me the sample C# Appium code for mobile automation**

## Environment

Appium version (or git revision) that exhibits the issue: 1.91.
Last Appium version that did not exhibit the issue (if applicable): All it exibited
Desktop OS/version used to run Appium: Mac Cataline windows 10
Node.js version (unless using Appium.app|exe):
Npm or Yarn package manager:
Mobile platform/version under test: 9
Real device or emulator/simulator: Real Android device

After all the environment setup and resolving errors, i feel Mobile automation is bit challenging and not difficult using C#. I am learning and practicing hard to master it.

**Comment by anunay1** [comment]
the above exception is thrown because the driver ie never initialized, use the new keyboard to initialize the driver

**Comment by vishnuprakash9845** [comment]
> the above exception is thrown because the driver ie never initialized, use the new keyboard to initialize the driver

Thank you @anunay1  Is there any github repo, so that I can refer the code(Appium with c#).

**Comment by Dor-bl** [comment]
@vishnuprakash9845 I'm closing this issue in case you still need help with some examples please refer to our [tests Integration project](https://github.com/appium/appium-dotnet-driver/tree/release/5.0.0/test/integration)
