### ISSUE TITLE
Null when try get time .DeviseTime

### ISSUE THREAD

**Issue by grishukov** [appium/appium-dotnet-driver#440]
## Description

Something wrong with DeviseTime(); in 4.2.1
## Environment
.net 472; Appium server 1.17.1, Appium client 4.2.1; Android on real device and emulator; Selenium 3.141

## Details
 it works ok on 4.1.1
```csharp       
var actualDeviceTimeRaw = Driver.DeviceTime;
string parsedDeviceTime = DateTime.Parse(actualDeviceTimeRaw).ToString("h:mm tt");
           
```

But 
 in  4.2.1 get null ref exeption
## Exception stacktraces

  [gist](https://gist.github.com/grishukov/d4dfc34fa33e592a13791c21edc50d0a)

**Comment by akinsolb** [comment]
@grishukov Do you recall which driver you were using?

**Comment by grishukov** [comment]
> @grishukov Do you recall which driver type you were using?

it was Android UIAutomator2 and still reproduce on 4.3.0

**Comment by akinsolb** [comment]
Thanks @grishukov I'll get a pr out for it today

**Comment by akinsolb** [comment]
On its way out
