### ISSUE TITLE
set w3c chromeoptions error

### ISSUE THREAD

**Issue by ArmyMedalMei** [appium/appium-dotnet-driver#451]
## Description

Unhandled exception. OpenQA.Selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: invalid argument: cannot parse capability: goog:chromeOptions

## Environment

* .NET client build version or git revision if you use some shapshot:.NET
* Appium server version or git revision if you use some shapshot:Appium 1.18,1
* Desktop OS/version used to run Appium if necessary:Desktop OS
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:Appium.exe
* Mobile platform/version under test:Android
* Real device or emulator/simulator:simulator

## Details

Apium uses chromeoptions to report an error. I want to set W3C to false, because I can't find the element by using driver.FindElementById, but I can find it by using appium desktop program. Comparing the two parameters is because the default W3C value of this parameter is true in. Net

## Code To Reproduce Issue [ Good To Have ]

var chromeOptions = new ChromeOptions {UseSpecCompliantProtocol = false};
            var appiumOptions = new AppiumOptions();
            appiumOptions.AddAdditionalCapability(MobileCapabilityType.PlatformName, MobilePlatform.Android);
            appiumOptions.AddAdditionalCapability(MobileCapabilityType.DeviceName, "模拟器");
            appiumOptions.AddAdditionalCapability(MobileCapabilityType.NewCommandTimeout, 24 * 5 * 60 * 60);
            appiumOptions.AddAdditionalCapability(MobileCapabilityType.Udid, "emulator-5554");
            appiumOptions.AddAdditionalCapability(AndroidMobileCapabilityType.UnicodeKeyboard, true);
            appiumOptions.AddAdditionalCapability(AndroidMobileCapabilityType.ChromeOptions, chromeOptions);

try
            {
                driver.Navigate().GoToUrl("https://m.baidu.com");

                driver.Context = "CHROMIUM";

                Console.WriteLine(driver.Context);

                Thread.Sleep(TimeSpan.FromSeconds(12));

                var indexKw = driver.FindElementById("index-kw");

                Thread.Sleep(TimeSpan.FromSeconds(new Random().Next(2, 3)));

                driver.PressKeyCode(AndroidKeyCode.Enter);

          }
          catch (Exception e)
          {
              Log.Warning("未能找到“百度首页输入框元素”");
          }

## Appium Desktop Log
[HTTP] 
[HTTP] --> POST /wd/hub/session/5cebd82b-9428-4fd1-9ad3-b3c4f54cbddb/element
[HTTP] {"using":"id","value":"index-kw"}
[W3C (5cebd82b)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/5cebd82b-9428-4fd1-9ad3-b3c4f54cbddb/element' to command name 'findElement'
[WD Proxy] Proxying [POST /wd/hub/session/5cebd82b-9428-4fd1-9ad3-b3c4f54cbddb/element] to [POST http://127.0.0.1:8022/wd/hub/session/3e5590e010bf8ba00a087b4ac5389c63/element] with body: {"using":"id","value":"index-kw"}
[WD Proxy] Got response with status 400: {"value":{"error":"invalid argument","message":"invalid argument: invalid locator\n  (Session info: chrome=86.0.4240.110)","stacktrace":"Backtrace:\n\tOrdinal0 [0x0080C013+3194899]\n\tOrdinal0 [0x006F6021+2056225]\n\tOrdinal0 [0x0058F608+587272]\n\tOrdinal0 [0x0051B796+112534]\n\tOrdinal0 [0x0053B182+242050]\n\tOrdinal0 [0x0052FDAA+196010]\n\tOrdinal0 [0x00539B22+236322]\n\tOrdinal0 [0x0052FC1B+195611]\n\tOrdinal0 [0x00513B7F+80767]\n\tOrdinal0 [0x00514B4E+84814]\n\tOrdinal0 [0x00514AD9+84697]\n\tOrdinal0 [0x0070CE64+2149988]\n\tGetHandleVerifier [0x0097BE95+1400773]\n\tGetHandleVerifier [0x0097BB61+1399953]\n\tGetHandleVerifier [0x009831FA+1430314]\n\tGetHandleVerifier [0x0097C69F+1402831]\n\tOrdinal0 [0x00703D61+2112865]\n\tOrdinal0 [0x0070E5CB+2155979]\n\tOrdinal0 [0x0070E6F5+2156277]\n\tOrdinal0 [0x0071F26E+2224750]\n\tBaseThreadInitThunk [0x77216359+25]\n\tRtlGetAppContainerNamedObjectPath [0x77938944+228]\n\tRtlGetAppContainerNamedObjectPath [0x77938914+180]\n"}}
[W3C] Matched W3C error code 'invalid argument' to InvalidArgumentError
[HTTP] <-- POST /wd/hub/session/5cebd82b-9428-4fd1-9ad3-b3c4f54cbddb/element 400 14 ms - 983

**Comment by KazuCocoa** [comment]
appium-dotnet-driver usage?

**Comment by ArmyMedalMei** [comment]
@KazuCocoa，No, this is an error. I tried to solve this problem in the lower version of chrome 37.0.2062.117, but in the higher version of chrome, there will be this problem, for example: 86.0.4240.22. I saw that W3C specification will be used after some versions, but the higher version can't pass findelementbyid after it is set to true by default Method, for example, open M baidu.com Through the element review, the ID of the input box is indeed index kW, as I mentioned above, can it be tested?

**Comment by KazuCocoa** [comment]
Sorry, probably I confused.

I thought the issue was `chromeOptions`'s format from .NET client to the chromedriver as below description.

> Unhandled exception. OpenQA.Selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: invalid argument: cannot parse capability: goog:chromeOptions

But

> but the higher version can't pass findelementbyid after it is set to true by default Method

so, it meant some find element location strategies like `id` did not work when `w3c` mode in chromedriver.

Then, it is expected because W3C does not support some location strategies. It supports only https://www.w3.org/TR/webdriver1/#locator-strategies `id`, `tag name`, `class name` and `name` should be `css selector` or another available selector in W3C for chromedriver.

**Comment by ArmyMedalMei** [comment]
Thank you. If W3C is not set to false, there will be no way to find a unique element. What should I do?

**Comment by ArmyMedalMei** [comment]
·

> Sorry, probably I confused.
> 
> I thought the issue was `chromeOptions`'s format from .NET client to the chromedriver as below description.
> 
> > Unhandled exception. OpenQA.Selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: invalid argument: cannot parse capability: goog:chromeOptions
> 
> But
> 
> > but the higher version can't pass findelementbyid after it is set to true by default Method
> 
> so, it meant some find element location strategies like `id` did not work when `w3c` mode in chromedriver.
> 
> Then, it is expected because W3C does not support some location strategies. It supports only https://www.w3.org/TR/webdriver1/#locator-strategies `id`, `tag name`, `class name` and `name` should be `css selector` or another available selector in W3C for chromedriver.

Thank you. If W3C is not set to false, there will be no way to find a unique element. What should I do?

**Comment by KazuCocoa** [comment]
You should find another location strategizes.
For example, selenium clients convert them as `css selector`. Appium clients disable the conversion, but you an do the same thing via css selector.
https://github.com/SeleniumHQ/selenium/blob/104b2782858fc190987e799f2feb55b9b3ac8861/py/selenium/webdriver/remote/webdriver.py#L1156-L1167

**Comment by ArmyMedalMei** [comment]
Thank you very much for your reply. I try to find elements in other ways
