### ISSUE TITLE
'Selenium.Support 3.141.0' is not compatible with '********constraint: Selenium.Support (>= 4.0.0-alpha05)'

### ISSUE THREAD

**Issue by kmx0101** [appium/appium-dotnet-driver#454]
Installing a nuget package that is Selenium 4 (alpha)- based  was not compatible with Appium 4.3.1

Framework: .NET Framework 4.7.2
Appium version: 4.3.1
MS Test Unit

**Getting error:**
![image](https://user-images.githubusercontent.com/23139484/107913836-1b633580-6f9c-11eb-8d90-c48302ae08c9.png)

**Comment by akinsolb** [comment]
This will be because thus library doesn't support selenium v4-x. The nuget package specifies that. Also we don't integrate alpha or beta dependencies
