### ISSUE TITLE
c# imageelement GetAttribute("visual") retturn System.Collections.Generic.Dictionary`2[System.String,System.Object]

### ISSUE THREAD

**Issue by atimofeev86** [appium/appium-dotnet-driver#461]
## The problem

I use method FindElementsByImage, it return not similar elements and I want to debug process.
I change settings 
driver.SetSetting("getMatchedImageResult", true);
driver.SetSetting("imageMatchThreshold", 0.5); 
but when I try use he_col.First().GetAttribute("visual") I get string "System.Collections.Generic.Dictionary`2[System.String,System.Object]"

## Environment

* Appium version 1.21.0
* Desktop OS/version windows 10
* Node.js version 14.16.0
* Mobile platform/version Android 11
* Real device xiaomi

**Comment by KazuCocoa** [comment]
Could you share the appium server log as well?

**Comment by atimofeev86** [comment]
as you can seein log good data, but in visual studio not good
![Снимок](https://user-images.githubusercontent.com/41478386/126897361-6ca9af73-47af-4374-b165-6f8b0eb43521.PNG)

**Comment by mykola-mokhnach** [comment]
This was fixed in appium@beta: https://github.com/appium/appium-base-driver/pull/489
