### ISSUE TITLE
ComparisonResult.SaveVisualizationAsFile throws FormatException 

### ISSUE THREAD

**Issue by omghb** [appium/appium-dotnet-driver#463]
Appium: 1.21.0
Appium.Net: 4.2.1
For: iOS

The method `ComparisonResult.SaveVisualizationAsFile` throws `FormatException` because the input `Visualization` property is not a valid Base-64 string.

https://github.com/appium/appium-dotnet-driver/blob/4570d11267572b861554142d39d4452d853e6118/src/Appium.Net/Appium/ImageComparison/ComparisonResult.cs#L24

The 'Visualization' property contains a `Dictionary<string, object>` with two entries `type` and `data`. See Debugger screenshot:

![AppiumIssue](https://user-images.githubusercontent.com/47421673/131490611-654bbcc9-7802-4df5-ba18-beb78be69998.png)

The `Visualization` property calls `Result["visualization"]` which results now in another Dictionary instead of the data. This needs to be changed.

https://github.com/appium/appium-dotnet-driver/blob/4570d11267572b861554142d39d4452d853e6118/src/Appium.Net/Appium/ImageComparison/ComparisonResult.cs#L13

**Comment by omghb** [comment]
Workaround unit this issue is fixed:

```C#
using OpenQA.Selenium.Appium.ImageComparison;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

namespace AppiumWrapper
{
    public static class ComparisonResultHelper
    {
        // Workaround for https://github.com/appium/appium-dotnet-driver/issues/463
        public static void FixedSaveVisualizationAsFile(this ComparisonResult comparisonResult, string fileName)
        {
            var resultProperty = typeof(ComparisonResult).GetProperty("Result", BindingFlags.Instance | BindingFlags.NonPublic);
            var result = (Dictionary<string, object>)resultProperty.GetValue(comparisonResult);
            var visualization = result["visualization"];
            var x = visualization is Dictionary<string, object> dict ? ((object[])dict["data"]).Select(y => (byte)((long)y)).ToArray() : Convert.FromBase64String(visualization.ToString());
            File.WriteAllBytes(fileName, x);
        }
    }
}
```

**Comment by Dor-bl** [comment]
@omghb Can we close this issue? 
Or something needed to be done on the client side?

**Comment by akinsolb** [comment]
@Dor-bl I think this is a bug, since reflection is used above. We probably need the iOS version..because I don't see when the type for `Visualisation` type change from a `String` to `Dictionary<string, object>`.. or whether this was always the case

**Comment by mykola-mokhnach** [comment]
It was once a bug on the server side. The expected type should be String (a base-64 encoded PNG image represented as a string).

Ask users to keep their server up to date

**Comment by akinsolb** [comment]
> It was once a bug on the server side. The expected type should be String (a base-64 encoded PNG image represented as a string).
> 
> 
> 
> Ask users to keep their server up to date

Nice. Thank you @mykola-mokhnach
