### ISSUE TITLE
Perform double click on WPF application

### ISSUE THREAD

**Issue by Xiphereal** [appium/appium-dotnet-driver#464]
## Description
I'm testing a WPF application with Appium and WinAppDriver.
When I try to use `Actions` for performing a double click over an element, a `WebDriverException` with the message "Currently only pen and touch pointer input source types are supported" occurs.

I've also tried the solution from https://github.com/microsoft/WinAppDriver/issues/344 or https://github.com/microsoft/WinAppDriver/issues/114, but in this case a `NullReferenceException` is risen instead.

Any ideas?

Thanks in advance :)

## Environment

* .NET client build version or git revision if you use some shapshot: 4.3.1
* Appium server version or git revision if you use some shapshot: 1.21.0
* Desktop OS/version used to run Appium if necessary: Microsoft Windows Server 2019 Standard
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: Using Appium main.js

**Comment by KazuCocoa** [comment]
Could you share the appium log?

I guess your client send actions as `keys` in `input source` section http://appium.io/docs/en/commands/interactions/actions/
i don't know your client code, but in Ruby, it can specify with `add_pointer_input`. Java is `PointerInput`. They depend on your client code.

**Comment by KazuCocoa** [comment]
oh, sorry this is dotnet repo.

**Comment by KazuCocoa** [comment]
I guess you can do it with `var inputDevice = new PointerInputDevice(PointerKind.Touch);` in http://appium.io/docs/en/commands/interactions/actions/ as "touch" action

**Comment by Xiphereal** [comment]
> 
> 
> I guess you can do it with `var inputDevice = new PointerInputDevice(PointerKind.Touch);` in http://appium.io/docs/en/commands/interactions/actions/ as "touch" action

Thanks! This seems to work with a few adjustments. Anyway, the most desirable way of doing it would be with the mouse as input device. Any idea on how to do it? Or why is the mouse now supported as an input device for Windows applications with WinAppDriver?

**Comment by mykola-mokhnach** [comment]
It's rather a question to the Microsoft team, which develops this driver

**Comment by KazuCocoa** [comment]
Yes, as mykola comments, the behavior is by MS team. I believe microsoft/WinAppDriver#1584 should be the proper place in such a question.
