### ISSUE TITLE
Jetpack Compose support

### ISSUE THREAD

**Issue by gosr** [appium/appium-dotnet-driver#482]
There is not yet support for locating Android elements that are built via Jetpack Compose.
There is an open issue on the Appium github: https://github.com/appium/appium/issues/15138

I'm not sure if this repo needs a separate issue for this to have it supported in the .net driver -- if not, please feel free to close this issue.

**Comment by iparry7979** [comment]
Does this mean that we can't locate jetpack compose elements if we are using the c# client?

**Comment by KazuCocoa** [comment]
No. It means the support does not require appoum client side code change. You can follow https://github.com/appium/appium-espresso-driver#jetpack-compose-support to test compose components via proper version’s espresso driver.
(the version is available via appoum beta or 2.0)
