### ISSUE TITLE
Deprecate TouchAction and MultiTouchAction

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-dotnet-driver#484]
## Description

https://github.com/appium/appium/issues/16009

## Details

We'd like to deprecate old touch actions endpoints.
maybe https://github.com/appium/appium-dotnet-driver/blob/4570d11267572b861554142d39d4452d853e6118/src/Appium.Net/Appium/MultiAction/MultiAction.cs and https://github.com/appium/appium-dotnet-driver/blob/4570d11267572b861554142d39d4452d853e6118/src/Appium.Net/Appium/MultiAction/TouchAction.cs ?

**Comment by Dor-bl** [comment]
@akinsolb did we deprecated the above? or it's something we need to do.

**Comment by Dor-bl** [comment]
@KazuCocoa https://github.com/appium/appium-dotnet-driver/pull/548 should address this
