### ISSUE TITLE
CHANGELOG.md has no entry for 5.0.0

### ISSUE THREAD

**Issue by bruno-garcia** [appium/appium-dotnet-driver#485]
GitHub release notes has information but not the changelog file in the repository root.

Is there a plan to update the CHANGELOG.md file or deprecated it?

**Comment by Dor-bl** [comment]
@bruno-garcia please share a sample of your code usage and I'll try to assist

**Comment by Dor-bl** [comment]
@akinsolb we added entry for 5.0.0. So I think we can close this issue
