### ISSUE TITLE
Unable to use fullReset capability

### ISSUE THREAD

**Issue by iparry7979** [appium/appium-dotnet-driver#491]
## Description

Application capability and fullReset capability don't seem to be working in conjunction with each other

## Environment

* .NET client build version or git revision if you use some shapshot: Appium WebDriver 5.0.0-beta01
* Appium server version or git revision if you use some shapshot: Appium Server version 1.22.0
* Desktop OS/version used to run Appium if necessary: Windows 10
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: Node.js 12.8.1
* Mobile platform/version under test: Android 11
* Real device or emulator/simulator: Emulator

## Details

When setting the fullReset capabilty, I get an error message when instantiating a new AndroidDriver saying that the app capability must be set for reinstall (fair enough)

When setting the app capability I get the following error message when setting the additional option 'There is already an option for the appium:app capability. Please use the Application property instead. Arg_ParamName_Name'

Changing the app capability to Application reverts to the original error message 'app option is required for reinstall' when instantiating AndroidDriver

## Code To Reproduce Issue [ Good To Have ]

```
            var driverOption = new AppiumOptions();

            driverOption.AddAdditionalAppiumOption("DeviceName", "AndroidEmulatorPixel11");
            driverOption.AddAdditionalAppiumOption("platformName", "Android");
            driverOption.AddAdditionalAppiumOption("PlatformVersion", "11.0");
            driverOption.AddAdditionalAppiumOption("udid", "emulator-5554");
            driverOption.AddAdditionalAppiumOption("appPackage", _myAppPackage_);
            driverOption.AddAdditionalAppiumOption("appActivity", _myAppActivity_);
            driverOption.AddAdditionalAppiumOption("Application", _path/to/apk_);
            driverOption.AddAdditionalAppiumOption("fullReset", true);

            var driver = new AndroidDriver(new Uri("http://127.0.0.1:4723/wd/hub"), driverOption); //Gives error saying app capability needed
```

**Comment by alexlazarciuc** [comment]
@iparry7979 Hello, Might not be related, I am getting similar and wondering if you have it too, When creating the driver I am getting `OpenQA.Selenium.WebDriverException : Error : Platform and Browser not valid.` Wondering if you experienced similar?

**Comment by jlipps** [comment]
I'm not sure about the dotnet client, but `Application` is definitely not an Appium capability. `app` is the correct one. Sounds like there is some dotnet-specific way to set that capability?

**Comment by iparry7979** [comment]
So it seems. In the latest beta release when I set the app capability it says there is already an option for that capability - use the Application instead

**Comment by iparry7979** [comment]
Nevermind, I missed the part where it said to use the Application _property_. If any one else experiences this issue there are now properties on AppiumOptions class. Some capabilities are now set by directly setting the properties rather than calling AddAdditionalAppiumOptions.

**Comment by arpitkup** [comment]
> @iparry7979 Hello, Might not be related, I am getting similar and wondering if you have it too, When creating the driver I am getting `OpenQA.Selenium.WebDriverException : Error : Platform and Browser not valid.` Wondering if you experienced similar?
Hi @alexlazarciuc I am getting the same error with Appium 5.0.0 beta3. Did you figure out the solution ?

**Comment by Dor-bl** [comment]
Hi, @arpitkup please open a new issue since this one is closed and please use the issue template.
Thanks
