### ISSUE TITLE
No attribute for locating Android elements via link text?

### ISSUE THREAD

**Issue by gosr** [appium/appium-dotnet-driver#494]
Previously I've been using UIAutomator as the Appium driver for my project, but I am migrating to using Espresso instead.
I've been using the FindsByAndroidUIAutomatorAttribute, but I don't see any similar attribute for Espresso locators (e.g. link text).
The only one I found was FindsBySelendroidAttribute, but that is deprecated.

**Comment by jlipps** [comment]
As this client is not very well maintained, would you consider adding these attributes yourself as a contribution to the project?

**Comment by KazuCocoa** [comment]
Available locators in Espresso is https://github.com/appium/appium-espresso-driver#espresso-elements-location

Perhaps you can use them by https://github.com/appium/appium-dotnet-driver/blob/4570d11267572b861554142d39d4452d853e6118/src/Appium.Net/Appium/Enums/MobileSelector.cs as https://github.com/appium/appium-dotnet-driver/blob/4570d11267572b861554142d39d4452d853e6118/test/integration/PageObjectTests/DesktopBrowserCompatibility/FoundLinks.cs#L11-L12 (as an example)

**Comment by gosr** [comment]
Thanks for the input. I decided to locate elements on the fly instead of using attributes.
