### ISSUE TITLE
Newtonsoft.Json 13.0.1

### ISSUE THREAD

**Issue by yuqizhou77** [appium/appium-dotnet-driver#501]
Could someone check if Newtonsoft.Json could be bumped to 13.0.1. We are waiting for this update in Appium package for compliance requirements. Thanks!

Looks like there is a PR opened last week: https://github.com/appium/appium-dotnet-driver/pull/499 - could we check this in and when will the new version be released?

**Comment by KazuCocoa** [comment]
Perhaps a new version will come soon, thanks @akinsolb https://github.com/appium/appium-dotnet-driver/pull/502#issuecomment-1170471045

Then, please check if it will work for you.

**Comment by yuqizhou77** [comment]
Thank @KazuCocoa and @akinsolb !
Do you know when we will see the new version in nuget gallery?

**Comment by KazuCocoa** [comment]
Probably not yet? akinsholb may know of it.
https://github.com/appium/appium-dotnet-driver/releases/tag/v4.3.2

**Comment by yuqizhou77** [comment]
Guess this would be the one for nuget package? https://github.com/appium/appium-dotnet-driver/actions/runs/2597920478

**Comment by akinsolb** [comment]
@yuqizhou77 [Nuget is now published](https://www.nuget.org/packages/Appium.WebDriver/4.3.2)
