### ISSUE TITLE
Appium WebDriver 5.0.0-beta01 source code still doesn't support Selenium V4.0

### ISSUE THREAD

**Issue by RameshR66** [appium/appium-dotnet-driver#504]
Here's what I did, I referred the NuGet gallery for the Appium WebDriver 5.0.0-beta01 package and went through the source repository -

https://www.nuget.org/packages/Appium.WebDriver/5.0.0-beta01
https://github.com/appium/appium-dotnet-driver

When I try to run this code with Selenium Packages upgraded to version 4.0, I still get errors. For Example -

- There is no more Remote namespace in Selenium V4.0 and above
![image](https://user-images.githubusercontent.com/106594946/177710953-127908c5-bdf1-4d1a-9aaa-6f98645aea85.png)

![image](https://user-images.githubusercontent.com/106594946/177712898-addb01bc-51d3-4b69-bb97-8c9e1dd3929e.png)

Hence, classes like "RemoteWebElementFactory" will be no more available from Selenium for Appium to consume. This means there is a severe rework needs to be done to create any corresponding elements based on relevant platforms. 

- DesiredCapabilities class is made internal within Selenium as part of V4.0 due to deprecation. Hence AppiumCapabilities cannot inherit the class anymore. 

![image](https://user-images.githubusercontent.com/106594946/177713138-cdf0f6cf-89c8-4d53-8a31-32cc1ea57d43.png)

- There is no "CommandInfoRepository" to create a series of commands in a dictionary to run using ICommandExecutor.

![image](https://user-images.githubusercontent.com/106594946/177715592-15691f3d-2bc6-45c4-9edd-78e2cb9ec828.png)

I don't think the version 5.0.0-beta01 source code is reworked significantly to support the Selenium V4.0. I will check the forks to see if anyone has already done these modifications. Any thoughts on these issues and how we can approach this would be great.

Thanks.

**Comment by Dor-bl** [comment]
Hi, @RameshR66 .
Not sure where exactly you encounter an issue.
5.0.0-Beta01 does support Selenium 4.0, I've been using it for some time now in my solution.
can you provide the errors you are seeing?

**Comment by Dor-bl** [comment]
@akinsolb can be closed I assume, due to no response.
