### ISSUE TITLE
Why appium-dotnet-driver capabilities JSON contains "desiredCapabilities" and does not contains "alwaysMatch" ?

### ISSUE THREAD

**Issue by momentumsuite** [appium/appium-dotnet-driver#507]
## Description

Appium Capabilities JSON is the same with the latest Java, JS and Python Appium clients. But Dotnet W3C is different, contains both of "capabilities" and "desiredCapabilities". And "alwaysMatch" is empty on dotnet.  why?

## Environment

* Appium.WebDriver 4.3.2
* Appium v1.22.3
* Dotnetcoreapp 3.1
* MacOS Appium CLI (Server only)
* Node.js version v16.15.0
* Mobile platform/version under test: Android v11
* Real device or emulator/simulator: Real device

## Details

Why dotnet is different with the latest W3C supported version? How can I fix this on client side?

JAVA DEFAULT
{
  "capabilities": {
    "firstMatch": [
      {}
    ],
    "alwaysMatch": {
      "appium:app": "ms://......",
      "appium:autoGrantPermissions": true,
      "appium:automationName": "UIAutomator2",
      "appium:deviceName": "",
      "appium:fullReset": true,
      "appium:language": "en",
      "appium:locale": "en",
      "appium:noReset": false,
      "appium:platformName": "Android",
      "appium:udid": "",
      "momentum:options": {
        "gw": 4041,
        "user": "...",
        "token": "..."
      },
      "platformName": "android"
    }
  }
}

## Code To Reproduce Issue [ Good To Have ]

            AppiumOptions caps = new AppiumOptions();
            Dictionary<string, object> momentumOptions = new Dictionary<string, object>();
            momentumOptions.Add("user",momentumUser);
            momentumOptions.Add("token", momentumToken);
            momentumOptions.Add("gw", momentumDeviceId);
            caps.AddAdditionalCapability("momentum:options", momentumOptions);
            caps.AddAdditionalCapability("plarformName", "Android");
            caps.AddAdditionalCapability("appium:automationName", "UiAutomator2");
            caps.AddAdditionalCapability("appium:autoGrantPermissions", true);
            caps.AddAdditionalCapability("appium:language", "en");
            caps.AddAdditionalCapability("appium:locale", "en");
            caps.AddAdditionalCapability("appium:deviceName", "");
            caps.AddAdditionalCapability("appium:udid", "");
            caps.AddAdditionalCapability("appium:app", "https://momentumsuite.com/downloads/My-Bank-Wallet-v1.apk");
            caps.AddAdditionalCapability("appium:fullReset", true);
            caps.AddAdditionalCapability("appium:noReset", false);
            Console.WriteLine(caps);
            driver = new AndroidDriver<AppiumWebElement>(new Uri("http://momentumv2.mobven.com:8088/wd/hub"), caps);

**Comment by KazuCocoa** [comment]
It was since you used `4.3.2`. The version has both W3C and MJSONWP. Did you confirm v5 beta https://github.com/appium/appium-dotnet-driver/releases/tag/v5.0.0-beta01?

**Comment by momentumsuite** [comment]
Thanks, I will check the beta.
