### ISSUE TITLE
Could not load type 'OpenQA.Selenium.Internal.IFindsById' from assembly 'WebDriver, Version=4.0.0.0

### ISSUE THREAD

**Issue by pro-pintuyadav** [appium/appium-dotnet-driver#520]
Could not load type 'OpenQA.Selenium.Internal.IFindsById' from assembly 'WebDriver, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' 

Getting above error with below Selenium version:

Environment
1. .NET Core 3.1
2. Selenium.WebDriver (4.4.0)
3. Selenium.Support (4.4.0)
4. Appium.WebDriver (4.3.2)
5. Win 10 Visual studio pro 2019

**Comment by akinsolb** [comment]
Appium 4.3.2 doesn't support Selenium Webdriver v4 so I'm going to close this. If you're looking for a version that supports Selenium 4, then please try the [beta version](https://www.nuget.org/packages/Appium.WebDriver/5.0.0-beta01)
