### ISSUE TITLE
Selenium 4 support without page factory

### ISSUE THREAD

**Issue by pro-pintuyadav** [appium/appium-dotnet-driver#523]
## Description

After migration of Selenium 4, mobile scripts are getting fail. What is the Appium .NET Driver version supporting Selenium 4 without page factory and without Selenium Extra package. 

Element Format :IWebElement btnCancel => FindElement(By.XPath("//button/span[contains(.,'Cancel')]")); 

## Environment

* .NET client build version or git revision if you use some shapshot: .NET 6
* Appium server version or git revision if you use some shapshot: Latest
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: Andriod/iOS
* Real device or emulator/simulator: Real Device

**Comment by Dor-bl** [comment]
@pro-pintuyadav did you tried this version?
[v5.0.0_beta1](https://github.com/appium/appium-dotnet-driver/releases/tag/v5.0.0-beta01)

**Comment by Dor-bl** [comment]
@akinsolb, I see no response. So I think we can close it for now.
