### ISSUE TITLE
[Bug]: driver.get() not available

### ISSUE THREAD

**Issue by gosr** [appium/appium-dotnet-driver#534]
## Description

This article https://appiumpro.com/editions/7-speeding-up-tests-with-deep-links mentions that we can use driver.get() to launch the app with a deep link.

There is no Get() method available.

## Environment

Appium.Net 4.3.1

**Comment by KazuCocoa** [comment]
What about `driver.Nativate.GoToUrl`? This command's naming depends on selenium
https://appium.io/docs/en/commands/web/navigation/go-to-url/
https://www.selenium.dev/selenium/docs/api/dotnet/html/M_OpenQA_Selenium_INavigation_GoToUrl.htm

**Comment by gosr** [comment]
Thanks, that works.
