### ISSUE TITLE
Perfecto Real Devices and Appium 5.0/Selenium 4.x not working

### ISSUE THREAD

**Issue by kelmelzer** [appium/appium-dotnet-driver#535]
Hey all,

My company has a contract with Perfecto for mobile testing real devices in their cloud. I've been trying to update my web/mobile test automation framework to the latest Selenium since its about time to get off of 3.141, but I cannot due to issues acquiring their devices using the new W3C standards it seems. Here are capabilities that they say works and acquires one of our devices (in this case, a Galaxy S20) using Appium Java client 8.1.1 and Selenium Java `4.4.0:`

`String host = "xxx.perfectomobile.com";`
`String myToken = "xxx";`

`Map<String, Object> perfectoOptions = new HashMap<>();`

`UiAutomator2Options uiAutomator2Options = new UiAutomator2Options();`
`uiAutomator2Options.setCapability("platformName", "android");`
`perfectoOptions.put("securityToken", myToken);`
`perfectoOptions.put("deviceName", "RFCN208S8BP");`
`perfectoOptions.put("automationName", "appium");`
`perfectoOptions.put("appiumVersion", "2.0.0");`
`perfectoOptions.put("automationVersion", "1.70.1");`
`perfectoOptions.put("useAppiumForHybrid", false);`

`uiAutomator2Options.setCapability("perfecto:options", perfectoOptions);`

`AndroidDriver driver = new AndroidDriver(new URL("https://" + host + "/nexperience/perfectomobile/wd/hub"), uiAutomator2Options);`

I do the same thing with Selenium C# 4.5.1 (and previous versions like 4.2.0) and Appium 5.0.0beta1:

`private const string cloudName = "xxx";`
`private const string securityToken = "xxx";`

`Dictionary<string, object> perfectoOptions = new Dictionary<string, object>();`
`AppiumOptions appiumOptions = new AppiumOptions();`
`appiumOptions.PlatformName = "android";`
`perfectoOptions.Add("securityToken", securityToken);`
`perfectoOptions.Add("deviceName", "1A051FDF600M4J");`
`perfectoOptions.Add("automationName", "appium");`
`perfectoOptions.Add("appiumVersion", "2.0.0");`
`perfectoOptions.Add("automationVersion", "1.70.1");`
`perfectoOptions.Add("useAppiumForHybrid", false);`
`appiumOptions.AddAdditionalAppiumOption("perfecto:options", perfectoOptions);`

`AndroidDriver driver = new AndroidDriver(new Uri($"https://{cloudName}.perfectomobile.com/nexperience/perfectomobile/wd/hub"), appiumOptions);`

I end up getting this error:

OpenQA.Selenium.WebDriverException
  HResult=0x80131500
  Message=Access denied - bad credentials
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Appium.AppiumDriver..ctor(Uri remoteAddress, ICapabilities appiumOptions)
   at MyApp.Program.Main() 

Any ideas? I did a ticket with them, and they are still looking into it, but of course they are primarily a Java shop but few C# customers. My token works fine with Selenium 3.141 and Appium-Dotnet 4.3.

Here's a look at the JSON as well from appiumOptions:

appiumOptions
`{{
  "platformName": "Android",
  "perfecto:options": {
    "securityToken": "xxx",
    "deviceName": "RFCN208S8BP",
    "automationName": "appium",
    "appiumVersion": "2.0.0",
    "automationVersion": "1.70.1",
    "useAppiumForHybrid": false
  }
}}`

**Comment by KazuCocoa** [comment]
Perhaps the request body they got helps the investigation. (I mean the actual JSON request body they got)

**Comment by kelmelzer** [comment]
> Perhaps sharing the request body they got helps the investigation. (I mean the actual JSON request body they got)

I may be able to fire up Fiddler and get that info myself, too. I'll update later tomorrow.

**Comment by kelmelzer** [comment]
> > Perhaps sharing the request body they got helps the investigation. (I mean the actual JSON request body they got)
> 
> I may be able to fire up Fiddler and get that info myself, too. I'll update later tomorrow.

I was having issues with Fiddler locally, but Perfecto got back to me with this useful info:

Selenium Dotnet 4.5.1 with Appium does this:

`{
    "capabilities": {
        "firstMatch": [{
            "platformName": "Android",
            "perfecto:options": {
                "securityToken": ".....",
                "platformName": "Android",
                "browserName": "Chrome",
                "useAppiumForWeb": false,
                "automationName": "appium",
                "openDeviceTimeout": 2,
                "appiumVersion": "2.0.0",
                "automationVersion": "1.70.1"
            }
        }]
    }
}
`

while Java client 8 does this with the capabilities set as "alwaysMatch", which are then parsed correctly by them:

`{
  "capabilities": {
	"firstMatch": [{}],
	"alwaysMatch": {
		"appium:automationName": "UIAutomator2",
		"perfecto:options": {
			"securityToken": "......",
			"appPackage": "io.perfecto.expense.tracker.hybrid",
			"automationVersion": "1.70.1",
			"appiumVersion": "2.0.0",
			"automationName": "Appium",
			"enableAppiumBehavior": true,
			"scriptName": "Perfecto Support Test",
			"deviceName": "3552383734303098",
			"useAppiumForHybrid": true
		},
		"platformName": "android"
	}
  }
}
`

He was unable to force the dotnet client to send the capabilities in "alwaysMatch", but they're checking with their R&D team to see why this is happening and will keep me posted.

**Comment by KazuCocoa** [comment]
Hm, thank. I thought this client followed https://github.com/SeleniumHQ/selenium/blob/319acea1d52c617551f92f1233522171ae4db442/dotnet/src/webdriver/Remote/RemoteSessionSettings.cs#L260 but maybe not(?). We may be able to see the code around new session creation request in this client.

The format, only firstMatch, pattern existed in ld selenium v3 in some clients (in my head...) but the v3 had `desiredCapabilities`, which was valid for MJSONWP, as well.

**Comment by kelmelzer** [comment]
> Hm, thank. I thought this client followed https://github.com/SeleniumHQ/selenium/blob/319acea1d52c617551f92f1233522171ae4db442/dotnet/src/webdriver/Remote/RemoteSessionSettings.cs#L260 but maybe not(?). We may be able to see the code around new session creation request in this client.
> 
> The format, only firstMatch, pattern existed in ld selenium v3 in some clients (in my head...) but the v3 had `desiredCapabilities`, which was valid for MJSONWP, as well.

I pulled this from the W3C standards (https://www.w3.org/TR/webdriver/#dfn-new-session):

![image](https://user-images.githubusercontent.com/10146662/198397648-3029cad6-394e-4b6c-bd3e-ed032cfd548f.png)

My guess is Perfecto is not handling null/empty capabilities.alwaysMatch correctly like the spec requires? I tried the call myself to their server with PostMan, and their sample works fine when I post to /session with an empty JSON array in firstMatch and the capabilities moved to alwaysMatch instead.

**Comment by KazuCocoa** [comment]
Yes, it seems like it should be an empty object.

Btw, I quickly checked with vanilla Firefox's  options with the remote driver in the Selenium client. It sent the below, so this is not Appium dotnet client specific, but also the base's selenium client as well:

```
{"capabilities":{"firstMatch":[{"browserName":"firefox","moz:firefoxOptions":{}}]}}
```

Close this issue as not this client's issue. (If the cap needs to update, the update should be that parent's selenium's one)
