### ISSUE TITLE
[Bug]: I got Error

### ISSUE THREAD

**Issue by GodStar88** [appium/appium-dotnet-driver#544]
driver = new AndroidDriver<AndroidElement>(new Uri(http://127.0.01:4723/wd/hub), options, Env.INIT_TIMEOUT_SEC);

A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:4723/wd/hub/session. The status of the exception was ReceiveFailure, and the message was: The underlying connection was closed: An unexpected error occurred on a receive.

**Comment by Dor-bl** [comment]
@GodStar88 please mention appium server version and. Net appium client version

**Comment by GodStar88** [comment]
I tried 1.15.1 and 2.02

**Comment by Dor-bl** [comment]
If you use Appium web driver 4.4.0, you need to use something like that : _driver = new AndroidDriver<AndroidElement>(serverUri, capabilities, Env.InitTimeoutSec);

**Comment by GodStar88** [comment]
I i use 'option', what appium web version should i use?

_driver = new AndroidDriver <AndroidElement>'(serverUri, option, Env.InitTimeoutSec);

**Comment by Dor-bl** [comment]
My point was that you were missing the android driver type which is `<AndroidElement >`.
But from the logs it's seems like your emulator is crashing.
Regardless, please share the full snippet of your driver initialize so we can make sure that's the code is not the issue

**Comment by GodStar88** [comment]
AndroidDriver<AndroidElement> driver;
AppiumOptions options = new AppiumOptions();
options.AddAdditionalCapability(MobileCapabilityType.DeviceName, DeviceName);
options.AddAdditionalCapability(MobileCapabilityType.Udid, "127.0.0.1:21523");
options.AddAdditionalCapability(MobileCapabilityType.PlatformName, App.AndroidDeviceName());
options.AddAdditionalCapability(MobileCapabilityType.PlatformVersion, PlatformVersion);
options.AddAdditionalCapability(MobileCapabilityType.AutomationName, "UiAutomator1");
options.AddAdditionalCapability(MobileCapabilityType.NewCommandTimeout, 5 * 60 * 1000);
options.AddAdditionalCapability("systemPort", 8200);
options.AddAdditionalCapability("appPackage", "com.apple.android.music");
options.AddAdditionalCapability("appActivity", "com.apple.android.music.browse.BrowseMainNavigationActivity");
options.AddAdditionalCapability(MobileCapabilityType.App, App.AndroidAppleApp());
driver = new AndroidDriver<AndroidElement>(new Uri(http://127.0.01:4723/wd/hub), options, Env.INIT_TIMEOUT_SEC);
driver.Manage().Timeouts().ImplicitWait = Env.IMPLICIT_TIMEOUT_SEC;


Thank you for your message, Tha is my code

**Comment by Dor-bl** [comment]
I don't see `<AndroidElement>` in your new android driver line . Can you try and add it?

**Comment by GodStar88** [comment]
driver = new AndroidDriver<AndroidElement>(new Uri([http://127.0.01:4723/wd/hub](http://127.0.0.1:4723/wd/hub)), options, Env.INIT_TIMEOUT_SEC);

**Comment by GodStar88** [comment]
![image](https://user-images.githubusercontent.com/23701978/199927416-15236868-3a74-423a-857b-bf885e1fda1e.png)
I already added that when I copy code in GitHub it will disappear

**Comment by Dor-bl** [comment]
Try wrap your code with the add code style

**Comment by GodStar88** [comment]
can you check on anydesk?

**Comment by Dor-bl** [comment]
OK. So the code looks OK to me. Seems like your emulator is crashing, are you sure that the appium server is running and listening?

**Comment by GodStar88** [comment]
Yes
![image](https://user-images.githubusercontent.com/23701978/199927936-35784752-16ee-4751-8010-59ef2720857e.png)

**Comment by Dor-bl** [comment]
Your issue seems related to this one : https://github.com/appium/appium/issues/16141

**Comment by GodStar88** [comment]
Let me check

**Comment by GodStar88** [comment]
Thanks, fixed

**Comment by Dor-bl** [comment]
Happy to help, please close the issue. I don't have permissions to do it myself :)

**Comment by GodStar88** [comment]
Thanks again, Closed issue

**Comment by jlipps** [comment]
@Dor-bl made you a maintainer of this repo
