### ISSUE TITLE
[macOS] Sharing know issues with appium-dotnet-driver on macOS

### ISSUE THREAD

**Issue by Son-Nguyen2-Cerebral** [appium/appium-dotnet-driver#549]
Hi all,

I am working on the demonstration for automation mobile app with C# on macOS
If you are experienced with this one, could you share the issues/know issues that got when implementation?

Thanks,
SonNguyen

**Comment by Dor-bl** [comment]
Hello @Son-Nguyen2-Cerebral.
This is not a real issue, please use https://discuss.appium.io/
For questions like those.
