### ISSUE TITLE
What if capabilities of dotnet client would be synchronized with java client? 

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/appium-dotnet-driver#64]
Java client contains interesting things like:

- Page factory annotations and tools.

- actual method set and two AppiumDriver's (one for Android, another for iOS, I think that FirefoxOSDriver and WinPhoneDriver will be there in the future).

What if dotnet client would be the same?

**Comment by TikhomirovSergey** [comment]
Hi all! Lets start the new year of contributions!
The pull request is proposed to Selenium: https://github.com/SeleniumHQ/selenium/pull/304

**Comment by TikhomirovSergey** [comment]
Me and Jim Evans have reach an agreement. Now the requred change of PageFactory is on Selemium  side: https://github.com/SeleniumHQ/selenium/commit/689276b5e39c414edccf8a1bd11d71fd81b5fad4

**Comment by Jonahss** [comment]
Ooh! Does that affect the java-client PR you submitted?
(I haven't had a chance to play with it yet, super busy)

**Comment by TikhomirovSergey** [comment]
>Ooh! Does that affect the java-client PR you submitted?

@Jonahss 
It was about PageFactory on Selenium .Net side. Now we are able to implement the same for Appium .Net as it was done for Appium Java: https://github.com/appium/java-client/pull/68. Actually I have built updated Selenium locally and I'm working on it when I have free time. PR will be proposed when Selenium 2.46 will be released. 

One more reference: #84

**Comment by Jonahss** [comment]
Oh I see. Good work!

On Wed, Apr 15, 2015 at 1:41 AM, Sergey Tikhomirov <notifications@github.com

**Comment by TikhomirovSergey** [comment]
Yeah! Required changes are on Selenium side now. [(on behalf of Sergey Tikhomirov) Refactored PageFactory implementation, including a number of changes to make it more extensible and more robust....](https://raw.githubusercontent.com/SeleniumHQ/selenium/master/dotnet/CHANGELOG) I am going to propose a PR on this week or the beginning of the next!
