### ISSUE TITLE
HideKeyboard Crashes Appium

### ISSUE THREAD

**Issue by KDeeds** [appium/appium-dotnet-driver#73]
I recently just upgraded to 1.2.0.7 and updated methods and interfaces in my code. Most things seem to work the same except HideKeyboard() crashes Appium whenever I try to use it. I noticed its trying to send a symbol for hiding the keyboard.

info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"edafd8d2-5357-499b-b33e-82b8bf3c9585"}
info: <-- POST /wd/hub/session/edafd8d2-5357-499b-b33e-82b8bf3c9585/element/28/value 200 3676.050 ms - 74 {"status":0,"value":"","sessionId":"edafd8d2-5357-499b-b33e-82b8bf3c9585"}
info: --> GET /wd/hub/session/edafd8d2-5357-499b-b33e-82b8bf3c9585/element/28/name {}
info: [debug] Pushing command to appium work queue: "au.getElement('28').type()"
info: [debug] Sending command to instruments: au.getElement('28').type()
info: [debug] [INST] 2015-01-08 15:48:04 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-01-08 15:48:04 +0000 Debug: responding with:
info: [debug] [INST] 2015-01-08 15:48:04 +0000 Debug: Running system command #32: /usr/local/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...
info: [debug] [INST] 2015-01-08 15:48:05 +0000 Debug: Got new command 32 from instruments: au.getElement('28').type()
info: [debug] Socket data received (37 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":"UIASearchBar"}
info: [debug] Responding to client with success: {"status":0,"value":"UIASearchBar","sessionId":"edafd8d2-5357-499b-b33e-82b8bf3c9585"}
info: <-- GET /wd/hub/session/edafd8d2-5357-499b-b33e-82b8bf3c9585/element/28/name 200 968.173 ms - 86 {"status":0,"value":"UIASearchBar","sessionId":"edafd8d2-5357-499b-b33e-82b8bf3c9585"}
info: --> POST /wd/hub/session/edafd8d2-5357-499b-b33e-82b8bf3c9585/element/28/value {"value":[""],"keysToSend":[""]}
info: [debug] Pushing command to appium work queue: "au.getElement('28').setValueByType('')"
info: [debug] Sending command to instruments: au.getElement('28').setValueByType('')
info: [debug] [INST] 2015-01-08 15:48:05 +0000 Debug: evaluating au.getElement('28').type()
info: [debug] [INST] 2015-01-08 15:48:05 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-01-08 15:48:05 +0000 Debug: responding with:
info: [debug] [INST] 2015-01-08 15:48:05 +0000 Debug: Running system command #33: /usr/local/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":"UIASearchBar"}...
info: [debug] [INST] 2015-01-08 15:48:06 +0000 Debug: Got new command 33 from instruments: au.getElement('28').setValueByType('')
info: [debug] [INST] 2015-01-08 15:48:06 +0000 Debug: evaluating au.getElement('28').setValueByType('')
info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"edafd8d2-5357-499b-b33e-82b8bf3c9585"}
info: <-- POST /wd/hub/session/edafd8d2-5357-499b-b33e-82b8bf3c9585/element/28/value 200 1501.082 ms - 74 {"status":0,"value":"","sessionId":"edafd8d2-5357-499b-b33e-82b8bf3c9585"}

**Comment by TikhomirovSergey** [comment]
It seems I found the rootcause. The fix is here: #75
Here are some new tests.

**Comment by TikhomirovSergey** [comment]
The fix will be published as soon as possible.
