### ISSUE TITLE
GetScreenshot method is not working

### ISSUE THREAD

**Issue by pritamkarmakar** [appium/appium-dotnet-driver#74]
My intention is to take screenshot across different screens for my app, but the GetScreenshot() method is not working. I thought its a problem with my app but later on I tried with [this](http://appium.github.io/appium/assets/ApiDemos-debug.apk) sample app and the result is same. The byte array is empty in the screenshot object.

**Error:**
![screenshot](https://cloud.githubusercontent.com/assets/5255799/5669855/fd1ff50e-972f-11e4-86f7-55af01956c2f.png)

**Appium Log**: [here](https://gist.github.com/pritamkarmakar/e63b03ad436b9c88e79a)

Appreciate your help.

**Comment by TikhomirovSergey** [comment]
Hi @pritamkarmakar 
What library version do you use? Is it lower than v1.2.0.7? If it is so I think it was fixed at v1.2.0.7: https://github.com/appium/appium-dotnet-driver/commit/d50bacec4c7d2e7a9bd569760f1eb3704c065ee5#diff-604868d599c71b2aa1425d76b2289b83L480

This code works fine:
```c#
        [Test()]
        public void ScreenshotTestCase()
        {
            Screenshot screenshot = driver.GetScreenshot();
            Assert.IsNotNull(screenshot);
            screenshot.SaveAsFile("C:/CSharp/Test.jpeg", ImageFormat.Jpeg);
        }
```

The result: 
![test](https://cloud.githubusercontent.com/assets/4927589/5683395/8cc06000-9838-11e4-8812-2bff597e29ca.jpeg)

**Comment by pritamkarmakar** [comment]
@TikhomirovSergey : I'm using Appium v1.3.4. 

Looks like the issue is because of the API Level I'm using. When I'm running my test on simulator the APi Level is 21 and it is failing on it. But I just attached a real device which is on API Level 18 and it works fine.

**Comment by TikhomirovSergey** [comment]
Ok. If you can't reproduce it using API level < 21 so it is definetly on the server. Please describe your problem here: https://github.com/appium/appium/issues. 

> What library version do you use? Is it lower than v1.2.0.7
I meant the .Net client version :) There were something strange with the screenshot taking.

**Comment by pritamkarmakar** [comment]
I'm using v1.2.0.6. Let me try with 1.2.0.7.

**Comment by pritamkarmakar** [comment]
Sorry no luck with 1.2.0.7. This works fine with API level 18 but not with 21. Here is the simulator setting page - 
![screen shot 2015-01-12 at 1 10 07 pm](https://cloud.githubusercontent.com/assets/5255799/5711179/45dc6f86-9a5d-11e4-800a-b3c75e0b42ed.png)

**Comment by TikhomirovSergey** [comment]
Ok. Thanks for the environment description. Today I will try to reproduce the problem with emulator like above. So if it will be reproduced I will report this bug here: https://github.com/appium/appium/issues.

**Comment by pritamkarmakar** [comment]
I tried with API level 18, 19 from simulator and it doesn't work for 19 as well. Looks like this is not supported from API level 19 onwards.

**Comment by TikhomirovSergey** [comment]
It is strange... this screen shot was taken from Android 5.0 (API 21) :( 

![test](https://cloud.githubusercontent.com/assets/4927589/5731345/7797c7dc-9b93-11e4-8925-b6b8e806e5c2.jpeg)

**Comment by TikhomirovSergey** [comment]
@pritamkarmakar can you share capabilities which you use to instantiate appium driver?

**Comment by pritamkarmakar** [comment]
Please find below the capability setting -
```C#
  public static DesiredCapabilities getAndroid19Caps (string app) {
			DesiredCapabilities capabilities = new DesiredCapabilities();
			capabilities.SetCapability("browserName", "");
			capabilities.SetCapability("appium-version", "1.3.4");
			capabilities.SetCapability("platformName", "Android");
			capabilities.SetCapability("platformVersion", "5.0.1");
			capabilities.SetCapability("deviceName", "emulator-5554");
            capabilities.SetCapability("full reset", true);
            capabilities.SetCapability("noreset", false);
			capabilities.SetCapability("app", app);
			return capabilities;
		}
```

**Comment by TikhomirovSergey** [comment]
Hi, @pritamkarmakar. I have found the root cause. 
https://github.com/appium/appium/issues/3589
It is the known UI Automator (Android SDK) issue. ...And you are using the host GPU here. 

I can recommend you two ways to resolve this problem. 

- The first is to uncheck the "Use host GPU". But your emulator will be slow. 

- The second is to use Genymotion VM instead of emulator. It is much faster. ADB recognizes it as a device. My last screenshot was taken from Genymotion.

**Comment by pritamkarmakar** [comment]
I will try Genymotion and will let you know. Problem link that you given is for getting black screenshot, and I think this is different than my problem. I can repro this black screenshot issue with having 'host gpu' enabled in API 18.

But my problem was, with API level > 18 the byte array inside screenshot object is empty, and it is throwing exception while saving that file. I think these 2 issues are different. 

Also if you get chance can you try with the emulator comes with AVD?

**Comment by TikhomirovSergey** [comment]
Ok. Ok. Let me about your result with Genymotion.  

> I can repro this black screenshot issue with having 'host gpu' enabled in API 18.

Hmmm. Host GPU should be disabled.

**Comment by TikhomirovSergey** [comment]
Ok. Here is avd without host GPU:

![passed](https://cloud.githubusercontent.com/assets/4927589/5748312/ff8fb804-9c4f-11e4-8b8b-b45bb9049ddf.png)

The result is below:

![test](https://cloud.githubusercontent.com/assets/4927589/5748324/1183fdd6-9c50-11e4-977a-d1a7179fcaae.jpeg)

Now here is avd with host GPU:

![failed](https://cloud.githubusercontent.com/assets/4927589/5748500/8428adea-9c51-11e4-8f8c-974cd758b3dd.png)

The test is passed but here is only black space: 

![test](https://cloud.githubusercontent.com/assets/4927589/5748522/a82e7562-9c51-11e4-89d1-4af810e0bc2e.jpeg)

These pictures were taken from Windows 8. As I can see you are working on Mac OS X. Anyway "Use host GPU" affects Appium on Android.

What your results?

**Comment by TikhomirovSergey** [comment]
@pritamkarmakar I am closing this ticket because there is no response.
Please reopen it if you will find something related to this problem.
