### ISSUE TITLE
Multitouch api fails for double tap with cannot read property 'element' of undefined 

### ISSUE THREAD

**Issue by glorylo** [appium/appium-dotnet-driver#79]
I initially created this issue with appium but it turns out to be dotnet client.

This issue is related to https://github.com/appium/appium/issues/4310

```
          new TouchAction(driver)
                .Tap(point.X, point.Y, count: 2)
                .Perform(); 
```

Here's the trace:
```
> info: --> POST /wd/hub/session/8d6776f8-b84f-4fb5-ba04-4237bef7ba74/touch/perform {"actions":[{"action":"press","options":{"x":540,"y":1050}},{"action":"wait","options":{"ms":50}},{"action":"release"},{"action":"wait","options":{"ms":100}},{"action":"press","options":{"x":540,"y":540}},{"action":"wait","options":{"ms":50}},{"action":"release"}]}
> info: <-- POST /wd/hub/session/8d6776f8-b84f-4fb5-ba04-4237bef7ba74/touch/perform 500 0.804 ms - 97 
>     at Array.filter (native)
>     at Function._.filter._.select (C:\Workspace\appium\node_modules\underscore\underscore.js:173:65)
>     at _.(anonymous function) [as filter] (C:\Workspace\appium\node_modules\underscore\underscore.js:1178:39)
>     at null.<anonymous> (C:\Workspace\appium\lib\devices\android\android-controller.js:912:47)
>     at androidController.performTouch (C:\Workspace\appium\lib\devices\android\android-controller.js:990:5)
>     at Object.exports.performTouch [as handle] (C:\Workspace\appium\lib\server\controller.js:331:14)
>     at next_layer (C:\Workspace\appium\node_modules\express\lib\router\route.js:113:13)
>     at Route.dispatch (C:\Workspace\appium\node_modules\express\lib\router\route.js:117:5)
>     at C:\Workspace\appium\node_modules\express\lib\router\index.js:222:24

```

NOTE:  The {"action":"press","options":{"x":540,"y":540}} looks very suspicious as the "y" I am expecting it to be 1050

**Comment by Astro03** [comment]
I do not see this issue. 

I used the "Google Maps.apk" with appium. 

In my .NET code, I had 
>>>>>
var driver = new AndroidDriver(uri, caps);
new TouchAction(driver).Tap(300,300,2).Perform();
>>>>>>
The map zoomed in like it was supposed to.

Appium-dotnet-driver: 1.2.0.8
Appium-dot-app: 1.3.4

If you feel this is an error, please reopen this issue.

**Comment by glorylo** [comment]
Can you send me the test code.. It definitely happens for us and appium folks thinks it may be something with the client.  I've tested this on our app using 1.2.0.8 and appium 1.3.4.

**Comment by Astro03** [comment]
I did send you the test code and all the necessary information for reproduction. What else did you need?
