### ISSUE TITLE
How install that drivers

### ISSUE THREAD

**Issue by VladimirSozinov** [appium/appium-dotnet-driver#80]
Please explain me how install that drivers step by step, of course, if you have enough free time.
I try to build that solution, but don't get  .exe - file . What do I do wrong?

**Comment by Astro03** [comment]
the project produces a library (*.dll I think). Can you build without errors?

**Comment by VladimirSozinov** [comment]
Yes, it builds without errors, thanks!

**Comment by Astro03** [comment]
Can you close this or do you have other problems? If you just need the dll, you can use NuGet and get the package.  I believe it's called the same thing.

**Comment by VladimirSozinov** [comment]
Thanks! I have looked for reason - i don't launch my app(.cs)

**Comment by Astro03** [comment]
Closing since this issue seems to be a problem setting up your project and using references instead of an appium-dotnet-driver issue. If you have any other problems, please reopen the ticket.
