### ISSUE TITLE
malformed URL sent to server

### ISSUE THREAD

**Issue by glorylo** [appium/appium-dotnet-driver#82]
This issue is spawned from https://github.com/appium/appium/issues/4581

Log from appium server
```
info: --> POST /wd/hub/session//element {"using":"xpath","value":"//*[@resource-id='com.pof.android:id/thetitle']", "locator":"xpath"}
```

There are occasions when the a request is sent to server with malformed URL.  Has anyone seen this issue?

**Comment by Astro03** [comment]
I have not seen this issue. Anyone else? @jlipps @bootstraponline @penguinho

**Comment by penguinho** [comment]
I'd guess there's a + "/" in the code somewhere instead of a call to a URL string builder, whatever the URL equivalent of Path.Combine() is

**Comment by Astro03** [comment]
my suspicion is that this is a bug in the selenium remotewebdriver code and not the appium-dotnet-driver code. This appium code forwards all execution to the selenium code. Please open with them or reopen ticket if this is an appium-dotnet-driver bug. Thanks
