### ISSUE TITLE
Null reference exception while adding the custom commandInfo of AppiumDriver

### ISSUE THREAD

**Issue by pashidlos** [appium/appium-dotnet-driver#88]
Hello! 
I use new Webdriver 2.46.0 and I'm getting null reference exception in AppiumDriver.cs:
```
dynMethod.Invoke(CommandInfoRepository.Instance, new object[] { entry.Command, commandInfo });
```
Because this line returns null
```
var dynMethod = typeof(CommandInfoRepository).GetMethod("TryAddAdditionalCommand", BindingFlags.NonPublic | BindingFlags.Instance);
```
I've found that in new Selenium version 'TryAddAdditionalCommand' method in CommandInfoRepository was renamed to 'TryAddCommand' and was made public (https://raw.githubusercontent.com/SeleniumHQ/selenium/master/dotnet/CHANGELOG)
2.45.0 source:
https://code.google.com/p/selenium/source/browse/dotnet/src/webdriver/Remote/CommandInfoRepository.cs?name=selenium-2.45.0
2.46.0 source:
https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Remote/CommandInfoRepository.cs

So this code fixes it:
```
var dynMethod = typeof(CommandInfoRepository).GetMethod("TryAddAdditionalCommand", BindingFlags.NonPublic | BindingFlags.Instance);
if (dynMethod == null)
	        {
				dynMethod = typeof(CommandInfoRepository).GetMethod("TryAddCommand", BindingFlags.Public | BindingFlags.Instance);
	        }
```

If you don't mind I can submit pull request

**Comment by Jonahss** [comment]
Ooh! thank you :)
We shall have to update the other clients as well.

**Comment by Jonahss** [comment]
Can you submit a pull request?

**Comment by pashidlos** [comment]
Sure.
Please, take a look on it https://github.com/appium/appium-dotnet-driver/pull/89

**Comment by pashidlos** [comment]
How much time it can take to see these changes in new version?

**Comment by Jonahss** [comment]
Shouldn't be long. @Astro03 usually responds pretty quickly :)

**Comment by Astro03** [comment]
I accepted your pull request.  I'll make a build and push to NuGet.  Sorry for the delay.

**Comment by Astro03** [comment]
New package has been update - https://www.nuget.org/packages/Appium.WebDriver/.
Go to your source code and update your nuget packages.

**Comment by pashidlos** [comment]
Thank you!
