### ISSUE TITLE
Readme outdated - AppiumDriver is abstract class

### ISSUE THREAD

**Issue by BaN4NaJ0e** [appium/appium-dotnet-driver#91]
The README Example seems to be outdated. The class AppiumDriver is abstract. 
The line from the example: "driver = new AppiumDriver(new Uri("http://127.0.0.1:4723/wd/hub"), capabilities); "

will not work anymore. You have to use AndroidDriver or IOSDriver to create a new driver instance. 
Please update the example. The usage example in the class AppiumDriver seems to be outdated too. 

SNIPPET CODE from example:
...
private AppiumDriver driver;

        [TestFixtureSetUp]
        public void beforeAll(){
            DesiredCapabilities capabilities = new DesiredCapabilities();

            capabilities.SetCapability("deviceName", "iPhone Retina (4-inch 64-bit)");
            capabilities.SetCapability("platformName", "iOS");
            capabilities.SetCapability("platformVersion", "7.1");
            capabilities.SetCapability("app", "<Path to your app>");
            driver = new AppiumDriver(new Uri("http://127.0.0.1:4723/wd/hub"), capabilities);       
        }

...

**Comment by Jonahss** [comment]
Thanks.
You could submit a pull request to correct it if you want :)

**Comment by TikhomirovSergey** [comment]
Fixed!
